/*
 * Copyright 2026 Clidey, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
    Button,
    cn,
    ScrollArea,
    Sidebar as SidebarComponent,
    SidebarContent,
    SidebarGroup,
    SidebarHeader
} from "@clidey/ux";
import { ChatBubbleLeftRightIcon, PlusCircleIcon, TrashIcon } from "../../components/heroicons";
import { ChangeEvent, FC, useCallback, useEffect, useRef, useState } from "react";
import { useTranslation } from "../../hooks/use-translation";
import { useAppDispatch, useAppSelector } from "../../store/hooks";
import { ChatSession, HoudiniActions } from "../../store/chat";

type EditableSessionNameProps = {
    session: ChatSession;
    isActive: boolean;
    onUpdate: (sessionId: string, newName: string) => void;
};

const EditableSessionName: FC<EditableSessionNameProps> = ({ session, isActive, onUpdate }) => {
    const { t } = useTranslation('pages/chat');
    const [currentContent, setCurrentContent] = useState(session.name);
    const [displayContent, setDisplayContent] = useState(session.name);
    const [isEditing, setIsEditing] = useState(false);
    const inputRef = useRef<HTMLInputElement | null>(null);
    const targetTextRef = useRef(session.name);
    const typingIntervalRef = useRef<number | null>(null);

    // Typewriter effect when session.name changes (auto-generated title)
    useEffect(() => {
        if (!isEditing && session.name !== targetTextRef.current) {
            const oldName = targetTextRef.current;
            targetTextRef.current = session.name;

            // Clear previous interval if any
            if (typingIntervalRef.current) {
                clearInterval(typingIntervalRef.current);
                typingIntervalRef.current = null;
            }

            setCurrentContent(session.name);

            // Only do typewriter effect if transitioning from a default name to an auto-generated one
            const isDefaultName = oldName.startsWith('Chat ');
            const isAutoGenerated = !session.name.startsWith('Chat ');

            if (isDefaultName && isAutoGenerated) {
                setDisplayContent('');

                let currentIndex = 0;
                typingIntervalRef.current = window.setInterval(() => {
                    currentIndex++;
                    setDisplayContent(session.name.slice(0, currentIndex));

                    if (currentIndex >= session.name.length) {
                        if (typingIntervalRef.current) {
                            clearInterval(typingIntervalRef.current);
                            typingIntervalRef.current = null;
                        }
                    }
                }, 30);
            } else {
                setDisplayContent(session.name);
            }
        }

        return () => {
            if (typingIntervalRef.current) {
                clearInterval(typingIntervalRef.current);
                typingIntervalRef.current = null;
            }
        };
    }, [session.name, isEditing]);

    const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
        setCurrentContent(event.target.value);
    };

    const handleBlur = () => {
        if (currentContent !== session.name && currentContent.trim() !== "") {
            onUpdate(session.id, currentContent);
        } else if (currentContent.trim() === "") {
            // Revert to original name if empty
            setCurrentContent(session.name);
        }
        setIsEditing(false);
    };

    const handleDoubleClick = () => {
        setIsEditing(true);
        setTimeout(() => inputRef.current?.focus(), 0);
    };

    return (
        <div className="flex-1 min-w-0 overflow-hidden w-full" onClick={() => inputRef.current?.focus()} onDoubleClick={handleDoubleClick}>
            {isEditing ? (
                <input
                    ref={inputRef}
                    type="text"
                    value={currentContent}
                    onChange={handleChange}
                    onBlur={handleBlur}
                    onKeyDown={(e) => {
                        if (e.key === 'Enter') {
                            handleBlur();
                        } else if (e.key === 'Escape') {
                            setCurrentContent(session.name);
                            setIsEditing(false);
                        }
                    }}
                    autoFocus
                    className="w-full border-b border-gray-400 bg-transparent transition-colors text-xs outline-none"
                    data-testid={`chat-session-name-input-${session.id}`}
                    style={{ height: '20px' }}
                />
            ) : (
                <span
                    className={cn("text-xs block w-full", {
                        "text-primary font-medium": isActive,
                        "truncate": displayContent === currentContent,
                    })}
                    data-testid={`chat-session-name-${session.id}`}
                    title=""
                >
                    {displayContent || t('doubleClickEdit')}
                    {displayContent !== currentContent && displayContent.length > 0 && (
                        <span className="animate-pulse ml-px">|</span>
                    )}
                </span>
            )}
        </div>
    );
};

export const ChatHistorySidebar: FC = () => {
    const { t } = useTranslation('pages/chat');
    const dispatch = useAppDispatch();
    const { sessions, activeSessionId } = useAppSelector(state => state.houdini);
    const [confirmOpen, setConfirmOpen] = useState(false);
    const [sessionToDelete, setSessionToDelete] = useState<string | null>(null);

    const handleAddSession = useCallback(() => {
        dispatch(HoudiniActions.addChatSession({ name: `Chat ${sessions.length + 1}` }));
    }, [dispatch, sessions.length]);

    const handleSelectSession = useCallback((sessionId: string) => {
        dispatch(HoudiniActions.setActiveSession({ sessionId }));
    }, [dispatch]);

    const promptDelete = useCallback((sessionId: string) => {
        setSessionToDelete(sessionId);
        setConfirmOpen(true);
    }, []);

    const handleDelete = useCallback(() => {
        if (sessionToDelete) {
            dispatch(HoudiniActions.deleteChatSession({ sessionId: sessionToDelete }));
        }
        setConfirmOpen(false);
        setSessionToDelete(null);
    }, [dispatch, sessionToDelete]);

    const handleUpdateSessionName = useCallback((sessionId: string, newName: string) => {
        dispatch(HoudiniActions.updateSessionName({ sessionId, name: newName }));
    }, [dispatch]);

    return (
        <>
            <div className="flex h-full dark" data-testid="chat-history-sidebar">
                <SidebarComponent variant="embed" className="w-64 h-full flex flex-col">
                    <SidebarHeader>
                        <div className="flex items-center justify-between">
                            <h2 className="text-sm font-semibold">{t('chatHistory')}</h2>
                            <Button
                                variant="ghost"
                                size="sm"
                                onClick={handleAddSession}
                                data-testid="add-chat-session-button"
                                aria-label={t('newChat')}
                            >
                                <PlusCircleIcon className="w-4 h-4" />
                            </Button>
                        </div>
                    </SidebarHeader>
                    <SidebarContent>
                        <SidebarGroup>
                            <ScrollArea className="h-full">
                                <div className="flex flex-col gap-1 p-2">
                                {sessions.map((session) => {
                                    const isActive = session.id === activeSessionId;
                                    const messageCount = session.messages.length;

                                    return (
                                        <div
                                            key={session.id}
                                            className={cn(
                                                "flex items-center gap-2 p-2 rounded-md cursor-pointer hover:bg-muted/50 transition-colors group/session w-full max-w-full",
                                                {
                                                    "bg-muted": isActive,
                                                }
                                            )}
                                            onClick={() => handleSelectSession(session.id)}
                                            data-testid={`chat-session-item-${session.id}`}
                                        >
                                            <ChatBubbleLeftRightIcon className={cn("w-4 h-4 shrink-0", {
                                                "text-primary": isActive,
                                            })} />
                                            <div className="flex-1 min-w-0 flex flex-col overflow-hidden max-w-[calc(100%-3rem)] hover:max-w-[calc(100%-3rem)]">
                                                <EditableSessionName
                                                    session={session}
                                                    isActive={isActive}
                                                    onUpdate={handleUpdateSessionName}
                                                />
                                                <div className="text-xs text-muted-foreground truncate w-full" title="">
                                                    {messageCount > 0 ? t('messageCount', { count: messageCount }) : t('noMessages')}
                                                </div>
                                            </div>
                                            {sessions.length > 1 && (
                                                <Button
                                                    variant="ghost"
                                                    size="sm"
                                                    className="shrink-0 hidden group-hover/session:flex absolute right-4"
                                                    onClick={(e) => {
                                                        e.stopPropagation();
                                                        promptDelete(session.id);
                                                    }}
                                                    data-testid={`delete-chat-session-${session.id}`}
                                                    aria-label={t('deleteChat')}
                                                >
                                                    <TrashIcon className="w-4 h-4 text-destructive" />
                                                </Button>
                                            )}
                                        </div>
                                    );
                                })}
                            </div>
                        </ScrollArea>
                    </SidebarGroup>
                </SidebarContent>
            </SidebarComponent>
            </div>

            <AlertDialog open={confirmOpen} onOpenChange={setConfirmOpen}>
                <AlertDialogContent>
                    <AlertDialogHeader>
                        <AlertDialogTitle>
                            {t('deleteChatTitle', { chatName: sessions.find(s => s.id === sessionToDelete)?.name ?? 'chat' })}
                        </AlertDialogTitle>
                        <AlertDialogDescription>
                            {t('deleteChatDescription')}
                        </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                        <AlertDialogCancel data-testid="delete-chat-cancel">{t('cancel')}</AlertDialogCancel>
                        <AlertDialogAction asChild>
                            <Button
                                variant="destructive"
                                onClick={handleDelete}
                                data-testid="delete-chat-confirm"
                            >
                                {t('continue')}
                            </Button>
                        </AlertDialogAction>
                    </AlertDialogFooter>
                </AlertDialogContent>
            </AlertDialog>
        </>
    );
};
