/**
 * Copyright 2025 Clidey, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { CircleStackIcon, UsersIcon, UserGroupIcon, InformationCircleIcon, PresentationChartLineIcon, ShoppingBagIcon, BuildingStorefrontIcon, BanknotesIcon, PresentationChartBarIcon } from "../../components/heroicons";

export const chatExamples = [
    {
        icon: <CircleStackIcon className="w-4 h-4" />,
        description: "Get summary of all the purchase orders",
    },
    {
        icon: <UsersIcon className="w-4 h-4" />,
        description: "List all customers who made a purchase in the last month",
    },
    {
        icon: <UserGroupIcon className="w-4 h-4" />,
        description: "Show the top 10 customers by total spend",
    },
    {
        icon: <InformationCircleIcon className="w-4 h-4" />,
        description: "Provide a summary of customer feedback for the past year",
    },
    {
        icon: <PresentationChartLineIcon className="w-4 h-4" />,
        description: "List all purchase orders placed within the last week",
    },
    {
        icon: <PresentationChartLineIcon className="w-4 h-4" />,
        description: "Summarize total sales by region for this quarter",
    },
    {
        icon: <UserGroupIcon className="w-4 h-4" />,
        description: "Show the average order value for each product category",
    },
    {
        icon: <ShoppingBagIcon className="w-4 h-4" />,
        description: "List all products that are currently out of stock",
    },
    {
        icon: <ShoppingBagIcon className="w-4 h-4" />,
        description: "Show the top 5 best-selling products in the electronics category",
    },
    {
        icon: <BuildingStorefrontIcon className="w-4 h-4" />,
        description: "Provide the total count of different products in each warehouse",
    },
    {
        icon: <UserGroupIcon className="w-4 h-4" />,
        description: "List all employees who joined in the last six months",
    },
    {
        icon: <UserGroupIcon className="w-4 h-4" />,
        description: "Get a summary of employee demographics by department",
    },
    {
        icon: <UserGroupIcon className="w-4 h-4" />,
        description: "Show the average salary for software engineers",
    },
    {
        icon: <BanknotesIcon className="w-4 h-4" />,
        description: "Provide a breakdown of expenses by department for the last financial year",
    },
    {
        icon: <BanknotesIcon className="w-4 h-4" />,
        description: "Summarize the profit and loss statement for the last quarter",
    },
    {
        icon: <BanknotesIcon className="w-4 h-4" />,
        description: "Show the total revenue generated by each sales channel",
    },
    {
        icon: <PresentationChartBarIcon className="w-4 h-4" />,
        description: "Provide a list of all active marketing campaigns",
    },
    {
        icon: <PresentationChartBarIcon className="w-4 h-4" />,
        description: "Summarize the click-through rates of email campaigns for the last quarter",
    },
    {
        icon: <PresentationChartBarIcon className="w-4 h-4" />,
        description: "Show the total number of leads generated by each campaign",
    },
    {
        icon: <PresentationChartBarIcon className="w-4 h-4" />,
        description: "List all ongoing projects and their current status",
    },
    {
        icon: <PresentationChartBarIcon className="w-4 h-4" />,
        description: "Get a summary of project deadlines and milestones for the next quarter",
    },
    {
        icon: <PresentationChartBarIcon className="w-4 h-4" />,
        description: "Show the top 5 projects by budget allocation",
    },
    {
        icon: <PresentationChartBarIcon className="w-4 h-4" />,
        description: "Provide a trend analysis of website traffic for the past six months",
    },
    {
        icon: <PresentationChartBarIcon className="w-4 h-4" />,
        description: "Summarize the conversion rates by traffic source",
    },
    {
        icon: <PresentationChartBarIcon className="w-4 h-4" />,
        description: "Show the top-performing keywords in our search engine marketing campaigns",
    },
    {
        icon: <PresentationChartBarIcon className="w-4 h-4" />,
        description: "List all transactions flagged for audit in the last year",
    },
    {
        icon: <PresentationChartBarIcon className="w-4 h-4" />,
        description: "Summarize compliance issues reported by region",
    },
    {
        icon: <PresentationChartBarIcon className="w-4 h-4" />,
        description: "Show a report of all policy violations in the last quarter",
    },
];