// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type ChatResponseClassView struct {
	inner baml.ClassBuilder
}

func (t *ChatResponseClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ChatResponseClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *ChatResponseClassView) PropertyOperation() (ClassPropertyView, error) {
	return t.inner.Property("operation")
}

func (t *ChatResponseClassView) PropertyText() (ClassPropertyView, error) {
	return t.inner.Property("text")
}

func (t *TypeBuilder) ChatResponse() (*ChatResponseClassView, error) {
	bld, err := t.inner.Class("ChatResponse")
	if err != nil {
		return nil, err
	}
	return &ChatResponseClassView{inner: bld}, nil
}

func (t *ChatResponseClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type DatabaseContextClassView struct {
	inner baml.ClassBuilder
}

func (t *DatabaseContextClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DatabaseContextClassView) PropertyDatabase_type() (ClassPropertyView, error) {
	return t.inner.Property("database_type")
}

func (t *DatabaseContextClassView) PropertySchema() (ClassPropertyView, error) {
	return t.inner.Property("schema")
}

func (t *DatabaseContextClassView) PropertyTables_and_fields() (ClassPropertyView, error) {
	return t.inner.Property("tables_and_fields")
}

func (t *DatabaseContextClassView) PropertyPrevious_conversation() (ClassPropertyView, error) {
	return t.inner.Property("previous_conversation")
}

func (t *TypeBuilder) DatabaseContext() (*DatabaseContextClassView, error) {
	bld, err := t.inner.Class("DatabaseContext")
	if err != nil {
		return nil, err
	}
	return &DatabaseContextClassView{inner: bld}, nil
}

func (t *DatabaseContextClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
