// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type ChatMessageTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *ChatMessageTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ChatMessageTypeEnumView) ValueSQL() (EnumValueView, error) {
	return t.inner.Value("SQL")
}

func (t *ChatMessageTypeEnumView) ValueMESSAGE() (EnumValueView, error) {
	return t.inner.Value("MESSAGE")
}

func (t *ChatMessageTypeEnumView) ValueERROR() (EnumValueView, error) {
	return t.inner.Value("ERROR")
}

func (t *TypeBuilder) ChatMessageType() (*ChatMessageTypeEnumView, error) {
	bld, err := t.inner.Enum("ChatMessageType")
	if err != nil {
		return nil, err
	}
	return &ChatMessageTypeEnumView{inner: bld}, nil
}

func (t *ChatMessageTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type OperationTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *OperationTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *OperationTypeEnumView) ValueGET() (EnumValueView, error) {
	return t.inner.Value("GET")
}

func (t *OperationTypeEnumView) ValueINSERT() (EnumValueView, error) {
	return t.inner.Value("INSERT")
}

func (t *OperationTypeEnumView) ValueUPDATE() (EnumValueView, error) {
	return t.inner.Value("UPDATE")
}

func (t *OperationTypeEnumView) ValueDELETE() (EnumValueView, error) {
	return t.inner.Value("DELETE")
}

func (t *OperationTypeEnumView) ValueTEXT() (EnumValueView, error) {
	return t.inner.Value("TEXT")
}

func (t *TypeBuilder) OperationType() (*OperationTypeEnumView, error) {
	bld, err := t.inner.Enum("OperationType")
	if err != nil {
		return nil, err
	}
	return &OperationTypeEnumView{inner: bld}, nil
}

func (t *OperationTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}
