// render/go.mjs — Go renderer for generate-core.mjs. Emits the generated wire
// core (package gen) consumed by the handwritten whodb-go facade. Operations
// are transport-agnostic request builders, mirroring the Python renderer.
import { isEnumType, isScalarType, isInputObjectType, isObjectType, isNonNullType, isListType, getNamedType } from 'graphql';

const SCALAR_GO = {
  ID: 'string',
  String: 'string',
  Int: 'int',
  Float: 'float64',
  Boolean: 'bool',
};

function header(ir) {
  return `// Code generated by sdk/tools/generate-core.mjs — DO NOT EDIT (manifest ${ir.manifestHash.slice(0, 12)}).\n\npackage gen\n`;
}

function exported(name) {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function goTypeOf(gqlType, ir) {
  // Nullable values use pointers; lists are slices (nil = absent).
  if (isNonNullType(gqlType)) return goTypeOfInner(gqlType.ofType, false, ir);
  return goTypeOfInner(gqlType, true, ir);
}

function goTypeOfInner(gqlType, nullable, ir) {
  if (isListType(gqlType)) {
    return `[]${goTypeOf(gqlType.ofType, ir)}`; // slices are already nilable
  }
  const named = getNamedType(gqlType);
  let go;
  if (SCALAR_GO[named.name]) {
    go = SCALAR_GO[named.name];
  } else if (isScalarType(named)) {
    go = 'any';
  } else if (isEnumType(named)) {
    go = 'string';
  } else {
    go = named.name;
  }
  if (nullable && go !== 'any') return `*${go}`;
  return go;
}

function renderTypes(ir) {
  const lines = [header(ir)];
  const sorted = [...ir.typeClosure].sort();
  for (const name of sorted) {
    const type = ir.schema.getType(name);
    if (!type) continue;
    if (isEnumType(type)) {
      lines.push(`// ${name} travels as a string on the wire. Values: ${type.getValues().map(v => v.name).join(', ')}.`);
      lines.push(`type ${name} = string`);
      lines.push('');
      continue;
    }
    if (isInputObjectType(type) || isObjectType(type)) {
      lines.push(`// ${name} mirrors the GraphQL type ${name}.`);
      lines.push(`type ${name} struct {`);
      for (const field of Object.values(type.getFields())) {
        const goType = goTypeOf(field.type, ir);
        const omit = isNonNullType(field.type) ? '' : ',omitempty';
        lines.push(`\t${exported(field.name)} ${goType} \`json:"${field.name}${omit}"\``);
      }
      lines.push('}');
      lines.push('');
    }
  }
  return lines.join('\n');
}

function renderOperations(ir) {
  const lines = [header(ir)];
  lines.push('// Request is one prepared platform operation: document + variables.');
  lines.push('type Request struct {');
  lines.push('\tOperation string');
  lines.push('\tDocument  string');
  lines.push('\tVariables map[string]any');
  lines.push('}');
  lines.push('');
  for (const op of ir.operations) {
    lines.push(`// ${exported(op.name)}Document is the wire document for ${op.kind} ${op.name}.`);
    lines.push(`const ${exported(op.name)}Document = ${JSON.stringify(op.document)}`);
    lines.push('');
    lines.push(`// New${exported(op.name)}Request builds the wire request for ${op.kind} ${op.name}.`);
    lines.push(`func New${exported(op.name)}Request(variables map[string]any) Request {`);
    lines.push(`\treturn Request{Operation: "${op.name}", Document: ${exported(op.name)}Document, Variables: variables}`);
    lines.push('}');
    lines.push('');
  }
  return lines.join('\n');
}

function renderManifest(ir) {
  const lines = [header(ir)];
  lines.push('// OperationPolicy carries an operation\'s versioning-policy state.');
  lines.push('type OperationPolicy struct {');
  lines.push('\tKind            string');
  lines.push('\tDeprecated      bool');
  lines.push('\tSunsetAt        string');
  lines.push('\tBehaviorChanged bool');
  lines.push('\tNote            string');
  lines.push('}');
  lines.push('');
  lines.push('// EmbeddedManifest maps operation names to their policy state at generation time.');
  lines.push('var EmbeddedManifest = map[string]OperationPolicy{');
  for (const op of ir.operations) {
    const parts = [`Kind: "${op.kind}"`];
    if (op.deprecated) parts.push('Deprecated: true');
    if (op.sunsetAt) parts.push(`SunsetAt: ${JSON.stringify(op.sunsetAt)}`);
    if (op.behaviorChanged) parts.push('BehaviorChanged: true');
    if (op.note) parts.push(`Note: ${JSON.stringify(op.note)}`);
    lines.push(`\t"${op.name}": {${parts.join(', ')}},`);
  }
  lines.push('}');
  lines.push('');
  lines.push('// ManifestHash is the SHA-256 of the platform-manifest.json this SDK was generated from.');
  lines.push(`const ManifestHash = "${ir.manifestHash}"`);
  lines.push('');
  lines.push('// ManifestProtocolVersion is the manifest protocol this SDK understands.');
  lines.push(`const ManifestProtocolVersion = "${ir.protocolVersion}"`);
  return lines.join('\n') + '\n';
}

function renderHydration(ir) {
  const lines = [header(ir)];
  lines.push('// HydrationRules maps lowercase column type names to coercion kinds,');
  lines.push('// shared verbatim across all SDK languages.');
  lines.push('var HydrationRules = map[string]string{');
  for (const [key, kind] of Object.entries(ir.hydrationRules.rules)) {
    lines.push(`\t${JSON.stringify(key)}: ${JSON.stringify(kind)},`);
  }
  lines.push('}');
  lines.push('');
  lines.push('// HydrationDefault is the fallback coercion kind.');
  lines.push(`const HydrationDefault = ${JSON.stringify(ir.hydrationRules.default)}`);
  return lines.join('\n') + '\n';
}

export function renderGo(ir) {
  return [
    ['types.go', renderTypes(ir)],
    ['operations.go', renderOperations(ir)],
    ['manifest.go', renderManifest(ir)],
    ['hydration.go', renderHydration(ir)],
  ];
}
