// render/java.mjs — Java renderer for generate-core.mjs. Emits the generated
// wire core (package com.clidey.whodb.gen) consumed by the handwritten
// whodb-sdk Java facade. Rows stay dynamic (Map<String, Object>), matching
// the Go and Rust SDKs.

function header(ir) {
  return `// Code generated by sdk/tools/generate-core.mjs — DO NOT EDIT (manifest ${ir.manifestHash.slice(0, 12)}).\npackage com.clidey.whodb.gen;\n`;
}

function renderOperations(ir) {
  const lines = [header(ir)];
  lines.push('import java.util.Map;');
  lines.push('');
  lines.push('/** Generated wire operations: documents and request builders. */');
  lines.push('public final class Operations {');
  lines.push('    private Operations() {}');
  lines.push('');
  lines.push('    /** One prepared platform operation: document + variables. */');
  lines.push('    public record Request(String operation, String document, Map<String, Object> variables) {}');
  lines.push('');
  for (const op of ir.operations) {
    const constName = op.name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
    lines.push(`    /** Wire document for ${op.kind} ${op.name}. */`);
    lines.push(`    public static final String ${constName}_DOCUMENT = ${JSON.stringify(op.document)};`);
    lines.push('');
    lines.push(`    /** Builds the wire request for ${op.kind} ${op.name}. */`);
    lines.push(`    public static Request ${op.name.charAt(0).toLowerCase() + op.name.slice(1)}Request(Map<String, Object> variables) {`);
    lines.push(`        return new Request("${op.name}", ${constName}_DOCUMENT, variables);`);
    lines.push('    }');
    lines.push('');
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

function renderManifest(ir) {
  const lines = [header(ir)];
  lines.push('import java.util.Map;');
  lines.push('');
  lines.push('/** Per-operation versioning-policy state embedded at generation time. */');
  lines.push('public final class Manifest {');
  lines.push('    private Manifest() {}');
  lines.push('');
  lines.push('    /** One operation\'s policy state. */');
  lines.push('    public record OperationPolicy(String kind, boolean deprecated, String sunsetAt, boolean behaviorChanged, String note) {}');
  lines.push('');
  lines.push('    /** SHA-256 of the platform-manifest.json this SDK was generated from. */');
  lines.push(`    public static final String MANIFEST_HASH = "${ir.manifestHash}";`);
  lines.push('');
  lines.push('    /** Manifest protocol version this SDK understands. */');
  lines.push(`    public static final String MANIFEST_PROTOCOL_VERSION = "${ir.protocolVersion}";`);
  lines.push('');
  lines.push('    /** Operation name → policy. */');
  lines.push('    public static final Map<String, OperationPolicy> EMBEDDED = Map.ofEntries(');
  const entries = ir.operations.map(op =>
    `        Map.entry("${op.name}", new OperationPolicy("${op.kind}", ${!!op.deprecated}, ${JSON.stringify(op.sunsetAt ?? '')}, ${!!op.behaviorChanged}, ${JSON.stringify(op.note ?? '')}))`
  );
  lines.push(entries.join(',\n'));
  lines.push('    );');
  lines.push('}');
  return lines.join('\n') + '\n';
}

function renderHydration(ir) {
  const lines = [header(ir)];
  lines.push('import java.util.Map;');
  lines.push('');
  lines.push('/** Column-type → coercion kind rules shared across all SDK languages. */');
  lines.push('public final class Hydration {');
  lines.push('    private Hydration() {}');
  lines.push('');
  lines.push('    /** Fallback coercion kind. */');
  lines.push(`    public static final String DEFAULT_KIND = ${JSON.stringify(ir.hydrationRules.default)};`);
  lines.push('');
  lines.push('    /** Lowercase column type name → coercion kind. */');
  lines.push('    public static final Map<String, String> RULES = Map.ofEntries(');
  const entries = Object.entries(ir.hydrationRules.rules).map(
    ([key, kind]) => `        Map.entry(${JSON.stringify(key)}, ${JSON.stringify(kind)})`
  );
  lines.push(entries.join(',\n'));
  lines.push('    );');
  lines.push('}');
  return lines.join('\n') + '\n';
}

export function renderJava(ir) {
  return [
    ['Operations.java', renderOperations(ir)],
    ['Manifest.java', renderManifest(ir)],
    ['Hydration.java', renderHydration(ir)],
  ];
}
