// render/rust.mjs — Rust renderer for generate-core.mjs. Emits the generated
// wire core (module gen) consumed by the handwritten whodb-sdk crate.
// Operations are transport-agnostic request builders; rows stay dynamic
// (serde_json::Value), matching the Go SDK's model.

function header(ir) {
  return `// Code generated by sdk/tools/generate-core.mjs — DO NOT EDIT (manifest ${ir.manifestHash.slice(0, 12)}).\n`;
}

function renderOperations(ir) {
  const lines = [header(ir)];
  lines.push('use serde_json::{Map, Value};');
  lines.push('');
  lines.push('/// One prepared platform operation: document + variables.');
  lines.push('pub struct Request {');
  lines.push('    pub operation: &\'static str,');
  lines.push('    pub document: &\'static str,');
  lines.push('    pub variables: Map<String, Value>,');
  lines.push('}');
  lines.push('');
  for (const op of ir.operations) {
    const constName = op.name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
    const fnName = op.name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
    lines.push(`/// Wire document for ${op.kind} ${op.name}.`);
    lines.push(`pub const ${constName}_DOCUMENT: &str = ${JSON.stringify(op.document)};`);
    lines.push('');
    lines.push(`/// Builds the wire request for ${op.kind} ${op.name}.`);
    lines.push(`pub fn ${fnName}_request(variables: Map<String, Value>) -> Request {`);
    lines.push(`    Request { operation: "${op.name}", document: ${constName}_DOCUMENT, variables }`);
    lines.push('}');
    lines.push('');
  }
  return lines.join('\n');
}

function renderManifest(ir) {
  const lines = [header(ir)];
  lines.push('/// An operation\'s versioning-policy state at generation time.');
  lines.push('pub struct OperationPolicy {');
  lines.push('    pub kind: &\'static str,');
  lines.push('    pub deprecated: bool,');
  lines.push('    pub sunset_at: &\'static str,');
  lines.push('    pub behavior_changed: bool,');
  lines.push('    pub note: &\'static str,');
  lines.push('}');
  lines.push('');
  lines.push('/// Operation name → policy, embedded at generation time.');
  lines.push('pub const EMBEDDED_MANIFEST: &[(&str, OperationPolicy)] = &[');
  for (const op of ir.operations) {
    lines.push(`    ("${op.name}", OperationPolicy { kind: "${op.kind}", deprecated: ${!!op.deprecated}, sunset_at: ${JSON.stringify(op.sunsetAt ?? '')}, behavior_changed: ${!!op.behaviorChanged}, note: ${JSON.stringify(op.note ?? '')} }),`);
  }
  lines.push('];');
  lines.push('');
  lines.push('/// SHA-256 of the platform-manifest.json this SDK was generated from.');
  lines.push(`pub const MANIFEST_HASH: &str = "${ir.manifestHash}";`);
  lines.push('');
  lines.push('/// Manifest protocol version this SDK understands.');
  lines.push(`pub const MANIFEST_PROTOCOL_VERSION: &str = "${ir.protocolVersion}";`);
  return lines.join('\n') + '\n';
}

function renderHydration(ir) {
  const lines = [header(ir)];
  lines.push('/// Lowercase column type name → coercion kind, shared verbatim across');
  lines.push('/// all SDK languages.');
  lines.push('pub const HYDRATION_RULES: &[(&str, &str)] = &[');
  for (const [key, kind] of Object.entries(ir.hydrationRules.rules)) {
    lines.push(`    (${JSON.stringify(key)}, ${JSON.stringify(kind)}),`);
  }
  lines.push('];');
  lines.push('');
  lines.push('/// Fallback coercion kind.');
  lines.push(`pub const HYDRATION_DEFAULT: &str = ${JSON.stringify(ir.hydrationRules.default)};`);
  return lines.join('\n') + '\n';
}

function renderMod(ir) {
  return (
    header(ir) +
    '//! Generated wire core for the whodb-sdk crate. Do not edit.\n\n' +
    'pub mod hydration;\n' +
    'pub mod manifest;\n' +
    'pub mod operations;\n'
  );
}

export function renderRust(ir) {
  return [
    ['mod.rs', renderMod(ir)],
    ['operations.rs', renderOperations(ir)],
    ['manifest.rs', renderManifest(ir)],
    ['hydration.rs', renderHydration(ir)],
  ];
}
