// render/ts.mjs — TypeScript renderer for generate-core.mjs. Emits the
// generated wire core consumed by the handwritten @clidey/whodb-sdk facade.
import { isEnumType, isScalarType, isInputObjectType, isObjectType, isNonNullType, isListType, getNamedType } from 'graphql';

const SCALAR_TS = {
  ID: 'string',
  String: 'string',
  Int: 'number',
  Float: 'number',
  Boolean: 'boolean',
};

function header(ir) {
  return `// GENERATED by sdk/tools/generate-core.mjs — DO NOT EDIT (manifest ${ir.manifestHash.slice(0, 12)})\n`;
}

function tsTypeOf(gqlType) {
  if (isNonNullType(gqlType)) return tsTypeOfInner(gqlType.ofType, false);
  return tsTypeOfInner(gqlType, true);
}

function tsTypeOfInner(gqlType, nullable) {
  let ts;
  if (isListType(gqlType)) {
    ts = `Array<${tsTypeOf(gqlType.ofType)}>`;
  } else {
    const named = getNamedType(gqlType);
    ts = SCALAR_TS[named.name] ?? (isScalarType(named) ? 'unknown' : named.name);
  }
  return nullable ? `${ts} | null` : ts;
}

function renderTypes(ir) {
  const lines = [header(ir)];
  const sorted = [...ir.typeClosure].sort();
  for (const name of sorted) {
    const type = ir.schema.getType(name);
    if (!type) continue;
    if (isEnumType(type)) {
      const values = type.getValues().map(v => `'${v.name}'`).join(' | ');
      lines.push(`export type ${name} = ${values};\n`);
      continue;
    }
    if (isInputObjectType(type) || isObjectType(type)) {
      const fields = Object.values(type.getFields())
        .map(f => {
          const optional = !isNonNullType(f.type) ? '?' : '';
          return `  ${f.name}${optional}: ${tsTypeOf(f.type)};`;
        })
        .join('\n');
      lines.push(`export interface ${name} {\n${fields}\n}\n`);
    }
  }
  return lines.join('\n');
}

function varsTypeName(op) {
  return `${op.name}Vars`;
}

function renderOperations(ir) {
  const lines = [header(ir)];
  lines.push(`import type { Transport } from '../transport.js';`);
  const typeImports = new Set();
  for (const op of ir.operations) {
    for (const arg of op.args) {
      if (!SCALAR_TS[arg.type] && ir.typeClosure.has(arg.type)) typeImports.add(arg.type);
    }
    if (ir.typeClosure.has(op.returnTypeName)) typeImports.add(op.returnTypeName);
  }
  if (typeImports.size > 0) {
    lines.push(`import type { ${[...typeImports].sort().join(', ')} } from './types.js';`);
  }
  lines.push('');

  for (const op of ir.operations) {
    const argFields = op.args
      .map(a => {
        const base = SCALAR_TS[a.type] ?? (ir.typeClosure.has(a.type) ? a.type : 'unknown');
        const ts = a.list ? `Array<${base}>` : base;
        return `  ${a.name}${a.required ? '' : '?'}: ${ts}${a.required ? '' : ' | null'};`;
      })
      .join('\n');
    const returnBase = SCALAR_TS[op.returnTypeName] ?? (ir.typeClosure.has(op.returnTypeName) ? op.returnTypeName : 'unknown');
    const isList = op.returns.startsWith('[');
    const returnTs = isList ? `Array<${returnBase}>` : returnBase;
    const fnName = op.name.charAt(0).toLowerCase() + op.name.slice(1);

    lines.push(`export interface ${varsTypeName(op)} {\n${argFields || ''}\n}`);
    lines.push(`export const ${op.name}Document = ${JSON.stringify(op.document)};`);
    lines.push(
      `/** Generated wire call for ${op.kind} ${op.name}. */\n` +
      `export async function ${fnName}(transport: Transport, vars: ${varsTypeName(op)}): Promise<${returnTs}> {\n` +
      `  const data = await transport.execute('${op.name}', ${op.name}Document, vars as unknown as Record<string, unknown>);\n` +
      `  return (data as Record<string, unknown>)['${op.name}'] as ${returnTs};\n` +
      `}\n`
    );
  }
  return lines.join('\n');
}

function renderManifest(ir) {
  const entries = {};
  for (const op of ir.operations) {
    entries[op.name] = {
      kind: op.kind,
      deprecated: op.deprecated || undefined,
      sunsetAt: op.sunsetAt || undefined,
      behaviorChanged: op.behaviorChanged || undefined,
      note: op.note || undefined,
    };
  }
  return (
    header(ir) +
    `/** Per-operation versioning-policy state embedded at generation time. */\n` +
    `export const embeddedManifest: Record<string, { kind: string; deprecated?: boolean; sunsetAt?: string; behaviorChanged?: boolean; note?: string }> = ${JSON.stringify(entries, null, 2)};\n\n` +
    `/** SHA-256 of the platform-manifest.json this SDK was generated from. */\n` +
    `export const manifestHash = '${ir.manifestHash}';\n\n` +
    `/** Manifest protocol version this SDK understands. */\n` +
    `export const manifestProtocolVersion = '${ir.protocolVersion}';\n`
  );
}

function renderHydration(ir) {
  return (
    header(ir) +
    `/** Column-type → coercion kind rules shared across all SDK languages. */\n` +
    `export const hydrationRules: Record<string, string> = ${JSON.stringify(ir.hydrationRules.rules, null, 2)};\n\n` +
    `export const hydrationDefault = '${ir.hydrationRules.default}';\n`
  );
}

function renderSurface(ir) {
  // The facade consumes this to wire domain handles without hand-maintaining
  // the operation list: domain -> method -> generated op metadata.
  const surface = {};
  for (const op of ir.operations) {
    if (op.internal) continue;
    surface[op.domain] ??= {};
    surface[op.domain][op.method] = {
      operation: op.name,
      autofill: op.autofill,
      rename: op.rename,
      paginated: op.paginated,
    };
  }
  return (
    header(ir) +
    `/** Facade surface mapping generated from sdk/spec/surface.yaml. */\n` +
    `export const surface = ${JSON.stringify(surface, null, 2)} as const;\n`
  );
}

export function renderTypeScript(ir) {
  return [
    ['types.ts', renderTypes(ir)],
    ['operations.ts', renderOperations(ir)],
    ['manifest.ts', renderManifest(ir)],
    ['hydration.ts', renderHydration(ir)],
    ['surface.ts', renderSurface(ir)],
  ];
}
