// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
)

type CloudProvider interface {
	IsCloudProvider()
	GetID() string
	GetProviderType() CloudProviderType
	GetName() string
	GetRegion() string
	GetStatus() CloudProviderStatus
	GetLastDiscoveryAt() *string
	GetDiscoveredCount() int
	GetError() *string
}

type AIChatMessage struct {
	Type                 string      `json:"Type"`
	Result               *RowsResult `json:"Result,omitempty"`
	Text                 string      `json:"Text"`
	RequiresConfirmation bool        `json:"RequiresConfirmation"`
}

type AIProvider struct {
	Type                 string `json:"Type"`
	Name                 string `json:"Name"`
	ProviderID           string `json:"ProviderId"`
	IsEnvironmentDefined bool   `json:"IsEnvironmentDefined"`
	IsGeneric            bool   `json:"IsGeneric"`
}

type AWSProvider struct {
	ID                  string              `json:"Id"`
	ProviderType        CloudProviderType   `json:"ProviderType"`
	Name                string              `json:"Name"`
	Region              string              `json:"Region"`
	Status              CloudProviderStatus `json:"Status"`
	LastDiscoveryAt     *string             `json:"LastDiscoveryAt,omitempty"`
	DiscoveredCount     int                 `json:"DiscoveredCount"`
	Error               *string             `json:"Error,omitempty"`
	ProfileName         *string             `json:"ProfileName,omitempty"`
	DiscoverRds         bool                `json:"DiscoverRDS"`
	DiscoverElastiCache bool                `json:"DiscoverElastiCache"`
	DiscoverDocumentDb  bool                `json:"DiscoverDocumentDB"`
}

func (AWSProvider) IsCloudProvider()                        {}
func (this AWSProvider) GetID() string                      { return this.ID }
func (this AWSProvider) GetProviderType() CloudProviderType { return this.ProviderType }
func (this AWSProvider) GetName() string                    { return this.Name }
func (this AWSProvider) GetRegion() string                  { return this.Region }
func (this AWSProvider) GetStatus() CloudProviderStatus     { return this.Status }
func (this AWSProvider) GetLastDiscoveryAt() *string        { return this.LastDiscoveryAt }
func (this AWSProvider) GetDiscoveredCount() int            { return this.DiscoveredCount }
func (this AWSProvider) GetError() *string                  { return this.Error }

type AWSProviderInput struct {
	Name                string  `json:"Name"`
	Region              string  `json:"Region"`
	ProfileName         *string `json:"ProfileName,omitempty"`
	DiscoverRds         *bool   `json:"DiscoverRDS,omitempty"`
	DiscoverElastiCache *bool   `json:"DiscoverElastiCache,omitempty"`
	DiscoverDocumentDb  *bool   `json:"DiscoverDocumentDB,omitempty"`
}

type AWSRegion struct {
	ID          string `json:"Id"`
	Description string `json:"Description"`
	Partition   string `json:"Partition"`
}

type AtomicWhereCondition struct {
	ColumnType string `json:"ColumnType"`
	Key        string `json:"Key"`
	Operator   string `json:"Operator"`
	Value      string `json:"Value"`
}

type AuthSessionPayload struct {
	SessionToken string `json:"sessionToken"`
	ExpiresAt    string `json:"expiresAt"`
	Type         string `json:"type"`
	Hostname     string `json:"hostname"`
	Port         string `json:"port"`
	Database     string `json:"database"`
	DisplayName  string `json:"displayName"`
}

type Capabilities struct {
	SupportsScratchpad     bool `json:"supportsScratchpad"`
	SupportsChat           bool `json:"supportsChat"`
	SupportsGraph          bool `json:"supportsGraph"`
	SupportsSchema         bool `json:"supportsSchema"`
	SupportsDatabaseSwitch bool `json:"supportsDatabaseSwitch"`
	SupportsModifiers      bool `json:"supportsModifiers"`
}

type ChatInput struct {
	PreviousConversation string  `json:"PreviousConversation"`
	Query                string  `json:"Query"`
	Model                string  `json:"Model"`
	Token                *string `json:"Token,omitempty"`
}

type CollectionImportError struct {
	Index  int    `json:"Index"`
	Reason string `json:"Reason"`
}

type CollectionImportPreview struct {
	Format          CollectionImportFormat `json:"Format"`
	Sheet           *string                `json:"Sheet,omitempty"`
	Sheets          []string               `json:"Sheets"`
	Columns         []string               `json:"Columns"`
	Rows            [][]string             `json:"Rows"`
	Documents       []string               `json:"Documents"`
	Count           *int                   `json:"Count,omitempty"`
	Truncated       bool                   `json:"Truncated"`
	ValidationError *string                `json:"ValidationError,omitempty"`
}

type CollectionImportResult struct {
	Status        bool                     `json:"Status"`
	ImportedCount int                      `json:"ImportedCount"`
	SkippedCount  int                      `json:"SkippedCount"`
	MatchedCount  *int                     `json:"MatchedCount,omitempty"`
	ModifiedCount *int                     `json:"ModifiedCount,omitempty"`
	UpsertedCount *int                     `json:"UpsertedCount,omitempty"`
	Errors        []*CollectionImportError `json:"Errors"`
	Message       *string                  `json:"Message,omitempty"`
	Detail        *string                  `json:"Detail,omitempty"`
}

type Column struct {
	Type             string  `json:"Type"`
	Name             string  `json:"Name"`
	IsPrimary        bool    `json:"IsPrimary"`
	IsForeignKey     bool    `json:"IsForeignKey"`
	ReferencedTable  *string `json:"ReferencedTable,omitempty"`
	ReferencedColumn *string `json:"ReferencedColumn,omitempty"`
	Length           *int    `json:"Length,omitempty"`
	Precision        *int    `json:"Precision,omitempty"`
	Scale            *int    `json:"Scale,omitempty"`
}

type Dashboard struct {
	ID          string             `json:"ID"`
	Name        string             `json:"Name"`
	Description *string            `json:"Description,omitempty"`
	RefreshRule string             `json:"RefreshRule"`
	Widgets     []*DashboardWidget `json:"Widgets"`
	CreatedAt   string             `json:"CreatedAt"`
	UpdatedAt   string             `json:"UpdatedAt"`
}

type DashboardWidget struct {
	ID            string  `json:"ID"`
	Type          string  `json:"Type"`
	Title         string  `json:"Title"`
	Description   *string `json:"Description,omitempty"`
	Layout        string  `json:"Layout"`
	Query         *string `json:"Query,omitempty"`
	QueryContext  *string `json:"QueryContext,omitempty"`
	Visualization *string `json:"Visualization,omitempty"`
	Snapshot      *string `json:"Snapshot,omitempty"`
	SortOrder     int     `json:"SortOrder"`
}

type DatabaseMetadata struct {
	DatabaseType    string            `json:"databaseType"`
	TypeDefinitions []*TypeDefinition `json:"typeDefinitions"`
	Operators       []string          `json:"operators"`
	AliasMap        []*Record         `json:"aliasMap"`
	Capabilities    *Capabilities     `json:"capabilities"`
	SystemSchemas   []string          `json:"systemSchemas"`
}

type DatabaseQuerySuggestion struct {
	Description string `json:"description"`
	Category    string `json:"category"`
}

type DiscoveredConnection struct {
	ID           string            `json:"Id"`
	ProviderType CloudProviderType `json:"ProviderType"`
	ProviderID   string            `json:"ProviderID"`
	Name         string            `json:"Name"`
	DatabaseType string            `json:"DatabaseType"`
	Region       *string           `json:"Region,omitempty"`
	Status       ConnectionStatus  `json:"Status"`
	Metadata     []*Record         `json:"Metadata"`
}

type ExportDownload struct {
	ID          string `json:"ID"`
	Filename    string `json:"Filename"`
	ContentType string `json:"ContentType"`
	DownloadURL string `json:"DownloadURL"`
	Size        int    `json:"Size"`
}

type GenerateChatTitleInput struct {
	Query      string  `json:"Query"`
	ModelType  string  `json:"ModelType"`
	ProviderID *string `json:"ProviderId,omitempty"`
	Token      *string `json:"Token,omitempty"`
	Model      string  `json:"Model"`
	Endpoint   *string `json:"Endpoint,omitempty"`
}

type GenerateChatTitleResponse struct {
	Title string `json:"Title"`
}

type GraphUnit struct {
	Unit      *StorageUnit             `json:"Unit"`
	Relations []*GraphUnitRelationship `json:"Relations"`
}

type GraphUnitRelationship struct {
	Name         string                    `json:"Name"`
	Relationship GraphUnitRelationshipType `json:"Relationship"`
	SourceColumn *string                   `json:"SourceColumn,omitempty"`
	TargetColumn *string                   `json:"TargetColumn,omitempty"`
}

type HealthStatus struct {
	Server   string `json:"Server"`
	Database string `json:"Database"`
}

type ImportCollectionFileInput struct {
	Schema      string                 `json:"Schema"`
	Collection  string                 `json:"Collection"`
	Format      CollectionImportFormat `json:"Format"`
	Mode        ImportMode             `json:"Mode"`
	UpsertKeys  []string               `json:"UpsertKeys,omitempty"`
	SkipColumns []string               `json:"SkipColumns,omitempty"`
	Delimiter   *string                `json:"Delimiter,omitempty"`
	Sheet       *string                `json:"Sheet,omitempty"`
	File        graphql.Upload         `json:"File"`
}

type ImportCollectionPreviewInput struct {
	Format    CollectionImportFormat `json:"Format"`
	Delimiter *string                `json:"Delimiter,omitempty"`
	Sheet     *string                `json:"Sheet,omitempty"`
	File      graphql.Upload         `json:"File"`
}

type ImportColumnMapping struct {
	SourceColumn string  `json:"SourceColumn"`
	TargetColumn *string `json:"TargetColumn,omitempty"`
	Skip         bool    `json:"Skip"`
}

type ImportColumnMappingPreview struct {
	SourceColumn string `json:"SourceColumn"`
	TargetColumn string `json:"TargetColumn"`
}

type ImportExistingTableInput struct {
	Schema             string                 `json:"Schema"`
	StorageUnit        string                 `json:"StorageUnit"`
	Mode               ImportMode             `json:"Mode"`
	Mapping            []*ImportColumnMapping `json:"Mapping"`
	AllowAutoGenerated *bool                  `json:"AllowAutoGenerated,omitempty"`
}

type ImportExistingTablePreviewInput struct {
	Schema           string `json:"Schema"`
	StorageUnit      string `json:"StorageUnit"`
	UseHeaderMapping bool   `json:"UseHeaderMapping"`
}

type ImportFileInput struct {
	TargetMode    ImportTargetMode          `json:"TargetMode"`
	ExistingTable *ImportExistingTableInput `json:"ExistingTable,omitempty"`
	NewTable      *ImportNewTableInput      `json:"NewTable,omitempty"`
	Options       *ImportFileOptions        `json:"Options"`
	File          graphql.Upload            `json:"File"`
}

type ImportFileOptions struct {
	Format    ImportFileFormat `json:"Format"`
	Delimiter *string          `json:"Delimiter,omitempty"`
	Sheet     *string          `json:"Sheet,omitempty"`
}

type ImportNewTableColumnInput struct {
	SourceColumn string  `json:"SourceColumn"`
	TargetColumn *string `json:"TargetColumn,omitempty"`
	Type         *string `json:"Type,omitempty"`
	Nullable     bool    `json:"Nullable"`
	Primary      bool    `json:"Primary"`
	Skip         bool    `json:"Skip"`
}

type ImportNewTableColumnPreview struct {
	SourceColumn string `json:"SourceColumn"`
	TargetColumn string `json:"TargetColumn"`
	Type         string `json:"Type"`
	Nullable     bool   `json:"Nullable"`
	Primary      bool   `json:"Primary"`
	Skip         bool   `json:"Skip"`
}

type ImportNewTableInput struct {
	Schema    string                       `json:"Schema"`
	TableName string                       `json:"TableName"`
	Columns   []*ImportNewTableColumnInput `json:"Columns"`
}

type ImportNewTablePreview struct {
	TableName string                         `json:"TableName"`
	Columns   []*ImportNewTableColumnPreview `json:"Columns"`
	Issues    []*ImportSuggestionIssue       `json:"Issues"`
}

type ImportNewTablePreviewInput struct {
	Schema string `json:"Schema"`
}

type ImportPreview struct {
	Sheet                      *string                       `json:"Sheet,omitempty"`
	Sheets                     []string                      `json:"Sheets"`
	Columns                    []string                      `json:"Columns"`
	Rows                       [][]string                    `json:"Rows"`
	Truncated                  bool                          `json:"Truncated"`
	ValidationError            *string                       `json:"ValidationError,omitempty"`
	Mapping                    []*ImportColumnMappingPreview `json:"Mapping,omitempty"`
	RequiresAllowAutoGenerated bool                          `json:"RequiresAllowAutoGenerated"`
	AutoGeneratedColumns       []string                      `json:"AutoGeneratedColumns"`
	NewTable                   *ImportNewTablePreview        `json:"NewTable,omitempty"`
}

type ImportPreviewInput struct {
	TargetMode    ImportTargetMode                 `json:"TargetMode"`
	ExistingTable *ImportExistingTablePreviewInput `json:"ExistingTable,omitempty"`
	NewTable      *ImportNewTablePreviewInput      `json:"NewTable,omitempty"`
	Options       *ImportFileOptions               `json:"Options"`
	File          graphql.Upload                   `json:"File"`
}

type ImportResult struct {
	Status  bool    `json:"Status"`
	Message string  `json:"Message"`
	Detail  *string `json:"Detail,omitempty"`
}

type ImportSQLInput struct {
	Script   *string         `json:"Script,omitempty"`
	File     *graphql.Upload `json:"File,omitempty"`
	Filename *string         `json:"Filename,omitempty"`
}

type ImportSuggestionIssue struct {
	Key          string  `json:"Key"`
	Field        string  `json:"Field"`
	SourceColumn *string `json:"SourceColumn,omitempty"`
}

type LayoutInput struct {
	WidgetID string `json:"WidgetID"`
	Layout   string `json:"Layout"`
}

type LocalAWSProfile struct {
	Name      string  `json:"Name"`
	Region    *string `json:"Region,omitempty"`
	Source    string  `json:"Source"`
	AuthType  string  `json:"AuthType"`
	IsDefault bool    `json:"IsDefault"`
}

type LoginCredentials struct {
	ID       *string        `json:"Id,omitempty"`
	Type     string         `json:"Type"`
	Hostname string         `json:"Hostname"`
	Username string         `json:"Username"`
	Password string         `json:"Password"`
	Database string         `json:"Database"`
	Advanced []*RecordInput `json:"Advanced,omitempty"`
}

type LoginProfile struct {
	Alias                *string      `json:"Alias,omitempty"`
	ID                   string       `json:"Id"`
	Type                 DatabaseType `json:"Type"`
	Hostname             *string      `json:"Hostname,omitempty"`
	Database             *string      `json:"Database,omitempty"`
	IsEnvironmentDefined bool         `json:"IsEnvironmentDefined"`
	Source               string       `json:"Source"`
	SSLConfigured        bool         `json:"SSLConfigured"`
}

type LoginProfileInput struct {
	ID       string       `json:"Id"`
	Type     DatabaseType `json:"Type"`
	Database *string      `json:"Database,omitempty"`
}

type MockDataDependencyAnalysis struct {
	GenerationOrder []string             `json:"GenerationOrder"`
	Tables          []*MockDataTableInfo `json:"Tables"`
	TotalRows       int                  `json:"TotalRows"`
	Warnings        []string             `json:"Warnings"`
	Error           *string              `json:"Error,omitempty"`
}

type MockDataGenerationInput struct {
	Schema            string `json:"Schema"`
	StorageUnit       string `json:"StorageUnit"`
	RowCount          int    `json:"RowCount"`
	Method            string `json:"Method"`
	OverwriteExisting bool   `json:"OverwriteExisting"`
	FkDensityRatio    *int   `json:"FkDensityRatio,omitempty"`
}

type MockDataGenerationStatus struct {
	AmountGenerated int                    `json:"AmountGenerated"`
	Details         []*MockDataTableDetail `json:"Details,omitempty"`
}

type MockDataTableDetail struct {
	Table            string `json:"Table"`
	RowsGenerated    int    `json:"RowsGenerated"`
	UsedExistingData bool   `json:"UsedExistingData"`
}

type MockDataTableInfo struct {
	Table            string `json:"Table"`
	RowsToGenerate   int    `json:"RowsToGenerate"`
	IsBlocked        bool   `json:"IsBlocked"`
	UsesExistingData bool   `json:"UsesExistingData"`
}

type Mutation struct {
}

type OperationWhereCondition struct {
	Children []*WhereCondition `json:"Children"`
}

type Query struct {
}

type Record struct {
	Key   string `json:"Key"`
	Value string `json:"Value"`
}

type RecordInput struct {
	Key   string         `json:"Key"`
	Value string         `json:"Value"`
	Extra []*RecordInput `json:"Extra,omitempty"`
}

type RowsResult struct {
	Columns       []*Column  `json:"Columns"`
	Rows          [][]string `json:"Rows"`
	DisableUpdate bool       `json:"DisableUpdate"`
	TotalCount    int        `json:"TotalCount"`
}

type SQLDataExportInput struct {
	Schema      string            `json:"Schema"`
	StorageUnit string            `json:"StorageUnit"`
	Mode        SQLDataExportMode `json:"Mode"`
	Where       *WhereCondition   `json:"Where,omitempty"`
	Sort        []*SortCondition  `json:"Sort,omitempty"`
	Limit       *int              `json:"Limit,omitempty"`
}

type SSLStatus struct {
	IsEnabled bool   `json:"IsEnabled"`
	Mode      string `json:"Mode"`
}

type SealosBootstrapInput struct {
	Kubeconfig   string  `json:"kubeconfig"`
	DbType       string  `json:"dbType"`
	ResourceName string  `json:"resourceName"`
	DatabaseName *string `json:"databaseName,omitempty"`
	Host         *string `json:"host,omitempty"`
	Port         *string `json:"port,omitempty"`
	Namespace    *string `json:"namespace,omitempty"`
}

type SettingsConfig struct {
	MetricsEnabled         *bool `json:"MetricsEnabled,omitempty"`
	CloudProvidersEnabled  bool  `json:"CloudProvidersEnabled"`
	DisableCredentialForm  bool  `json:"DisableCredentialForm"`
	StandaloneLoginEnabled bool  `json:"StandaloneLoginEnabled"`
	MaxPageSize            int   `json:"MaxPageSize"`
}

type SettingsConfigInput struct {
	MetricsEnabled *string `json:"MetricsEnabled,omitempty"`
}

type SnapshotInput struct {
	Config     string `json:"Config"`
	Data       string `json:"Data"`
	ExecutedAt string `json:"ExecutedAt"`
}

type SortCondition struct {
	Column    string        `json:"Column"`
	Direction SortDirection `json:"Direction"`
}

type StatusResponse struct {
	Status bool `json:"Status"`
}

type StorageUnit struct {
	Name                        string    `json:"Name"`
	Attributes                  []*Record `json:"Attributes"`
	IsMockDataGenerationAllowed bool      `json:"IsMockDataGenerationAllowed"`
}

type StorageUnitColumns struct {
	StorageUnit string    `json:"StorageUnit"`
	Columns     []*Column `json:"Columns"`
}

type TypeDefinition struct {
	ID               string       `json:"id"`
	Label            string       `json:"label"`
	HasLength        bool         `json:"hasLength"`
	HasPrecision     bool         `json:"hasPrecision"`
	DefaultLength    *int         `json:"defaultLength,omitempty"`
	DefaultPrecision *int         `json:"defaultPrecision,omitempty"`
	Category         TypeCategory `json:"category"`
}

type UpdateInfo struct {
	CurrentVersion  string `json:"currentVersion"`
	LatestVersion   string `json:"latestVersion"`
	UpdateAvailable bool   `json:"updateAvailable"`
	ReleaseURL      string `json:"releaseURL"`
}

type UpdateWidgetInput struct {
	Title         *string `json:"Title,omitempty"`
	Description   *string `json:"Description,omitempty"`
	Layout        *string `json:"Layout,omitempty"`
	Query         *string `json:"Query,omitempty"`
	QueryContext  *string `json:"QueryContext,omitempty"`
	Visualization *string `json:"Visualization,omitempty"`
	Snapshot      *string `json:"Snapshot,omitempty"`
	SortOrder     *int    `json:"SortOrder,omitempty"`
}

type WhereCondition struct {
	Type   WhereConditionType       `json:"Type"`
	Atomic *AtomicWhereCondition    `json:"Atomic,omitempty"`
	And    *OperationWhereCondition `json:"And,omitempty"`
	Or     *OperationWhereCondition `json:"Or,omitempty"`
}

type WidgetInput struct {
	Type          string  `json:"Type"`
	Title         string  `json:"Title"`
	Description   *string `json:"Description,omitempty"`
	Layout        string  `json:"Layout"`
	Query         *string `json:"Query,omitempty"`
	QueryContext  *string `json:"QueryContext,omitempty"`
	Visualization *string `json:"Visualization,omitempty"`
	Snapshot      *string `json:"Snapshot,omitempty"`
	SortOrder     *int    `json:"SortOrder,omitempty"`
}

type CloudProviderStatus string

const (
	CloudProviderStatusConnected    CloudProviderStatus = "Connected"
	CloudProviderStatusDiscovering  CloudProviderStatus = "Discovering"
	CloudProviderStatusError        CloudProviderStatus = "Error"
	CloudProviderStatusDisconnected CloudProviderStatus = "Disconnected"
)

var AllCloudProviderStatus = []CloudProviderStatus{
	CloudProviderStatusConnected,
	CloudProviderStatusDiscovering,
	CloudProviderStatusError,
	CloudProviderStatusDisconnected,
}

func (e CloudProviderStatus) IsValid() bool {
	switch e {
	case CloudProviderStatusConnected, CloudProviderStatusDiscovering, CloudProviderStatusError, CloudProviderStatusDisconnected:
		return true
	}
	return false
}

func (e CloudProviderStatus) String() string {
	return string(e)
}

func (e *CloudProviderStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CloudProviderStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CloudProviderStatus", str)
	}
	return nil
}

func (e CloudProviderStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CloudProviderStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CloudProviderStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CloudProviderType string

const (
	CloudProviderTypeAWS CloudProviderType = "AWS"
)

var AllCloudProviderType = []CloudProviderType{
	CloudProviderTypeAWS,
}

func (e CloudProviderType) IsValid() bool {
	switch e {
	case CloudProviderTypeAWS:
		return true
	}
	return false
}

func (e CloudProviderType) String() string {
	return string(e)
}

func (e *CloudProviderType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CloudProviderType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CloudProviderType", str)
	}
	return nil
}

func (e CloudProviderType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CloudProviderType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CloudProviderType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CollectionImportFormat string

const (
	CollectionImportFormatJSON  CollectionImportFormat = "JSON"
	CollectionImportFormatCSV   CollectionImportFormat = "CSV"
	CollectionImportFormatExcel CollectionImportFormat = "EXCEL"
)

var AllCollectionImportFormat = []CollectionImportFormat{
	CollectionImportFormatJSON,
	CollectionImportFormatCSV,
	CollectionImportFormatExcel,
}

func (e CollectionImportFormat) IsValid() bool {
	switch e {
	case CollectionImportFormatJSON, CollectionImportFormatCSV, CollectionImportFormatExcel:
		return true
	}
	return false
}

func (e CollectionImportFormat) String() string {
	return string(e)
}

func (e *CollectionImportFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CollectionImportFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CollectionImportFormat", str)
	}
	return nil
}

func (e CollectionImportFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CollectionImportFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CollectionImportFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ConnectionStatus string

const (
	ConnectionStatusAvailable ConnectionStatus = "Available"
	ConnectionStatusStarting  ConnectionStatus = "Starting"
	ConnectionStatusStopped   ConnectionStatus = "Stopped"
	ConnectionStatusDeleting  ConnectionStatus = "Deleting"
	ConnectionStatusFailed    ConnectionStatus = "Failed"
	ConnectionStatusUnknown   ConnectionStatus = "Unknown"
)

var AllConnectionStatus = []ConnectionStatus{
	ConnectionStatusAvailable,
	ConnectionStatusStarting,
	ConnectionStatusStopped,
	ConnectionStatusDeleting,
	ConnectionStatusFailed,
	ConnectionStatusUnknown,
}

func (e ConnectionStatus) IsValid() bool {
	switch e {
	case ConnectionStatusAvailable, ConnectionStatusStarting, ConnectionStatusStopped, ConnectionStatusDeleting, ConnectionStatusFailed, ConnectionStatusUnknown:
		return true
	}
	return false
}

func (e ConnectionStatus) String() string {
	return string(e)
}

func (e *ConnectionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectionStatus", str)
	}
	return nil
}

func (e ConnectionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DatabaseType string

const (
	DatabaseTypePostgres      DatabaseType = "Postgres"
	DatabaseTypeMySQL         DatabaseType = "MySQL"
	DatabaseTypeSqlite3       DatabaseType = "Sqlite3"
	DatabaseTypeMongoDb       DatabaseType = "MongoDB"
	DatabaseTypeRedis         DatabaseType = "Redis"
	DatabaseTypeElasticSearch DatabaseType = "ElasticSearch"
	DatabaseTypeMariaDb       DatabaseType = "MariaDB"
	DatabaseTypeClickHouse    DatabaseType = "ClickHouse"
)

var AllDatabaseType = []DatabaseType{
	DatabaseTypePostgres,
	DatabaseTypeMySQL,
	DatabaseTypeSqlite3,
	DatabaseTypeMongoDb,
	DatabaseTypeRedis,
	DatabaseTypeElasticSearch,
	DatabaseTypeMariaDb,
	DatabaseTypeClickHouse,
}

func (e DatabaseType) IsValid() bool {
	switch e {
	case DatabaseTypePostgres, DatabaseTypeMySQL, DatabaseTypeSqlite3, DatabaseTypeMongoDb, DatabaseTypeRedis, DatabaseTypeElasticSearch, DatabaseTypeMariaDb, DatabaseTypeClickHouse:
		return true
	}
	return false
}

func (e DatabaseType) String() string {
	return string(e)
}

func (e *DatabaseType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DatabaseType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DatabaseType", str)
	}
	return nil
}

func (e DatabaseType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DatabaseType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DatabaseType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GraphUnitRelationshipType string

const (
	GraphUnitRelationshipTypeOneToOne   GraphUnitRelationshipType = "OneToOne"
	GraphUnitRelationshipTypeOneToMany  GraphUnitRelationshipType = "OneToMany"
	GraphUnitRelationshipTypeManyToOne  GraphUnitRelationshipType = "ManyToOne"
	GraphUnitRelationshipTypeManyToMany GraphUnitRelationshipType = "ManyToMany"
	GraphUnitRelationshipTypeUnknown    GraphUnitRelationshipType = "Unknown"
)

var AllGraphUnitRelationshipType = []GraphUnitRelationshipType{
	GraphUnitRelationshipTypeOneToOne,
	GraphUnitRelationshipTypeOneToMany,
	GraphUnitRelationshipTypeManyToOne,
	GraphUnitRelationshipTypeManyToMany,
	GraphUnitRelationshipTypeUnknown,
}

func (e GraphUnitRelationshipType) IsValid() bool {
	switch e {
	case GraphUnitRelationshipTypeOneToOne, GraphUnitRelationshipTypeOneToMany, GraphUnitRelationshipTypeManyToOne, GraphUnitRelationshipTypeManyToMany, GraphUnitRelationshipTypeUnknown:
		return true
	}
	return false
}

func (e GraphUnitRelationshipType) String() string {
	return string(e)
}

func (e *GraphUnitRelationshipType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GraphUnitRelationshipType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GraphUnitRelationshipType", str)
	}
	return nil
}

func (e GraphUnitRelationshipType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GraphUnitRelationshipType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GraphUnitRelationshipType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ImportFileFormat string

const (
	ImportFileFormatCSV   ImportFileFormat = "CSV"
	ImportFileFormatExcel ImportFileFormat = "EXCEL"
)

var AllImportFileFormat = []ImportFileFormat{
	ImportFileFormatCSV,
	ImportFileFormatExcel,
}

func (e ImportFileFormat) IsValid() bool {
	switch e {
	case ImportFileFormatCSV, ImportFileFormatExcel:
		return true
	}
	return false
}

func (e ImportFileFormat) String() string {
	return string(e)
}

func (e *ImportFileFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ImportFileFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ImportFileFormat", str)
	}
	return nil
}

func (e ImportFileFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ImportFileFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ImportFileFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ImportMode string

const (
	ImportModeAppend    ImportMode = "APPEND"
	ImportModeOverwrite ImportMode = "OVERWRITE"
	ImportModeUpsert    ImportMode = "UPSERT"
)

var AllImportMode = []ImportMode{
	ImportModeAppend,
	ImportModeOverwrite,
	ImportModeUpsert,
}

func (e ImportMode) IsValid() bool {
	switch e {
	case ImportModeAppend, ImportModeOverwrite, ImportModeUpsert:
		return true
	}
	return false
}

func (e ImportMode) String() string {
	return string(e)
}

func (e *ImportMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ImportMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ImportMode", str)
	}
	return nil
}

func (e ImportMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ImportMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ImportMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ImportTargetMode string

const (
	ImportTargetModeExistingTable ImportTargetMode = "EXISTING_TABLE"
	ImportTargetModeNewTable      ImportTargetMode = "NEW_TABLE"
)

var AllImportTargetMode = []ImportTargetMode{
	ImportTargetModeExistingTable,
	ImportTargetModeNewTable,
}

func (e ImportTargetMode) IsValid() bool {
	switch e {
	case ImportTargetModeExistingTable, ImportTargetModeNewTable:
		return true
	}
	return false
}

func (e ImportTargetMode) String() string {
	return string(e)
}

func (e *ImportTargetMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ImportTargetMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ImportTargetMode", str)
	}
	return nil
}

func (e ImportTargetMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ImportTargetMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ImportTargetMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SQLDataExportMode string

const (
	SQLDataExportModeInsert SQLDataExportMode = "INSERT"
	SQLDataExportModeUpdate SQLDataExportMode = "UPDATE"
)

var AllSQLDataExportMode = []SQLDataExportMode{
	SQLDataExportModeInsert,
	SQLDataExportModeUpdate,
}

func (e SQLDataExportMode) IsValid() bool {
	switch e {
	case SQLDataExportModeInsert, SQLDataExportModeUpdate:
		return true
	}
	return false
}

func (e SQLDataExportMode) String() string {
	return string(e)
}

func (e *SQLDataExportMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SQLDataExportMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SQLDataExportMode", str)
	}
	return nil
}

func (e SQLDataExportMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SQLDataExportMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SQLDataExportMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TypeCategory string

const (
	TypeCategoryNumeric  TypeCategory = "numeric"
	TypeCategoryText     TypeCategory = "text"
	TypeCategoryBinary   TypeCategory = "binary"
	TypeCategoryDatetime TypeCategory = "datetime"
	TypeCategoryBoolean  TypeCategory = "boolean"
	TypeCategoryJSON     TypeCategory = "json"
	TypeCategoryOther    TypeCategory = "other"
)

var AllTypeCategory = []TypeCategory{
	TypeCategoryNumeric,
	TypeCategoryText,
	TypeCategoryBinary,
	TypeCategoryDatetime,
	TypeCategoryBoolean,
	TypeCategoryJSON,
	TypeCategoryOther,
}

func (e TypeCategory) IsValid() bool {
	switch e {
	case TypeCategoryNumeric, TypeCategoryText, TypeCategoryBinary, TypeCategoryDatetime, TypeCategoryBoolean, TypeCategoryJSON, TypeCategoryOther:
		return true
	}
	return false
}

func (e TypeCategory) String() string {
	return string(e)
}

func (e *TypeCategory) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TypeCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TypeCategory", str)
	}
	return nil
}

func (e TypeCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TypeCategory) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TypeCategory) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WhereConditionType string

const (
	WhereConditionTypeAtomic WhereConditionType = "Atomic"
	WhereConditionTypeAnd    WhereConditionType = "And"
	WhereConditionTypeOr     WhereConditionType = "Or"
)

var AllWhereConditionType = []WhereConditionType{
	WhereConditionTypeAtomic,
	WhereConditionTypeAnd,
	WhereConditionTypeOr,
}

func (e WhereConditionType) IsValid() bool {
	switch e {
	case WhereConditionTypeAtomic, WhereConditionTypeAnd, WhereConditionTypeOr:
		return true
	}
	return false
}

func (e WhereConditionType) String() string {
	return string(e)
}

func (e *WhereConditionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WhereConditionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WhereConditionType", str)
	}
	return nil
}

func (e WhereConditionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WhereConditionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WhereConditionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
