// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Column struct {
	Type string `json:"Type"`
	Name string `json:"Name"`
}

type LoginCredentials struct {
	Type     string `json:"Type"`
	Hostname string `json:"Hostname"`
	Username string `json:"Username"`
	Password string `json:"Password"`
	Database string `json:"Database"`
}

type LoginResponse struct {
	Status bool `json:"Status"`
}

type Mutation struct {
}

type Query struct {
}

type Record struct {
	Key   string `json:"Key"`
	Value string `json:"Value"`
}

type RowsResult struct {
	Columns []*Column  `json:"Columns"`
	Rows    [][]string `json:"Rows"`
}

type StorageUnit struct {
	Name       string    `json:"Name"`
	Attributes []*Record `json:"Attributes"`
}

type DatabaseType string

const (
	DatabaseTypePostgres DatabaseType = "Postgres"
)

var AllDatabaseType = []DatabaseType{
	DatabaseTypePostgres,
}

func (e DatabaseType) IsValid() bool {
	switch e {
	case DatabaseTypePostgres:
		return true
	}
	return false
}

func (e DatabaseType) String() string {
	return string(e)
}

func (e *DatabaseType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DatabaseType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DatabaseType", str)
	}
	return nil
}

func (e DatabaseType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
