import { forwardRef, type SVGProps } from 'react';

const iconUrls = import.meta.glob<string>('../assets/whodb-icons/*.svg', {
    eager: true,
    query: '?url',
    import: 'default',
});

function glyph(name: string) {
    const url = iconUrls[`../assets/whodb-icons/${name}.svg`];
    if (!url) throw new Error(`Missing WhoDB icon: ${name}`);
    return forwardRef<SVGSVGElement, SVGProps<SVGSVGElement>>(({ style, ...props }, ref) =>
        <svg ref={ref} viewBox="0 0 24 24" aria-hidden="true" {...props} style={{
            mask: `url("${url}") center / contain no-repeat`,
            WebkitMask: `url("${url}") center / contain no-repeat`,
            ...style,
        }}><rect width="24" height="24" fill="currentColor" /></svg>,
    );
}

/** WhoDB AdjustmentsHorizontalIcon icon. */
export const AdjustmentsHorizontalIcon = glyph('sliders');
/** WhoDB AdjustmentsVerticalIcon icon. */
export const AdjustmentsVerticalIcon = glyph('sliders-v');
/** WhoDB ArrowDownCircleIcon icon. */
export const ArrowDownCircleIcon = glyph('arrow-down-circle');
/** WhoDB ArrowDownTrayIcon icon. */
export const ArrowDownTrayIcon = glyph('download');
/** WhoDB ArrowLeftStartOnRectangleIcon icon. */
export const ArrowLeftStartOnRectangleIcon = glyph('signout');
/** WhoDB ArrowPathIcon icon. */
export const ArrowPathIcon = glyph('refresh');
/** WhoDB ArrowPathRoundedSquareIcon icon. */
export const ArrowPathRoundedSquareIcon = glyph('refresh');
/** WhoDB ArrowRightCircleIcon icon. */
export const ArrowRightCircleIcon = glyph('arrow-right-circle');
/** WhoDB ArrowRightIcon icon. */
export const ArrowRightIcon = glyph('arrow-right');
/** WhoDB ArrowTopRightOnSquareIcon icon. */
export const ArrowTopRightOnSquareIcon = glyph('external');
/** WhoDB ArrowUpCircleIcon icon. */
export const ArrowUpCircleIcon = glyph('arrow-up-circle');
/** WhoDB ArrowUpIcon icon. */
export const ArrowUpIcon = glyph('upload');
/** WhoDB ArrowUturnLeftIcon icon. */
export const ArrowUturnLeftIcon = glyph('undo');
/** WhoDB ArrowUturnRightIcon icon. */
export const ArrowUturnRightIcon = glyph('redo');
/** WhoDB BanknotesIcon icon. */
export const BanknotesIcon = glyph('banknotes');
/** WhoDB Bars3Icon icon. */
export const Bars3Icon = glyph('menu');
/** WhoDB BarsArrowUpIcon icon. */
export const BarsArrowUpIcon = glyph('sort-up');
/** WhoDB BeakerIcon icon. */
export const BeakerIcon = glyph('beaker');
/** WhoDB BellAlertIcon icon. */
export const BellAlertIcon = glyph('bell');
/** WhoDB BookOpenIcon icon. */
export const BookOpenIcon = glyph('book');
/** WhoDB BriefcaseIcon icon. */
export const BriefcaseIcon = glyph('project');
/** WhoDB BuildingOffice2Icon icon. */
export const BuildingOffice2Icon = glyph('organization');
/** WhoDB BuildingStorefrontIcon icon. */
export const BuildingStorefrontIcon = glyph('store');
/** WhoDB CalculatorIcon icon. */
export const CalculatorIcon = glyph('calculator');
/** WhoDB CalendarIcon icon. */
export const CalendarIcon = glyph('calendar');
/** WhoDB ChartBarIcon icon. */
export const ChartBarIcon = glyph('chart');
/** WhoDB ChatBubbleLeftRightIcon icon. */
export const ChatBubbleLeftRightIcon = glyph('chat');
/** WhoDB CheckCircleIcon icon. */
export const CheckCircleIcon = glyph('check-circle');
/** WhoDB ChevronDownIcon icon. */
export const ChevronDownIcon = glyph('chevron-down');
/** WhoDB ChevronLeftIcon icon. */
export const ChevronLeftIcon = glyph('chevron-left');
/** WhoDB ChevronRightIcon icon. */
export const ChevronRightIcon = glyph('chevron-right');
/** WhoDB ChevronUpDownIcon icon. */
export const ChevronUpDownIcon = glyph('up-down');
/** WhoDB ChevronUpIcon icon. */
export const ChevronUpIcon = glyph('chevron-up');
/** WhoDB CircleStackIcon icon. */
export const CircleStackIcon = glyph('source');
/** WhoDB ClipboardDocumentIcon icon. */
export const ClipboardDocumentIcon = glyph('clipboard-doc');
/** WhoDB ClipboardIcon icon. */
export const ClipboardIcon = glyph('clipboard');
/** WhoDB ClockIcon icon. */
export const ClockIcon = glyph('clock');
/** WhoDB CloudIcon icon. */
export const CloudIcon = glyph('cloud');
/** WhoDB CodeBracketIcon icon. */
export const CodeBracketIcon = glyph('code');
/** WhoDB Cog6ToothIcon icon. */
export const Cog6ToothIcon = glyph('settings');
/** WhoDB CogIcon icon. */
export const CogIcon = glyph('settings');
/** WhoDB CommandLineIcon icon. */
export const CommandLineIcon = glyph('terminal');
/** WhoDB CreditCardIcon icon. */
export const CreditCardIcon = glyph('card');
/** WhoDB CubeIcon icon. */
export const CubeIcon = glyph('packages');
/** WhoDB CursorArrowRaysIcon icon. */
export const CursorArrowRaysIcon = glyph('cursor');
/** WhoDB DevicePhoneMobileIcon icon. */
export const DevicePhoneMobileIcon = glyph('mobile');
/** WhoDB DocumentDuplicateIcon icon. */
export const DocumentDuplicateIcon = glyph('copy');
/** WhoDB DocumentIcon icon. */
export const DocumentIcon = glyph('file');
/** WhoDB DocumentTextIcon icon. */
export const DocumentTextIcon = glyph('file-text');
/** WhoDB EllipsisHorizontalIcon icon. */
export const EllipsisHorizontalIcon = glyph('more');
/** WhoDB EllipsisVerticalIcon icon. */
export const EllipsisVerticalIcon = glyph('more-v');
/** WhoDB EnvelopeIcon icon. */
export const EnvelopeIcon = glyph('mail');
/** WhoDB ExclamationCircleIcon icon. */
export const ExclamationCircleIcon = glyph('alert-circle');
/** WhoDB ExclamationTriangleIcon icon. */
export const ExclamationTriangleIcon = glyph('warning');
/** WhoDB EyeIcon icon. */
export const EyeIcon = glyph('eye');
/** WhoDB EyeSlashIcon icon. */
export const EyeSlashIcon = glyph('eye-off');
/** WhoDB FolderIcon icon. */
export const FolderIcon = glyph('folder');
/** WhoDB GlobeAltIcon icon. */
export const GlobeAltIcon = glyph('globe');
/** WhoDB HashtagIcon icon. */
export const HashtagIcon = glyph('hash');
/** WhoDB HomeIcon icon. */
export const HomeIcon = glyph('home');
/** WhoDB InformationCircleIcon icon. */
export const InformationCircleIcon = glyph('info');
/** WhoDB KeyIcon icon. */
export const KeyIcon = glyph('secret');
/** WhoDB LinkIcon icon. */
export const LinkIcon = glyph('link');
/** WhoDB ListBulletIcon icon. */
export const ListBulletIcon = glyph('list');
/** WhoDB LockClosedIcon icon. */
export const LockClosedIcon = glyph('lock');
/** WhoDB MagnifyingGlassIcon icon. */
export const MagnifyingGlassIcon = glyph('search');
/** WhoDB PaperClipIcon icon. */
export const PaperClipIcon = glyph('paperclip');
/** WhoDB PencilIcon icon. */
export const PencilIcon = glyph('edit');
/** WhoDB PencilSquareIcon icon. */
export const PencilSquareIcon = glyph('edit');
/** WhoDB PlayIcon icon. */
export const PlayIcon = glyph('play');
/** WhoDB PlusCircleIcon icon. */
export const PlusCircleIcon = glyph('plus-circle');
/** WhoDB PlusIcon icon. */
export const PlusIcon = glyph('plus');
/** WhoDB PresentationChartBarIcon icon. */
export const PresentationChartBarIcon = glyph('present-bar');
/** WhoDB PresentationChartLineIcon icon. */
export const PresentationChartLineIcon = glyph('present-line');
/** WhoDB QuestionMarkCircleIcon icon. */
export const QuestionMarkCircleIcon = glyph('help');
/** WhoDB RectangleGroupIcon icon. */
export const RectangleGroupIcon = glyph('app');
/** WhoDB ShareIcon icon. */
export const ShareIcon = glyph('share');
/** WhoDB ShieldCheckIcon icon. */
export const ShieldCheckIcon = glyph('shield');
/** WhoDB ShoppingBagIcon icon. */
export const ShoppingBagIcon = glyph('bag');
/** WhoDB SignalSlashIcon icon. */
export const SignalSlashIcon = glyph('offline');
/** WhoDB SparklesIcon icon. */
export const SparklesIcon = glyph('ai');
/** WhoDB Squares2X2Icon icon. */
export const Squares2X2Icon = glyph('grid');
/** WhoDB StarIcon icon. */
export const StarIcon = glyph('star');
/** WhoDB TableCellsIcon icon. */
export const TableCellsIcon = glyph('table');
/** WhoDB TrashIcon icon. */
export const TrashIcon = glyph('trash');
/** WhoDB UserGroupIcon icon. */
export const UserGroupIcon = glyph('team');
/** WhoDB UserIcon icon. */
export const UserIcon = glyph('account');
/** WhoDB UsersIcon icon. */
export const UsersIcon = glyph('users');
/** WhoDB XCircleIcon icon. */
export const XCircleIcon = glyph('x-circle');
/** WhoDB XMarkIcon icon. */
export const XMarkIcon = glyph('close');

/** WhoDB Check icon. */
export const Check = glyph('check');
/** WhoDB CheckIcon icon. */
export const CheckIcon = Check;
/** WhoDB ChevronRight icon. */
export const ChevronRight = ChevronRightIcon;
/** WhoDB ChevronsUpDown icon. */
export const ChevronsUpDown = glyph('up-down');
/** WhoDB ChevronsUpDownIcon icon. */
export const ChevronsUpDownIcon = ChevronsUpDown;
/** WhoDB CircleIcon icon. */
export const CircleIcon = glyph('circle');
/** WhoDB Copy icon. */
export const Copy = glyph('copy');
/** WhoDB Ellipsis icon. */
export const Ellipsis = EllipsisHorizontalIcon;
/** WhoDB EllipsisIcon icon. */
export const EllipsisIcon = EllipsisHorizontalIcon;
/** WhoDB Eye icon. */
export const Eye = EyeIcon;
/** WhoDB EyeOff icon. */
export const EyeOff = EyeSlashIcon;
/** WhoDB GripVerticalIcon icon. */
export const GripVerticalIcon = glyph('grip-vertical');
/** WhoDB Monitor icon. */
export const Monitor = glyph('monitor');
/** WhoDB Moon icon. */
export const Moon = glyph('moon');
/** WhoDB PanelLeftIcon icon. */
export const PanelLeftIcon = glyph('sidebar');
/** WhoDB Search icon. */
export const Search = MagnifyingGlassIcon;
/** WhoDB SearchIcon icon. */
export const SearchIcon = MagnifyingGlassIcon;
/** WhoDB Sun icon. */
export const Sun = glyph('sun');
/** WhoDB XIcon icon. */
export const XIcon = XMarkIcon;
