# Copyright 2025 Clidey, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Docker Compose configuration specifically designed for screenshot generation
# This setup is optimized for visual testing and documentation purposes

services:
  screenshot_postgres:
    image: postgres
    container_name: screenshot_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: jio53$*(@nfe)
      PGDATA: /data/postgres
      POSTGRES_DB: test_db
    volumes:
      - screenshot_postgres:/data/postgres
      - ./sample-data/postgres/data.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  db:
    driver: bridge

volumes:
  screenshot_postgres:
