/*
 * Copyright 2026 Clidey, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package mockdata

import (
	"fmt"
	"strings"

	"github.com/clidey/whodb/core/src/engine"
	"github.com/clidey/whodb/core/src/log"
)

// loadExistingPKs loads primary key values from an existing table.
// Supports composite PKs by storing maps of column->value.
func (g *Generator) loadExistingPKs(
	plugin engine.PluginFunctions,
	config *engine.PluginConfig,
	schema, table string,
) error {
	log.WithField("table", table).Debug("Loading existing PKs from table")

	// Get columns to find all PK columns
	columns, err := plugin.GetColumnsForTable(config, schema, table)
	if err != nil {
		return err
	}

	// Collect all PK column names
	var pkColNames []string
	for _, col := range columns {
		if col.IsPrimary {
			pkColNames = append(pkColNames, col.Name)
		}
	}

	if len(pkColNames) == 0 {
		// No PK found, try to use first column
		if len(columns) > 0 {
			pkColNames = []string{columns[0].Name}
			log.WithFields(map[string]any{
				"table":  table,
				"column": columns[0].Name,
			}).Debug("No PK column found, using first column")
		} else {
			return fmt.Errorf("table %s has no columns", table)
		}
	} else {
		log.WithFields(map[string]any{
			"table":     table,
			"pkColumns": pkColNames,
		}).Debug("Found PK columns")
	}

	// Get existing rows
	rows, err := plugin.GetRows(config, &engine.GetRowsRequest{Schema: schema, StorageUnit: table, PageSize: 50})
	if err != nil {
		return err
	}

	// Build column name -> index map
	colIdxMap := make(map[string]int)
	for i, col := range rows.Columns {
		colIdxMap[col.Name] = i
	}

	// Extract PK values for each row
	pks := make([]map[string]any, 0, len(rows.Rows))
	for _, row := range rows.Rows {
		pkRow := make(map[string]any)
		for _, pkColName := range pkColNames {
			if idx, exists := colIdxMap[pkColName]; exists && idx < len(row) {
				pkRow[pkColName] = row[idx]
			}
		}
		if len(pkRow) > 0 {
			pks = append(pks, pkRow)
		}
	}

	g.existingPKs[table] = pks
	log.WithFields(map[string]any{
		"table":     table,
		"pkCount":   len(pks),
		"pkColumns": pkColNames,
	}).Debug("Loaded existing PKs")

	return nil
}

// getPKRowsForTable returns available PK rows for a table.
// Each row is a map of column name -> value to support composite PKs.
func (g *Generator) getPKRowsForTable(table string) []map[string]any {
	// Check generated PKs first
	if pks, ok := g.generatedPKs[table]; ok && len(pks) > 0 {
		return pks
	}
	// Fall back to existing PKs
	if pks, ok := g.existingPKs[table]; ok && len(pks) > 0 {
		return pks
	}
	return nil
}

// trackAutoGeneratedPK stores an auto-generated PK value from the database.
// Used when the PK is auto-increment and the database generates the value.
func (g *Generator) trackAutoGeneratedPK(table string, pkColumnName string, generatedID int64) {
	pkRow := map[string]any{
		pkColumnName: generatedID,
	}
	g.generatedPKs[table] = append(g.generatedPKs[table], pkRow)
	log.WithFields(map[string]any{
		"table":     table,
		"pkColumn":  pkColumnName,
		"pkValue":   generatedID,
		"totalRows": len(g.generatedPKs[table]),
	}).Debug("Tracked auto-generated PK")
}

// trackGeneratedPK stores all PK column values from a generated row.
// Supports composite PKs by storing a map of column->value.
func (g *Generator) trackGeneratedPK(table string, columns []engine.Column, row []engine.Record) {
	// Build a map of record key -> value for quick lookup
	rowValues := make(map[string]string)
	for _, rec := range row {
		rowValues[rec.Key] = rec.Value
	}

	// Collect all PK column values
	pkRow := make(map[string]any)
	for _, col := range columns {
		if col.IsPrimary {
			if val, exists := rowValues[col.Name]; exists {
				pkRow[col.Name] = val
			}
		}
	}

	if len(pkRow) > 0 {
		g.generatedPKs[table] = append(g.generatedPKs[table], pkRow)
		log.WithFields(map[string]any{
			"table":     table,
			"pkColumns": pkRow,
			"totalRows": len(g.generatedPKs[table]),
		}).Debug("Tracked generated PK row")
	}
}

// pkValueKey creates a string key for a PK value to use in the usedPKValues set.
// For composite PKs, concatenates all column values with a separator.
func pkValueKey(pkColumns []engine.Column, row []engine.Record) string {
	// Build a map of record key -> value for quick lookup
	rowValues := make(map[string]string)
	for _, rec := range row {
		rowValues[rec.Key] = rec.Value
	}

	// Concatenate PK column values
	var parts []string
	for _, col := range pkColumns {
		if col.IsPrimary && !col.IsAutoIncrement {
			if val, exists := rowValues[col.Name]; exists {
				parts = append(parts, fmt.Sprintf("%s=%s", col.Name, val))
			}
		}
	}
	return strings.Join(parts, "|")
}

// loadExistingPKsForUniqueness loads existing PK values from a table into the usedPKValues set.
// This prevents generating PK values that already exist in the database.
func (g *Generator) loadExistingPKsForUniqueness(
	plugin engine.PluginFunctions,
	config *engine.PluginConfig,
	schema, table string,
	columns []engine.Column,
) error {
	// Find non-auto-increment PK columns
	var pkColumns []engine.Column
	for _, col := range columns {
		if col.IsPrimary && !col.IsAutoIncrement {
			pkColumns = append(pkColumns, col)
		}
	}

	// No non-auto-increment PKs to check
	if len(pkColumns) == 0 {
		return nil
	}

	log.WithFields(map[string]any{
		"table":     table,
		"pkColumns": len(pkColumns),
	}).Debug("Loading existing PK values for uniqueness check")

	// Initialize the used PK set for this table
	if g.usedPKValues[table] == nil {
		g.usedPKValues[table] = make(map[string]bool)
	}

	// Get existing rows (limit to avoid memory issues)
	rows, err := plugin.GetRows(config, &engine.GetRowsRequest{Schema: schema, StorageUnit: table, PageSize: MaxExistingPKsToLoad})
	if err != nil {
		return fmt.Errorf("failed to load existing rows for PK uniqueness check: %w", err)
	}

	// Build column name -> index map
	colIdxMap := make(map[string]int)
	for i, col := range rows.Columns {
		colIdxMap[col.Name] = i
	}

	// Extract and store PK values
	for _, row := range rows.Rows {
		// Build a pseudo-record for pkValueKey
		records := make([]engine.Record, 0, len(pkColumns))
		for _, pkCol := range pkColumns {
			if idx, exists := colIdxMap[pkCol.Name]; exists && idx < len(row) {
				records = append(records, engine.Record{Key: pkCol.Name, Value: row[idx]})
			}
		}
		if len(records) > 0 {
			key := pkValueKey(pkColumns, records)
			g.usedPKValues[table][key] = true
		}
	}

	log.WithFields(map[string]any{
		"table":          table,
		"existingPKs":    len(g.usedPKValues[table]),
		"totalRowsFound": len(rows.Rows),
	}).Debug("Loaded existing PK values")

	return nil
}

// isPKValueUsed checks if a PK value combination is already used.
func (g *Generator) isPKValueUsed(table string, columns []engine.Column, row []engine.Record) bool {
	if g.usedPKValues[table] == nil {
		return false
	}
	key := pkValueKey(columns, row)
	if key == "" {
		return false // No non-auto-increment PKs
	}
	return g.usedPKValues[table][key]
}

// markPKValueUsed marks a PK value combination as used.
func (g *Generator) markPKValueUsed(table string, columns []engine.Column, row []engine.Record) {
	if g.usedPKValues[table] == nil {
		g.usedPKValues[table] = make(map[string]bool)
	}
	key := pkValueKey(columns, row)
	if key != "" {
		g.usedPKValues[table][key] = true
	}
}
