import { createContext, use, useCallback, useEffect, useMemo, useRef, useState, type ChangeEvent, type ReactNode } from 'react'
import { AlertTriangle, CheckCircle, Database, FileCode, FileSpreadsheet, Loader2, Upload } from 'lucide-react'
import { Dialog, DialogClose, DialogContent, DialogFooter } from '@/components/ui/dialog'
import { Button } from '@/components/ui/Button'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/Input'
import { Textarea } from '@/components/ui/Textarea'
import { ModalForm, useModalForm } from '@/components/ui/ModalForm'
import { useI18n } from '@/i18n/useI18n'
import { cn } from '@/lib/utils'
import { useConnectionStore } from '@/stores/useConnectionStore'
import { resolveSchemaParam } from '@/utils/database-features'
import { getColumnTypeOptions, getDefaultTextColumnType, type ColumnTypeOption } from '@/utils/database-types'
import {
  buildImportSqlInput,
  buildImportTableFileInput,
  buildTableFileOptions,
  getTableFileFormat,
  hasSqlScriptSource,
  isAcceptedSqlFile,
  type SqlScriptSource,
  type TableFileSource,
} from './sql-import-utils'
import {
  ImportFileFormat,
  ImportMode,
  ImportTargetMode,
  useGetDatabaseMetadataQuery,
  useImportPreviewMutation,
  useImportSqlMutation,
  useImportTableFileMutation,
  type ImportColumnMapping,
  type ImportNewTableColumnInput,
  type ImportPreviewMutation,
} from '@graphql'

type ImportMethod = 'sql' | 'tableFile'
type SourceKind = 'file' | 'text'
type TableTargetMode = 'existing' | 'new'
type TableImportPreview = ImportPreviewMutation['ImportPreview']

interface DatabaseImportContextValue {
  method: ImportMethod
  sourceKind: SourceKind
  tableTargetMode: TableTargetMode
  source: SqlScriptSource | null
  tableSource: TableFileSource | null
  tablePreview: TableImportPreview | null
  targetDatabase: string
  databaseOptions: string[]
  tableName?: string | null
  targetTableLabel: string
  tableImportMode: ImportMode
  csvDelimiter: string
  excelSheet: string
  useHeaderMapping: boolean
  allowAutoGenerated: boolean
  newTableName: string
  newTableColumns: ImportNewTableColumnInput[]
  typeOptions: ColumnTypeOption[]
  metadataLoading: boolean
  metadataFailed: boolean
  newTableValidationError: string | null
  previewLoading: boolean
  result: ImportResultState | null
  sqlFileInputRef: React.RefObject<HTMLInputElement | null>
  tableFileInputRef: React.RefObject<HTMLInputElement | null>
  setMethod: (method: ImportMethod) => void
  setSourceKind: (kind: SourceKind) => void
  setTableTargetMode: (mode: TableTargetMode) => void
  setTargetDatabase: (database: string) => void
  setTableImportMode: (mode: ImportMode) => void
  setCsvDelimiter: (delimiter: string) => void
  setExcelSheet: (sheet: string) => void
  setUseHeaderMapping: (useHeaderMapping: boolean) => void
  setAllowAutoGenerated: (allowAutoGenerated: boolean) => void
  setNewTableName: (name: string) => void
  updateNewTableColumn: (index: number, field: keyof ImportNewTableColumnInput, value: string | boolean) => void
  handleFileChange: (event: ChangeEvent<HTMLInputElement>) => void
  handleTableFileChange: (event: ChangeEvent<HTMLInputElement>) => void
  handleScriptChange: (script: string) => void
  convertFileToText: () => void
  loadTablePreview: () => Promise<void>
  executeImport: () => Promise<void>
}

interface ImportResultState {
  status: boolean
  detail?: string | null
  message?: string | null
}

interface DatabaseImportProviderProps {
  connectionId: string
  databaseName: string
  schema?: string | null
  tableName?: string | null
  onSuccess?: (context: { databaseName: string; schema?: string | null; tableName?: string | null }) => void
  children: ReactNode
}

const CSV_DELIMITER_OPTIONS = [
  { value: '', labelKey: 'database.import.table.csvDelimiter.auto' },
  { value: ',', labelKey: 'database.import.table.csvDelimiter.comma' },
  { value: ';', labelKey: 'database.import.table.csvDelimiter.semicolon' },
  { value: '|', labelKey: 'database.import.table.csvDelimiter.pipe' },
] as const

const TABLE_IMPORT_MODES = [
  { value: ImportMode.Append, labelKey: 'database.import.table.mode.append' },
  { value: ImportMode.Upsert, labelKey: 'database.import.table.mode.upsert' },
  { value: ImportMode.Overwrite, labelKey: 'database.import.table.mode.overwrite' },
] as const

const DatabaseImportContext = createContext<DatabaseImportContextValue | null>(null)

function formatImportTargetLabel(databaseName: string, schema?: string | null, tableName?: string | null): string {
  if (tableName) {
    return schema ? `${databaseName}.${schema}.${tableName}` : `${databaseName}.${tableName}`
  }

  return schema ? `${databaseName}.${schema}` : databaseName
}

function useDatabaseImport(): DatabaseImportContextValue {
  const context = use(DatabaseImportContext)
  if (!context) throw new Error('useDatabaseImport must be used within DatabaseImportProvider')
  return context
}

/** Provides state and execution behavior for the shared Database Import modal. */
function DatabaseImportProvider({
  connectionId,
  databaseName,
  schema,
  tableName,
  onSuccess,
  children,
}: DatabaseImportProviderProps) {
  const { t } = useI18n()
  const [method, setMethodState] = useState<ImportMethod>('tableFile')
  const [sourceKind, setSourceKindState] = useState<SourceKind>('file')
  const [tableTargetMode, setTableTargetModeState] = useState<TableTargetMode>(tableName ? 'existing' : 'new')
  const [source, setSource] = useState<SqlScriptSource | null>(null)
  const [tableSource, setTableSource] = useState<TableFileSource | null>(null)
  const [tablePreview, setTablePreview] = useState<TableImportPreview | null>(null)
  const [targetDatabase, setTargetDatabase] = useState(databaseName)
  const [databaseOptions, setDatabaseOptions] = useState<string[]>([databaseName])
  const [tableImportMode, setTableImportMode] = useState<ImportMode>(ImportMode.Append)
  const [csvDelimiter, setCsvDelimiter] = useState('')
  const [excelSheet, setExcelSheet] = useState('')
  const [useHeaderMapping, setUseHeaderMapping] = useState(true)
  const [allowAutoGenerated, setAllowAutoGenerated] = useState(false)
  const [newTableName, setNewTableName] = useState('')
  const [newTableColumns, setNewTableColumns] = useState<ImportNewTableColumnInput[]>([])
  const [result, setResult] = useState<ImportResultState | null>(null)
  const sqlFileInputRef = useRef<HTMLInputElement | null>(null)
  const tableFileInputRef = useRef<HTMLInputElement | null>(null)
  const fetchDatabases = useConnectionStore((state) => state.fetchDatabases)
  const connections = useConnectionStore((state) => state.connections)
  const connection = connections.find((item) => item.id === connectionId)
  const { actions } = useModalForm()
  const [importSql] = useImportSqlMutation()
  const [importPreview, { loading: previewLoading }] = useImportPreviewMutation()
  const [importTableFile] = useImportTableFileMutation()
  const { data: metadataData, loading: metadataLoading, error: metadataError } = useGetDatabaseMetadataQuery({
    context: { database: databaseName },
  })
  const metadata = metadataData?.DatabaseMetadata ?? null
  const typeOptions = useMemo(() => getColumnTypeOptions(metadata), [metadata])
  const defaultTextType = useMemo(() => getDefaultTextColumnType(metadata), [metadata])
  const metadataFailed = Boolean(metadataError) || (!metadataLoading && typeOptions.length === 0)

  const targetTableSchema = resolveSchemaParam(connection?.type, databaseName, schema ?? undefined)
  const targetTableLabel = formatImportTargetLabel(databaseName, schema, tableName)
  const newTableValidationError = useMemo(
    () => getNewTableValidationError(newTableName, newTableColumns),
    [newTableColumns, newTableName],
  )

  useEffect(() => {
    setTargetDatabase(databaseName)
    setDatabaseOptions([databaseName])
  }, [databaseName])

  useEffect(() => {
    if (!tableName && tableTargetMode === 'existing') {
      setTableTargetModeState('new')
    }
  }, [tableName, tableTargetMode])

  useEffect(() => {
    let cancelled = false

    void fetchDatabases(connectionId)
      .then((databases) => {
        if (cancelled) return
        const nextOptions = databases.includes(databaseName)
          ? databases
          : [databaseName, ...databases]
        setDatabaseOptions([...new Set(nextOptions)])
      })
      .catch(() => {
        if (!cancelled) {
          actions.setAlert({
            type: 'error',
            title: t('database.import.loadDatabasesFailed'),
            message: t('database.import.loadDatabasesFailedMessage'),
          })
        }
      })

    return () => { cancelled = true }
  }, [actions, connectionId, databaseName, fetchDatabases, t])

  useEffect(() => {
    setTablePreview(null)
    setResult(null)
    setAllowAutoGenerated(false)
    setNewTableName('')
    setNewTableColumns([])
  }, [csvDelimiter, excelSheet, tableSource, tableTargetMode, useHeaderMapping])

  const setMethod = useCallback((nextMethod: ImportMethod) => {
    setMethodState(nextMethod)
    setResult(null)
    actions.closeAlert()

    if (nextMethod === 'sql') {
      setTableSource(null)
      setTablePreview(null)
      setAllowAutoGenerated(false)
      if (tableFileInputRef.current) tableFileInputRef.current.value = ''
      return
    }

    setSource(null)
    setSourceKindState('file')
    setTargetDatabase(databaseName)
    if (sqlFileInputRef.current) sqlFileInputRef.current.value = ''
  }, [actions, databaseName])

  const setTableTargetMode = useCallback((nextMode: TableTargetMode) => {
    if (nextMode === 'existing' && !tableName) return
    setTableTargetModeState(nextMode)
    setResult(null)
    setTablePreview(null)
    setAllowAutoGenerated(false)
    actions.closeAlert()
  }, [actions, tableName])

  const setSourceKind = useCallback((kind: SourceKind) => {
    setSourceKindState(kind)
    setSource(null)
    setResult(null)
    actions.closeAlert()
    if (kind === 'file' && sqlFileInputRef.current) {
      sqlFileInputRef.current.value = ''
    }
  }, [actions])

  const handleFileChange = useCallback(async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (!file) return

    actions.closeAlert()
    setResult(null)

    if (!isAcceptedSqlFile(file)) {
      setSource(null)
      actions.setAlert({
        type: 'error',
        title: t('database.import.invalidFileTitle'),
        message: t('database.import.invalidFileMessage'),
      })
      event.target.value = ''
      return
    }

    try {
      const preview = await file.text()
      setSourceKindState('file')
      setSource({ kind: 'file', file, filename: file.name, preview })
    } catch {
      setSource(null)
      actions.setAlert({
        type: 'error',
        title: t('database.import.readFileFailedTitle'),
        message: t('database.import.readFileFailedMessage'),
      })
      event.target.value = ''
    }
  }, [actions, t])

  const handleTableFileChange = useCallback((event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (!file) return

    actions.closeAlert()
    setResult(null)

    const format = getTableFileFormat(file.name)
    if (!format) {
      setTableSource(null)
      actions.setAlert({
        type: 'error',
        title: t('database.import.invalidFileTitle'),
        message: t('database.import.table.invalidFileMessage'),
      })
      event.target.value = ''
      return
    }

    setTableSource({ kind: 'tableFile', file, filename: file.name, format })
  }, [actions, t])

  const handleScriptChange = useCallback((script: string) => {
    setSourceKindState('text')
    setSource({ kind: 'text', script })
    setResult(null)
    actions.closeAlert()
  }, [actions])

  const convertFileToText = useCallback(() => {
    if (!source || source.kind !== 'file') return
    setSourceKindState('text')
    setSource({ kind: 'text', script: source.preview })
    setResult(null)
    actions.closeAlert()
    if (sqlFileInputRef.current) sqlFileInputRef.current.value = ''
  }, [actions, source])

  const loadTablePreview = useCallback(async () => {
    if (!tableSource) return
    if (tableTargetMode === 'existing' && !tableName) return

    actions.closeAlert()
    setResult(null)

    const input = tableTargetMode === 'existing'
      ? {
          TargetMode: ImportTargetMode.ExistingTable,
          ExistingTable: {
            Schema: targetTableSchema,
            StorageUnit: tableName ?? '',
            UseHeaderMapping: useHeaderMapping,
          },
          Options: buildTableFileOptions(tableSource, csvDelimiter, excelSheet),
          File: tableSource.file,
        }
      : {
          TargetMode: ImportTargetMode.NewTable,
          NewTable: {
            Schema: targetTableSchema,
          },
          Options: buildTableFileOptions(tableSource, csvDelimiter, excelSheet),
          File: tableSource.file,
        }

    try {
      const { data, errors } = await importPreview({
        variables: { input },
        context: { database: databaseName },
      })

      if (errors?.length) {
        actions.setAlert({
          type: 'error',
          title: t('database.import.table.previewFailedTitle'),
          message: errors[0].message,
        })
        return
      }

      const preview = data?.ImportPreview
      if (!preview) {
        actions.setAlert({
          type: 'error',
          title: t('database.import.table.previewFailedTitle'),
          message: t('database.import.table.previewFailedMessage'),
        })
        return
      }

      setTablePreview(preview)
      if (tableTargetMode === 'new' && preview.NewTable) {
        setNewTableName(preview.NewTable.TableName)
        setNewTableColumns(preview.NewTable.Columns.map((column) => ({
          SourceColumn: column.SourceColumn,
          TargetColumn: column.TargetColumn,
          Type: column.Type || defaultTextType,
          Nullable: column.Nullable,
          Primary: column.Primary,
          Skip: column.Skip,
        })))
      }
    } catch (error) {
      actions.setAlert({
        type: 'error',
        title: t('database.import.table.previewFailedTitle'),
        message: error instanceof Error ? error.message : t('database.import.table.previewFailedMessage'),
      })
    }
  }, [
    actions,
    csvDelimiter,
    databaseName,
    defaultTextType,
    excelSheet,
    importPreview,
    t,
    tableName,
    tableSource,
    tableTargetMode,
    targetTableSchema,
    useHeaderMapping,
  ])

  const executeSqlImport = useCallback(async () => {
    if (!source || !hasSqlScriptSource(source)) return

    const { data, errors } = await importSql({
      variables: { input: buildImportSqlInput(source) },
      context: { database: targetDatabase },
    })

    if (errors?.length) {
      actions.setAlert({
        type: 'error',
        title: t('database.import.failedTitle'),
        message: errors[0].message,
      })
      return
    }

    const importResult = data?.ImportSQL
    if (!importResult) {
      actions.setAlert({
        type: 'error',
        title: t('database.import.failedTitle'),
        message: t('database.import.failedMessage'),
      })
      return
    }

    setResult({ status: importResult.Status, detail: importResult.Detail, message: importResult.Message })
    if (importResult.Status) {
      onSuccess?.(targetDatabase === databaseName
        ? { databaseName: targetDatabase, schema, tableName }
        : { databaseName: targetDatabase, schema: null, tableName: null })
    }
  }, [actions, databaseName, importSql, onSuccess, schema, source, t, tableName, targetDatabase])

  const executeTableFileImport = useCallback(async () => {
    if (!tableSource || !tablePreview) return
    if (tableTargetMode === 'existing' && (!tableName || !tablePreview.Mapping?.length)) return
    if (tableTargetMode === 'new' && (!tablePreview.NewTable || newTableValidationError || metadataLoading || metadataFailed)) return

    const input = tableTargetMode === 'existing'
      ? buildImportTableFileInput({
          targetMode: ImportTargetMode.ExistingTable,
          source: tableSource,
          schema: targetTableSchema,
          storageUnit: tableName ?? '',
          mode: tableImportMode,
          mapping: tablePreview.Mapping?.map((item): ImportColumnMapping => ({
            SourceColumn: item.SourceColumn,
            TargetColumn: item.TargetColumn,
            Skip: false,
          })) ?? [],
          delimiter: csvDelimiter,
          sheet: excelSheet,
          allowAutoGenerated,
        })
      : buildImportTableFileInput({
          targetMode: ImportTargetMode.NewTable,
          source: tableSource,
          schema: targetTableSchema,
          tableName: newTableName.trim(),
          columns: newTableColumns,
          delimiter: csvDelimiter,
          sheet: excelSheet,
        })

    const { data, errors } = await importTableFile({
      variables: {
        input,
      },
      context: { database: databaseName },
    })

    if (errors?.length) {
      actions.setAlert({
        type: 'error',
        title: t('database.import.failedTitle'),
        message: errors[0].message,
      })
      return
    }

    const importResult = data?.ImportTableFile
    if (!importResult) {
      actions.setAlert({
        type: 'error',
        title: t('database.import.failedTitle'),
        message: t('database.import.table.failedMessage'),
      })
      return
    }

    setResult({ status: importResult.Status, detail: importResult.Detail, message: importResult.Message })
    if (importResult.Status) {
      onSuccess?.({
        databaseName,
        schema,
        tableName: tableTargetMode === 'new' ? newTableName.trim() : tableName,
      })
    }
  }, [
    actions,
    allowAutoGenerated,
    csvDelimiter,
    databaseName,
    excelSheet,
    importTableFile,
    metadataFailed,
    metadataLoading,
    newTableColumns,
    newTableName,
    newTableValidationError,
    onSuccess,
    schema,
    t,
    tableImportMode,
    tableName,
    tablePreview,
    tableSource,
    tableTargetMode,
    targetTableSchema,
  ])

  const executeImport = useCallback(async () => {
    actions.setSubmitting(true)
    actions.closeAlert()
    setResult(null)

    try {
      if (method === 'tableFile') {
        await executeTableFileImport()
      } else {
        await executeSqlImport()
      }
    } catch (error) {
      actions.setAlert({
        type: 'error',
        title: t('database.import.failedTitle'),
        message: error instanceof Error ? error.message : t(method === 'tableFile'
          ? 'database.import.table.failedMessage'
          : 'database.import.failedMessage'),
      })
    } finally {
      actions.setSubmitting(false)
    }
  }, [actions, executeSqlImport, executeTableFileImport, method, t])

  const updateNewTableColumn = useCallback((index: number, field: keyof ImportNewTableColumnInput, value: string | boolean) => {
    setNewTableColumns((prev) => prev.map((column, columnIndex) => {
      if (columnIndex !== index) return column
      if (field === 'Primary') {
        return { ...column, Primary: value === true, Nullable: value === true ? false : column.Nullable }
      }
      if (field === 'Nullable' && column.Primary) return column
      if (field === 'Skip') {
        return { ...column, Skip: value === true, Primary: value === true ? false : column.Primary }
      }
      return { ...column, [field]: value }
    }))
  }, [])

  const contextValue = useMemo<DatabaseImportContextValue>(() => ({
    method,
    sourceKind,
    tableTargetMode,
    source,
    tableSource,
    tablePreview,
    targetDatabase,
    databaseOptions,
    tableName,
    targetTableLabel,
    tableImportMode,
    csvDelimiter,
    excelSheet,
    useHeaderMapping,
    allowAutoGenerated,
    newTableName,
    newTableColumns,
    typeOptions,
    metadataLoading,
    metadataFailed,
    newTableValidationError,
    previewLoading,
    result,
    sqlFileInputRef,
    tableFileInputRef,
    setMethod,
    setSourceKind,
    setTableTargetMode,
    setTargetDatabase,
    setTableImportMode,
    setCsvDelimiter,
    setExcelSheet,
    setUseHeaderMapping,
    setAllowAutoGenerated,
    setNewTableName,
    updateNewTableColumn,
    handleFileChange,
    handleTableFileChange,
    handleScriptChange,
    convertFileToText,
    loadTablePreview,
    executeImport,
  }), [
    allowAutoGenerated,
    convertFileToText,
    csvDelimiter,
    databaseOptions,
    excelSheet,
    executeImport,
    handleFileChange,
    handleScriptChange,
    handleTableFileChange,
    loadTablePreview,
    metadataFailed,
    metadataLoading,
    method,
    newTableColumns,
    newTableName,
    newTableValidationError,
    previewLoading,
    result,
    setMethod,
    setSourceKind,
    setTableTargetMode,
    source,
    sourceKind,
    tableImportMode,
    tableTargetMode,
    tableName,
    tablePreview,
    tableSource,
    targetDatabase,
    targetTableLabel,
    typeOptions,
    updateNewTableColumn,
    useHeaderMapping,
  ])

  return (
    <DatabaseImportContext value={contextValue}>
      {children}
    </DatabaseImportContext>
  )
}

function DatabaseImportFields() {
  const { method } = useDatabaseImport()

  return (
    <div className="flex max-h-[68vh] flex-col gap-4 overflow-y-auto pr-1">
      <ImportMethodSelector />
      {method === 'tableFile' ? (
        <TableFileImportFields />
      ) : (
        <>
          <TargetDatabaseSelect />
          <SqlSourceSelector />
        </>
      )}
      <ImportResultFeedback />
    </div>
  )
}

function ImportMethodSelector() {
  const { t } = useI18n()
  const { method, setMethod } = useDatabaseImport()
  const { state } = useModalForm()
  const disabled = state.isSubmitting

  return (
    <div className="flex flex-col gap-2">
      <span className="text-sm font-medium text-foreground">{t('database.import.method')}</span>
      <div className="grid gap-2 sm:grid-cols-2">
        <button
          type="button"
          onClick={() => setMethod('sql')}
          disabled={disabled}
          aria-pressed={method === 'sql'}
          className={cn(
            'flex min-h-14 items-center gap-3 rounded-md border px-3 py-2 text-left transition-colors',
            method === 'sql'
              ? 'border-primary bg-primary/5'
              : 'border-input bg-background hover:bg-muted/30',
          )}
        >
          <FileCode className="h-4 w-4 text-primary" />
          <span className="flex flex-col gap-0.5">
            <span className="text-sm font-medium">{t('database.import.method.sqlFile')}</span>
            <span className="text-xs text-muted-foreground">{t('database.import.method.sqlFileDescription')}</span>
          </span>
        </button>
        <button
          type="button"
          onClick={() => setMethod('tableFile')}
          disabled={disabled}
          aria-pressed={method === 'tableFile'}
          className={cn(
            'flex min-h-14 items-center gap-3 rounded-md border px-3 py-2 text-left transition-colors',
            method === 'tableFile'
              ? 'border-primary bg-primary/5'
              : 'border-input bg-background hover:bg-muted/30',
          )}
        >
          <FileSpreadsheet className="h-4 w-4 text-primary" />
          <span className="flex flex-col gap-0.5">
            <span className="text-sm font-medium">{t('database.import.method.tableFile')}</span>
            <span className="text-xs text-muted-foreground">{t('database.import.method.tableFileDescription')}</span>
          </span>
        </button>
      </div>
    </div>
  )
}

function TargetDatabaseSelect() {
  const { t } = useI18n()
  const { targetDatabase, setTargetDatabase, databaseOptions } = useDatabaseImport()
  const { state } = useModalForm()

  return (
    <div className="flex flex-col gap-2">
      <label className="text-sm font-medium text-foreground" htmlFor="database-import-target">
        {t('database.import.targetDatabase')}
      </label>
      <select
        id="database-import-target"
        value={targetDatabase}
        onChange={(event) => setTargetDatabase(event.target.value)}
        disabled={state.isSubmitting}
        className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm shadow-xs outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:opacity-50"
      >
        {databaseOptions.map((database) => (
          <option key={database} value={database}>{database}</option>
        ))}
      </select>
    </div>
  )
}

function SqlSourceSelector() {
  const { t } = useI18n()
  const { sourceKind, setSourceKind, source } = useDatabaseImport()
  const { state } = useModalForm()

  return (
    <div className="flex flex-col gap-3">
      <span className="text-sm font-medium text-foreground">{t('database.import.source')}</span>
      <div className="inline-flex w-fit rounded-md border border-input p-1">
        <button
          type="button"
          onClick={() => setSourceKind('file')}
          disabled={state.isSubmitting}
          aria-pressed={sourceKind === 'file'}
          className={cn(
            'rounded-sm px-3 py-1.5 text-sm transition-colors',
            sourceKind === 'file' ? 'bg-highlight-background text-foreground' : 'text-muted-foreground hover:text-foreground',
          )}
        >
          {t('database.import.source.file')}
        </button>
        <button
          type="button"
          onClick={() => setSourceKind('text')}
          disabled={state.isSubmitting}
          aria-pressed={sourceKind === 'text'}
          className={cn(
            'rounded-sm px-3 py-1.5 text-sm transition-colors',
            sourceKind === 'text' ? 'bg-highlight-background text-foreground' : 'text-muted-foreground hover:text-foreground',
          )}
        >
          {t('database.import.source.text')}
        </button>
      </div>
      {sourceKind === 'file' ? <SqlFileSource /> : <SqlTextSource />}
      {!hasSqlScriptSource(source) && (
        <p className="text-xs text-muted-foreground">{t('database.import.emptySourceHint')}</p>
      )}
    </div>
  )
}

function SqlFileSource() {
  const { t } = useI18n()
  const { source, sqlFileInputRef, handleFileChange, convertFileToText } = useDatabaseImport()
  const { state } = useModalForm()
  const fileSource = source?.kind === 'file' ? source : null

  return (
    <div className="flex flex-col gap-3">
      <Input
        ref={sqlFileInputRef}
        type="file"
        accept=".sql"
        onChange={handleFileChange}
        disabled={state.isSubmitting}
        aria-label={t('database.import.uploadSqlFile')}
      />
      {fileSource && (
        <div className="flex flex-col gap-2">
          <div className="flex items-center justify-between gap-3">
            <span className="min-w-0 truncate text-sm text-muted-foreground">
              {t('database.import.selectedFile', { filename: fileSource.filename })}
            </span>
            <Button type="button" variant="outline" size="sm" onClick={convertFileToText} disabled={state.isSubmitting}>
              {t('database.import.editAsText')}
            </Button>
          </div>
          <Textarea
            value={fileSource.preview}
            readOnly
            aria-readonly="true"
            aria-label={t('database.import.sqlFilePreview')}
            className="h-52 resize-none font-mono text-xs"
          />
        </div>
      )}
    </div>
  )
}

function SqlTextSource() {
  const { t } = useI18n()
  const { source, handleScriptChange } = useDatabaseImport()
  const { state } = useModalForm()
  const script = source?.kind === 'text' ? source.script : ''

  return (
    <Textarea
      value={script}
      onChange={(event) => handleScriptChange(event.target.value)}
      disabled={state.isSubmitting}
      aria-label={t('database.import.sqlTextInput')}
      placeholder={t('database.import.pastePlaceholder')}
      className="h-60 resize-none font-mono text-xs"
    />
  )
}

function TableFileImportFields() {
  return (
    <>
      <TableTargetModeSelector />
      <TableFileSourceInput />
      <TableImportOptions />
      <TableImportPreview />
    </>
  )
}

function TableTargetModeSelector() {
  const { t } = useI18n()
  const { tableTargetMode, setTableTargetMode, tableName, targetTableLabel } = useDatabaseImport()
  const { state } = useModalForm()
  const existingDisabled = state.isSubmitting || !tableName

  return (
    <div className="flex flex-col gap-2">
      <span className="text-sm font-medium text-foreground">{t('database.import.table.targetMode')}</span>
      <div className="grid gap-2 sm:grid-cols-2">
        <button
          type="button"
          onClick={() => setTableTargetMode('existing')}
          disabled={existingDisabled}
          aria-pressed={tableTargetMode === 'existing'}
          className={cn(
            'flex min-h-14 flex-col rounded-md border px-3 py-2 text-left transition-colors',
            tableTargetMode === 'existing'
              ? 'border-primary bg-primary/5'
              : existingDisabled
                ? 'border-input bg-muted/20 opacity-60'
                : 'border-input bg-background hover:bg-muted/30',
          )}
        >
          <span className="text-sm font-medium">{t('database.import.table.targetModeExisting')}</span>
          <span className="text-xs text-muted-foreground">
            {tableName ? targetTableLabel : t('database.import.table.targetModeExistingUnavailable')}
          </span>
        </button>
        <button
          type="button"
          onClick={() => setTableTargetMode('new')}
          disabled={state.isSubmitting}
          aria-pressed={tableTargetMode === 'new'}
          className={cn(
            'flex min-h-14 flex-col rounded-md border px-3 py-2 text-left transition-colors',
            tableTargetMode === 'new'
              ? 'border-primary bg-primary/5'
              : 'border-input bg-background hover:bg-muted/30',
          )}
        >
          <span className="text-sm font-medium">{t('database.import.table.targetModeNew')}</span>
          <span className="text-xs text-muted-foreground">{t('database.import.table.targetModeNewDescription')}</span>
        </button>
      </div>
    </div>
  )
}

function TableFileSourceInput() {
  const { t } = useI18n()
  const { tableSource, tableFileInputRef, handleTableFileChange } = useDatabaseImport()
  const { state } = useModalForm()

  return (
    <div className="flex flex-col gap-3">
      <label className="text-sm font-medium text-foreground" htmlFor="database-import-table-file">
        {t('database.import.table.source')}
      </label>
      <Input
        ref={tableFileInputRef}
        id="database-import-table-file"
        type="file"
        accept=".csv,.xls,.xlsx"
        onChange={handleTableFileChange}
        disabled={state.isSubmitting}
        aria-label={t('database.import.table.uploadFile')}
      />
      {tableSource ? (
        <span className="min-w-0 truncate text-sm text-muted-foreground">
          {t('database.import.selectedFile', { filename: tableSource.filename })}
        </span>
      ) : (
        <p className="text-xs text-muted-foreground">{t('database.import.table.emptySourceHint')}</p>
      )}
    </div>
  )
}

function TableImportOptions() {
  const { t } = useI18n()
  const {
    tableTargetMode,
    tableSource,
    tableImportMode,
    csvDelimiter,
    excelSheet,
    useHeaderMapping,
    allowAutoGenerated,
    tablePreview,
    previewLoading,
    metadataLoading,
    metadataFailed,
    setTableImportMode,
    setCsvDelimiter,
    setExcelSheet,
    setUseHeaderMapping,
    setAllowAutoGenerated,
    loadTablePreview,
  } = useDatabaseImport()
  const { state } = useModalForm()
  const disabled = state.isSubmitting || previewLoading
  const previewDisabled = !tableSource || disabled || (tableTargetMode === 'new' && (metadataLoading || metadataFailed))

  return (
    <div className="flex flex-col gap-3">
      <span className="text-sm font-medium text-foreground">{t('database.import.table.options')}</span>
      <div className="grid gap-3 sm:grid-cols-2">
        {tableTargetMode === 'existing' && (
          <label className="flex flex-col gap-2 text-sm">
            <span className="font-medium text-foreground">{t('database.import.table.mode')}</span>
            <select
              value={tableImportMode}
              onChange={(event) => setTableImportMode(event.target.value as ImportMode)}
              disabled={disabled}
              className="h-9 rounded-md border border-input bg-background px-3 text-sm shadow-xs outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:opacity-50"
            >
              {TABLE_IMPORT_MODES.map((option) => (
                <option key={option.value} value={option.value}>{t(option.labelKey)}</option>
              ))}
            </select>
          </label>
        )}

        {tableSource?.format === ImportFileFormat.Excel ? (
          <label className="flex flex-col gap-2 text-sm">
            <span className="font-medium text-foreground">{t('database.import.table.excelSheet')}</span>
            <Input
              value={excelSheet}
              onChange={(event) => setExcelSheet(event.target.value)}
              disabled={disabled}
              placeholder={t('database.import.table.excelSheetPlaceholder')}
            />
          </label>
        ) : (
          <label className="flex flex-col gap-2 text-sm">
            <span className="font-medium text-foreground">{t('database.import.table.csvDelimiter')}</span>
            <select
              value={csvDelimiter}
              onChange={(event) => setCsvDelimiter(event.target.value)}
              disabled={disabled}
              className="h-9 rounded-md border border-input bg-background px-3 text-sm shadow-xs outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:opacity-50"
            >
              {CSV_DELIMITER_OPTIONS.map((option) => (
                <option key={option.value || 'auto'} value={option.value}>{t(option.labelKey)}</option>
              ))}
            </select>
          </label>
        )}
      </div>

      {tableTargetMode === 'existing' && (
        <label className="flex items-center gap-2 text-sm text-foreground">
          <Checkbox
            checked={useHeaderMapping}
            onCheckedChange={(checked) => setUseHeaderMapping(checked === true)}
            disabled={disabled}
          />
          <span>{t('database.import.table.useHeaderMapping')}</span>
        </label>
      )}

      {tableTargetMode === 'existing' && tablePreview?.RequiresAllowAutoGenerated && (
        <div className="flex flex-col gap-2 rounded-md border border-warning/20 bg-warning/5 p-3 text-sm text-warning">
          <label className="flex items-center gap-2">
            <Checkbox
              checked={allowAutoGenerated}
              onCheckedChange={(checked) => setAllowAutoGenerated(checked === true)}
              disabled={disabled}
            />
            <span>{t('database.import.table.allowAutoGenerated')}</span>
          </label>
          <span className="font-mono text-xs">
            {t('database.import.table.allowAutoGeneratedColumns', {
              columns: tablePreview.AutoGeneratedColumns.join(', '),
            })}
          </span>
        </div>
      )}

      {tableTargetMode === 'new' && metadataLoading && (
        <div className="rounded-md border border-primary/20 bg-primary/5 px-3 py-2 text-sm text-primary">
          {t('database.import.table.metadataLoading')}
        </div>
      )}
      {tableTargetMode === 'new' && metadataFailed && (
        <div className="rounded-md border border-destructive/20 bg-destructive/5 px-3 py-2 text-sm text-destructive">
          {t('database.import.table.metadataUnavailable')}
        </div>
      )}

      <Button
        type="button"
        variant="outline"
        onClick={loadTablePreview}
        disabled={previewDisabled}
        className="w-fit gap-2"
      >
        {previewLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileSpreadsheet className="h-4 w-4" />}
        {previewLoading ? t('database.import.table.previewLoading') : t('database.import.table.previewAction')}
      </Button>
    </div>
  )
}

function TableImportPreview() {
  const { t } = useI18n()
  const { tableTargetMode, tablePreview, previewLoading } = useDatabaseImport()

  if (previewLoading) {
    return (
      <div role="status" className="flex items-center gap-2 rounded-md border border-primary/20 bg-primary/5 p-3 text-sm text-primary">
        <Loader2 className="h-4 w-4 animate-spin" />
        <span>{t('database.import.table.previewLoading')}</span>
      </div>
    )
  }

  if (!tablePreview) {
    return null
  }

  if (tablePreview.ValidationError) {
    return (
      <div role="alert" className="flex items-start gap-2 rounded-md border border-destructive/20 bg-destructive/5 p-3 text-sm text-destructive">
        <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
        <span>{formatImportFailure(t, tablePreview.ValidationError, true)}</span>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-3">
      {tableTargetMode === 'existing' && tablePreview.Mapping && tablePreview.Mapping.length > 0 && (
        <div className="flex flex-col gap-2">
          <span className="text-sm font-medium text-foreground">{t('database.import.table.mapping')}</span>
          <div className="max-h-40 overflow-auto rounded-md border">
            <table className="w-full min-w-96 text-left text-xs">
              <thead className="bg-muted/50 text-muted-foreground">
                <tr>
                  <th className="px-3 py-2 font-medium">{t('database.import.table.sourceColumn')}</th>
                  <th className="px-3 py-2 font-medium">{t('database.import.table.targetColumn')}</th>
                </tr>
              </thead>
              <tbody>
                {tablePreview.Mapping.map((mapping) => (
                  <tr key={`${mapping.SourceColumn}-${mapping.TargetColumn}`} className="border-t">
                    <td className="px-3 py-2 font-mono">{mapping.SourceColumn}</td>
                    <td className="px-3 py-2 font-mono">{mapping.TargetColumn}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {tableTargetMode === 'new' && tablePreview.NewTable && <NewTableDefinitionEditor />}

      <div className="flex flex-col gap-2">
        <span className="text-sm font-medium text-foreground">{t('database.import.table.previewRows')}</span>
        <div className="max-h-56 overflow-auto rounded-md border">
          <table className="w-full min-w-128 text-left text-xs">
            <thead className="bg-muted/50 text-muted-foreground">
              <tr>
                {tablePreview.Columns.map((column) => (
                  <th key={column} className="px-3 py-2 font-medium">{column}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {tablePreview.Rows.map((row, rowIndex) => (
                <tr key={rowIndex} className="border-t">
                  {tablePreview.Columns.map((column, columnIndex) => (
                    <td key={`${rowIndex}-${column}`} className="px-3 py-2 font-mono">
                      {row[columnIndex] ?? ''}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {tablePreview.Truncated && (
          <span className="text-xs text-muted-foreground">{t('database.import.table.truncated')}</span>
        )}
      </div>
    </div>
  )
}

function NewTableDefinitionEditor() {
  const { t } = useI18n()
  const {
    newTableName,
    newTableColumns,
    typeOptions,
    metadataLoading,
    metadataFailed,
    newTableValidationError,
    tablePreview,
    setNewTableName,
    updateNewTableColumn,
  } = useDatabaseImport()
  const { state } = useModalForm()
  const disabled = state.isSubmitting || metadataLoading || metadataFailed

  return (
    <div className="flex flex-col gap-3">
      <label className="flex flex-col gap-2 text-sm">
        <span className="font-medium text-foreground">{t('database.import.table.newTableName')}</span>
        <Input
          value={newTableName}
          onChange={(event) => setNewTableName(event.target.value)}
          disabled={state.isSubmitting}
          placeholder={t('database.import.table.newTableNamePlaceholder')}
        />
      </label>

      {metadataLoading && (
        <div className="rounded-md border border-primary/20 bg-primary/5 px-3 py-2 text-sm text-primary">
          {t('database.import.table.metadataLoading')}
        </div>
      )}
      {metadataFailed && (
        <div className="rounded-md border border-destructive/20 bg-destructive/5 px-3 py-2 text-sm text-destructive">
          {t('database.import.table.metadataUnavailable')}
        </div>
      )}
      {newTableValidationError && (
        <div role="alert" className="rounded-md border border-destructive/20 bg-destructive/5 px-3 py-2 text-sm text-destructive">
          {formatImportFailure(t, newTableValidationError, true)}
        </div>
      )}
      {tablePreview?.NewTable?.Issues.length ? (
        <div className="rounded-md border border-warning/20 bg-warning/5 px-3 py-2 text-sm text-warning">
          {t('database.import.table.newTableIssues')}
        </div>
      ) : null}

      <div className="flex flex-col gap-2">
        <span className="text-sm font-medium text-foreground">{t('database.import.table.newTableColumns')}</span>
        <div className="max-h-72 overflow-auto rounded-md border">
          <table className="w-full min-w-192 text-left text-xs">
            <thead className="bg-muted/50 text-muted-foreground">
              <tr>
                <th className="px-3 py-2 font-medium">{t('database.import.table.sourceColumn')}</th>
                <th className="px-3 py-2 font-medium">{t('database.import.table.targetColumn')}</th>
                <th className="px-3 py-2 font-medium">{t('database.import.table.columnType')}</th>
                <th className="px-3 py-2 text-center font-medium">{t('database.import.table.primary')}</th>
                <th className="px-3 py-2 text-center font-medium">{t('database.import.table.nullable')}</th>
                <th className="px-3 py-2 text-center font-medium">{t('database.import.table.skip')}</th>
              </tr>
            </thead>
            <tbody>
              {newTableColumns.map((column, index) => (
                <tr key={`${column.SourceColumn}-${index}`} className="border-t">
                  <td className="px-3 py-2 font-mono">{column.SourceColumn}</td>
                  <td className="px-3 py-2">
                    <Input
                      value={column.TargetColumn ?? ''}
                      onChange={(event) => updateNewTableColumn(index, 'TargetColumn', event.target.value)}
                      disabled={disabled || column.Skip}
                      className="h-8 min-w-36 font-mono text-xs"
                    />
                  </td>
                  <td className="px-3 py-2">
                    <select
                      value={column.Type ?? ''}
                      onChange={(event) => updateNewTableColumn(index, 'Type', event.target.value)}
                      disabled={disabled || column.Skip}
                      className="h-8 min-w-36 rounded-md border border-input bg-background px-2 text-xs shadow-xs outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:opacity-50"
                    >
                      {typeOptions.map((option) => (
                        <option key={option.id} value={option.id}>{option.label}</option>
                      ))}
                    </select>
                  </td>
                  <td className="px-3 py-2 text-center">
                    <Checkbox
                      checked={column.Primary}
                      onCheckedChange={(checked) => updateNewTableColumn(index, 'Primary', checked === true)}
                      disabled={disabled || column.Skip}
                    />
                  </td>
                  <td className="px-3 py-2 text-center">
                    <Checkbox
                      checked={column.Nullable}
                      onCheckedChange={(checked) => updateNewTableColumn(index, 'Nullable', checked === true)}
                      disabled={disabled || column.Skip || column.Primary}
                    />
                  </td>
                  <td className="px-3 py-2 text-center">
                    <Checkbox
                      checked={column.Skip}
                      onCheckedChange={(checked) => updateNewTableColumn(index, 'Skip', checked === true)}
                      disabled={state.isSubmitting}
                    />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}

function ImportResultFeedback() {
  const { t } = useI18n()
  const { method, result } = useDatabaseImport()
  const { state } = useModalForm()

  if (state.isSubmitting) {
    return (
      <div role="status" className="flex items-center gap-2 rounded-md border border-primary/20 bg-primary/5 p-3 text-sm text-primary">
        <Loader2 className="h-4 w-4 animate-spin" />
        <span>{t('database.import.running')}</span>
      </div>
    )
  }

  if (!result) {
    if (method !== 'sql') return null
    return (
      <div className="flex items-start gap-2 rounded-md border border-warning/20 bg-warning/5 p-3 text-sm text-warning">
        <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
        <span>{t('database.import.reviewWarning')}</span>
      </div>
    )
  }

  if (result.status) {
    return (
      <div role="status" className="flex items-center gap-2 rounded-md border border-success/20 bg-success/5 p-3 text-sm text-success">
        <CheckCircle className="h-4 w-4" />
        <span>{t('database.import.successMessage')}</span>
      </div>
    )
  }

  return (
    <div role="alert" className="flex items-start gap-2 rounded-md border border-destructive/20 bg-destructive/5 p-3 text-sm text-destructive">
      <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
      <div className="min-w-0">
        <span>{formatImportFailure(t, result.detail, method === 'tableFile')}</span>
        {result.message && (
          <pre className="mt-2 whitespace-pre-wrap break-words font-mono text-xs leading-relaxed">{result.message}</pre>
        )}
      </div>
    </div>
  )
}

function formatImportFailure(t: ReturnType<typeof useI18n>['t'], detail?: string | null, tableFile = false): string {
  switch (detail) {
    case 'import.error.sql_source_both':
      return t('database.import.error.sqlSourceBoth')
    case 'import.error.sql_source_missing':
      return t('database.import.error.sqlSourceMissing')
    case 'import.error.sql_too_large':
      return t('database.import.error.sqlTooLarge')
    case 'import.error.sql_file_failed':
      return t('database.import.error.sqlFileFailed')
    case 'import.error.sql_multi_statement_unsupported':
      return t('database.import.error.sqlMultiStatementUnsupported')
    case 'import.error.sql_failed':
      return t('database.import.error.sqlFailed')
    case 'import.validation.missing_file':
      return t('database.import.error.missingFile')
    case 'import.validation.file_too_large':
      return t('database.import.error.fileTooLarge')
    case 'import.validation.invalid_options':
      return t('database.import.error.invalidOptions')
    case 'import.validation.unsupported_format':
      return t('database.import.error.unsupportedFormat')
    case 'import.validation.ambiguous_delimiter':
      return t('database.import.error.ambiguousDelimiter')
    case 'import.validation.invalid_delimiter':
      return t('database.import.error.invalidDelimiter')
    case 'import.validation.parse_failed':
      return t('database.import.error.parseFailed')
    case 'import.validation.no_columns':
      return t('database.import.error.noColumns')
    case 'import.validation.row_too_many_columns':
      return t('database.import.error.rowTooManyColumns')
    case 'import.validation.row_limit_exceeded':
      return t('database.import.error.rowLimitExceeded')
    case 'import.validation.duplicate_header':
      return t('database.import.error.duplicateHeader')
    case 'import.validation.empty_header':
      return t('database.import.error.emptyHeader')
    case 'import.validation.column_count_mismatch':
      return t('database.import.error.columnCountMismatch')
    case 'import.validation.column_count_insertable':
      return t('database.import.error.columnCountInsertable')
    case 'import.validation.column_unknown':
      return t('database.import.error.columnUnknown')
    case 'import.validation.column_generated':
      return t('database.import.error.columnGenerated')
    case 'import.validation.column_auto_generated':
      return t('database.import.error.columnAutoGenerated')
    case 'import.validation.mapping_invalid':
      return t('database.import.error.mappingInvalid')
    case 'import.validation.auto_generated_requires_toggle':
      return t('database.import.error.autoGeneratedRequiresToggle')
    case 'import.validation.target_mode_invalid':
      return t('database.import.error.targetModeInvalid')
    case 'import.validation.table_name_empty':
      return t('database.import.error.tableNameEmpty')
    case 'import.validation.table_exists':
      return t('database.import.error.tableExists')
    case 'import.validation.column_name_empty':
      return t('database.import.error.columnNameEmpty')
    case 'import.validation.column_duplicate':
      return t('database.import.error.columnDuplicate')
    case 'import.validation.column_type_invalid':
      return t('database.import.error.columnTypeInvalid')
    case 'import.validation.all_columns_skipped':
      return t('database.import.error.allColumnsSkipped')
    case 'import.validation.primary_skipped':
      return t('database.import.error.primarySkipped')
    case 'import.validation.primary_nullable':
      return t('database.import.error.primaryNullable')
    case 'import.error.no_rows':
      return t('database.import.error.noRows')
    case 'import.error.table_columns':
      return t('database.import.error.tableColumns')
    case 'import.error.import_failed':
      return t('database.import.error.importFailed')
    case 'import.error.clear_failed':
      return t('database.import.error.clearFailed')
    case 'import.error.insert_failed':
      return t('database.import.error.insertFailed')
    case 'import.error.upsert_no_pk':
      return t('database.import.error.upsertNoPrimaryKey')
    case 'import.error.upsert_not_supported':
      return t('database.import.error.upsertNotSupported')
    default:
      return t(tableFile ? 'database.import.table.failedMessage' : 'database.import.failedMessage')
  }
}

function getNewTableValidationError(tableName: string, columns: ImportNewTableColumnInput[]): string | null {
  if (!tableName.trim()) return 'import.validation.table_name_empty'
  if (columns.length === 0) return 'import.validation.mapping_invalid'

  const seenTargets = new Set<string>()
  let includedCount = 0

  for (const column of columns) {
    if (column.Skip) {
      if (column.Primary) return 'import.validation.primary_skipped'
      continue
    }

    includedCount += 1
    const targetColumn = column.TargetColumn?.trim() ?? ''
    if (!targetColumn) return 'import.validation.column_name_empty'
    if (seenTargets.has(targetColumn)) return 'import.validation.column_duplicate'
    seenTargets.add(targetColumn)

    if (!column.Type?.trim()) return 'import.validation.column_type_invalid'
    if (column.Primary && column.Nullable) return 'import.validation.primary_nullable'
  }

  if (includedCount === 0) return 'import.validation.all_columns_skipped'
  return null
}

function canRunTableImport(
  tableTargetMode: TableTargetMode,
  tableName: string | null | undefined,
  tableSource: TableFileSource | null,
  tablePreview: TableImportPreview | null,
  allowAutoGenerated: boolean,
  newTableValidationError: string | null,
  metadataLoading: boolean,
  metadataFailed: boolean,
): boolean {
  if (!tableSource || !tablePreview) return false
  if (tablePreview.ValidationError) return false
  if (tableTargetMode === 'new') {
    if (!tablePreview.NewTable) return false
    if (metadataLoading || metadataFailed || newTableValidationError) return false
    return true
  }

  if (!tableName) return false
  if (!tablePreview.Mapping || tablePreview.Mapping.length === 0) return false
  if (tablePreview.RequiresAllowAutoGenerated && !allowAutoGenerated) return false
  return true
}

function DatabaseImportFooter() {
  const { t } = useI18n()
  const {
    method,
    tableTargetMode,
    source,
    result,
    executeImport,
    tableSource,
    tablePreview,
    allowAutoGenerated,
    newTableValidationError,
    metadataLoading,
    metadataFailed,
    previewLoading,
    tableName,
  } = useDatabaseImport()
  const { state } = useModalForm()
  const canRun = method === 'tableFile'
    ? canRunTableImport(
        tableTargetMode,
        tableName,
        tableSource,
        tablePreview,
        allowAutoGenerated,
        newTableValidationError,
        metadataLoading,
        metadataFailed,
      )
    : hasSqlScriptSource(source)

  if (result?.status) {
    return (
      <DialogFooter>
        <DialogClose asChild>
          <Button variant="outline">{t('common.actions.close')}</Button>
        </DialogClose>
      </DialogFooter>
    )
  }

  return (
    <DialogFooter>
      <DialogClose asChild>
        <Button type="button" variant="outline" disabled={state.isSubmitting}>
          {t('common.actions.cancel')}
        </Button>
      </DialogClose>
      <Button type="button" onClick={executeImport} disabled={!canRun || state.isSubmitting || previewLoading} className="gap-2">
        {state.isSubmitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}
        {state.isSubmitting ? t('database.import.running') : t('database.import.runImport')}
      </Button>
    </DialogFooter>
  )
}

export interface DatabaseImportModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  connectionId: string
  databaseName: string
  schema?: string | null
  tableName?: string | null
  onSuccess?: (context: { databaseName: string; schema?: string | null; tableName?: string | null }) => void
}

/** Shared Database Import modal for supported SQL import entry points. */
export function DatabaseImportModal({
  open,
  onOpenChange,
  connectionId,
  databaseName,
  schema,
  tableName,
  onSuccess,
}: DatabaseImportModalProps) {
  const { t } = useI18n()
  const description = formatImportTargetLabel(databaseName, schema, tableName)

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-4xl">
        <ModalForm.Provider meta={{ title: t('database.import.title'), description, icon: Database }}>
          <DatabaseImportProvider
            connectionId={connectionId}
            databaseName={databaseName}
            schema={schema}
            tableName={tableName}
            onSuccess={onSuccess}
          >
            <ModalForm.Header />
            <DatabaseImportFields />
            <ModalForm.Alert />
            <DatabaseImportFooter />
          </DatabaseImportProvider>
        </ModalForm.Provider>
      </DialogContent>
    </Dialog>
  )
}
