# GENERATED by sdk/tools/generate-core.mjs — DO NOT EDIT (manifest 4b84678f5fe7)

from __future__ import annotations

from typing import Any


class Request:
    """One prepared platform operation: document + variables."""

    def __init__(self, operation: str, document: str, variables: dict[str, Any]):
        self.operation = operation
        self.document = document
        self.variables = variables


ONTOLOGYENTITIES_DOCUMENT = "query OntologyEntities($projectId: ID!) { OntologyEntities(projectId: $projectId) { id projectId apiName displayName pluralDisplayName description primaryKey sourceId tableName schemaName storageMode provisioningStatus embeddingEnabled embeddingProperties status icon color createdAt updatedAt properties { id apiName displayName description columnName dataType arrayElementType isRequired visibility isSearchable isSortable isEditOnly sortOrder } links { id apiName targetOntologyApiName cardinality foreignKeyProperty targetForeignKeyProperty joinTable sourceColumnInJoinTable targetColumnInJoinTable displayName pluralDisplayName reverseDisplayName } } }"


def ontology_entities_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query OntologyEntities."""
    return Request("OntologyEntities", ONTOLOGYENTITIES_DOCUMENT, variables)


def ontology_entities_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologyEntities payload from a GraphQL data object."""
    return data.get("OntologyEntities")

ONTOLOGYENTITY_DOCUMENT = "query OntologyEntity($projectId: ID!, $id: ID!) { OntologyEntity(projectId: $projectId, id: $id) { id projectId apiName displayName pluralDisplayName description primaryKey sourceId tableName schemaName storageMode provisioningStatus embeddingEnabled embeddingProperties status icon color createdAt updatedAt properties { id apiName displayName description columnName dataType arrayElementType isRequired visibility isSearchable isSortable isEditOnly sortOrder } links { id apiName targetOntologyApiName cardinality foreignKeyProperty targetForeignKeyProperty joinTable sourceColumnInJoinTable targetColumnInJoinTable displayName pluralDisplayName reverseDisplayName } } }"


def ontology_entity_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query OntologyEntity."""
    return Request("OntologyEntity", ONTOLOGYENTITY_DOCUMENT, variables)


def ontology_entity_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologyEntity payload from a GraphQL data object."""
    return data.get("OntologyEntity")

ONTOLOGYDESCRIBE_DOCUMENT = "query OntologyDescribe($projectId: ID!, $input: OntologyDescribeInput!) { OntologyDescribe(projectId: $projectId, input: $input) { text entities { name displayName description primaryKey fields { name displayName description type required searchable sortable } } relationships { name source sourceField target targetField cardinality kind } } }"


def ontology_describe_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query OntologyDescribe."""
    return Request("OntologyDescribe", ONTOLOGYDESCRIBE_DOCUMENT, variables)


def ontology_describe_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologyDescribe payload from a GraphQL data object."""
    return data.get("OntologyDescribe")

ONTOLOGYROWS_DOCUMENT = "query OntologyRows($projectId: ID!, $id: ID!, $pageSize: Int!, $pageOffset: Int!) { OntologyRows(projectId: $projectId, id: $id, pageSize: $pageSize, pageOffset: $pageOffset) { columns rows total } }"


def ontology_rows_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query OntologyRows."""
    return Request("OntologyRows", ONTOLOGYROWS_DOCUMENT, variables)


def ontology_rows_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologyRows payload from a GraphQL data object."""
    return data.get("OntologyRows")

ONTOLOGYQUERY_DOCUMENT = "query OntologyQuery($projectId: ID!, $input: OntologyQueryInput!) { OntologyQuery(projectId: $projectId, input: $input) { columns rows total } }"


def ontology_query_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query OntologyQuery."""
    return Request("OntologyQuery", ONTOLOGYQUERY_DOCUMENT, variables)


def ontology_query_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologyQuery payload from a GraphQL data object."""
    return data.get("OntologyQuery")

ONTOLOGYAGGREGATE_DOCUMENT = "query OntologyAggregate($projectId: ID!, $id: ID!, $groupBy: [String!]!, $metrics: [OntologyAggregateMetricInput!]!, $where: WhereCondition, $sort: [SortCondition!], $pageSize: Int!, $pageOffset: Int!) { OntologyAggregate(projectId: $projectId, id: $id, groupBy: $groupBy, metrics: $metrics, where: $where, sort: $sort, pageSize: $pageSize, pageOffset: $pageOffset) { columns rows total } }"


def ontology_aggregate_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query OntologyAggregate."""
    return Request("OntologyAggregate", ONTOLOGYAGGREGATE_DOCUMENT, variables)


def ontology_aggregate_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologyAggregate payload from a GraphQL data object."""
    return data.get("OntologyAggregate")

ONTOLOGYSTATS_DOCUMENT = "query OntologyStats($projectId: ID!, $id: ID!, $property: String!, $where: WhereCondition) { OntologyStats(projectId: $projectId, id: $id, property: $property, where: $where) { property min max total nonNull } }"


def ontology_stats_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query OntologyStats."""
    return Request("OntologyStats", ONTOLOGYSTATS_DOCUMENT, variables)


def ontology_stats_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologyStats payload from a GraphQL data object."""
    return data.get("OntologyStats")

ONTOLOGYSIMILAR_DOCUMENT = "query OntologySimilar($projectId: ID!, $input: OntologySimilarInput!) { OntologySimilar(projectId: $projectId, input: $input) { rows { score values { key value } } } }"


def ontology_similar_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query OntologySimilar."""
    return Request("OntologySimilar", ONTOLOGYSIMILAR_DOCUMENT, variables)


def ontology_similar_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologySimilar payload from a GraphQL data object."""
    return data.get("OntologySimilar")

ONTOLOGYFOLLOWLINK_DOCUMENT = "query OntologyFollowLink($projectId: ID!, $entityId: ID!, $pk: String!, $linkApiName: String!, $pageSize: Int!, $pageOffset: Int!) { OntologyFollowLink(projectId: $projectId, entityId: $entityId, pk: $pk, linkApiName: $linkApiName, pageSize: $pageSize, pageOffset: $pageOffset) { columns rows total } }"


def ontology_follow_link_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query OntologyFollowLink."""
    return Request("OntologyFollowLink", ONTOLOGYFOLLOWLINK_DOCUMENT, variables)


def ontology_follow_link_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologyFollowLink payload from a GraphQL data object."""
    return data.get("OntologyFollowLink")

ONTOLOGYFOLLOWINCOMINGLINK_DOCUMENT = "query OntologyFollowIncomingLink($projectId: ID!, $entityId: ID!, $pk: String!, $sourceEntityId: ID!, $linkApiName: String!, $pageSize: Int!, $pageOffset: Int!) { OntologyFollowIncomingLink(projectId: $projectId, entityId: $entityId, pk: $pk, sourceEntityId: $sourceEntityId, linkApiName: $linkApiName, pageSize: $pageSize, pageOffset: $pageOffset) { columns rows total } }"


def ontology_follow_incoming_link_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query OntologyFollowIncomingLink."""
    return Request("OntologyFollowIncomingLink", ONTOLOGYFOLLOWINCOMINGLINK_DOCUMENT, variables)


def ontology_follow_incoming_link_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologyFollowIncomingLink payload from a GraphQL data object."""
    return data.get("OntologyFollowIncomingLink")

ONTOLOGYFASTLOOKUPS_DOCUMENT = "query OntologyFastLookups($projectId: ID!, $entityId: ID!) { OntologyFastLookups(projectId: $projectId, entityId: $entityId) { id entityId displayName fields status reason createdAt updatedAt } }"


def ontology_fast_lookups_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query OntologyFastLookups."""
    return Request("OntologyFastLookups", ONTOLOGYFASTLOOKUPS_DOCUMENT, variables)


def ontology_fast_lookups_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologyFastLookups payload from a GraphQL data object."""
    return data.get("OntologyFastLookups")

ONTOLOGYADDROW_DOCUMENT = "mutation OntologyAddRow($projectId: ID!, $entityId: ID!, $values: [RecordInput!]!) { OntologyAddRow(projectId: $projectId, entityId: $entityId, values: $values) { Status } }"


def ontology_add_row_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Mutation OntologyAddRow."""
    return Request("OntologyAddRow", ONTOLOGYADDROW_DOCUMENT, variables)


def ontology_add_row_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologyAddRow payload from a GraphQL data object."""
    return data.get("OntologyAddRow")

ONTOLOGYADDROWS_DOCUMENT = "mutation OntologyAddRows($projectId: ID!, $entityId: ID!, $rows: [OntologyCreateRowInput!]!, $idempotencyKey: String) { OntologyAddRows(projectId: $projectId, entityId: $entityId, rows: $rows, idempotencyKey: $idempotencyKey) { inserted ids } }"


def ontology_add_rows_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Mutation OntologyAddRows."""
    return Request("OntologyAddRows", ONTOLOGYADDROWS_DOCUMENT, variables)


def ontology_add_rows_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologyAddRows payload from a GraphQL data object."""
    return data.get("OntologyAddRows")

ONTOLOGYUPDATEROW_DOCUMENT = "mutation OntologyUpdateRow($projectId: ID!, $entityId: ID!, $values: [RecordInput!]!, $updatedColumns: [String!]!) { OntologyUpdateRow(projectId: $projectId, entityId: $entityId, values: $values, updatedColumns: $updatedColumns) { Status } }"


def ontology_update_row_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Mutation OntologyUpdateRow."""
    return Request("OntologyUpdateRow", ONTOLOGYUPDATEROW_DOCUMENT, variables)


def ontology_update_row_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologyUpdateRow payload from a GraphQL data object."""
    return data.get("OntologyUpdateRow")

ONTOLOGYDELETEROW_DOCUMENT = "mutation OntologyDeleteRow($projectId: ID!, $entityId: ID!, $values: [RecordInput!]!) { OntologyDeleteRow(projectId: $projectId, entityId: $entityId, values: $values) { Status } }"


def ontology_delete_row_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Mutation OntologyDeleteRow."""
    return Request("OntologyDeleteRow", ONTOLOGYDELETEROW_DOCUMENT, variables)


def ontology_delete_row_parse(data: dict[str, Any]) -> Any:
    """Extract the OntologyDeleteRow payload from a GraphQL data object."""
    return data.get("OntologyDeleteRow")

PROJECTDATASETS_DOCUMENT = "query ProjectDatasets($projectId: ID!) { ProjectDatasets(projectId: $projectId) { id projectId sourceId name description schema { name type isNullable isPrimary } schemaMode ownerId rowCount sizeBytes createdAt updatedAt } }"


def project_datasets_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query ProjectDatasets."""
    return Request("ProjectDatasets", PROJECTDATASETS_DOCUMENT, variables)


def project_datasets_parse(data: dict[str, Any]) -> Any:
    """Extract the ProjectDatasets payload from a GraphQL data object."""
    return data.get("ProjectDatasets")

QUERYDATASET_DOCUMENT = "query QueryDataset($input: QueryDatasetInput!) { QueryDataset(input: $input) { columns rows total } }"


def query_dataset_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query QueryDataset."""
    return Request("QueryDataset", QUERYDATASET_DOCUMENT, variables)


def query_dataset_parse(data: dict[str, Any]) -> Any:
    """Extract the QueryDataset payload from a GraphQL data object."""
    return data.get("QueryDataset")

PROJECTSOURCES_DOCUMENT = "query ProjectSources($projectId: ID!) { ProjectSources(projectId: $projectId) { id projectId name databaseType createdBy createdAt ingestionStatus lastEventAt ingestionError eventsReceived } }"


def project_sources_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query ProjectSources."""
    return Request("ProjectSources", PROJECTSOURCES_DOCUMENT, variables)


def project_sources_parse(data: dict[str, Any]) -> Any:
    """Extract the ProjectSources payload from a GraphQL data object."""
    return data.get("ProjectSources")

PLATFORMSOURCEROWS_DOCUMENT = "query PlatformSourceRows($projectId: ID!, $sourceId: ID!, $ref: SourceObjectRefInput!, $where: WhereCondition, $sort: [SortCondition!], $pageSize: Int!, $pageOffset: Int!) { PlatformSourceRows(projectId: $projectId, sourceId: $sourceId, ref: $ref, where: $where, sort: $sort, pageSize: $pageSize, pageOffset: $pageOffset) { Columns { Type Name MetadataFidelity IsPrimary IsForeignKey ReferencedTable ReferencedColumn Length Precision Scale } Rows DisableUpdate TotalCount } }"


def platform_source_rows_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query PlatformSourceRows."""
    return Request("PlatformSourceRows", PLATFORMSOURCEROWS_DOCUMENT, variables)


def platform_source_rows_parse(data: dict[str, Any]) -> Any:
    """Extract the PlatformSourceRows payload from a GraphQL data object."""
    return data.get("PlatformSourceRows")

PLATFORMSOURCEOBJECTS_DOCUMENT = "query PlatformSourceObjects($projectId: ID!, $sourceId: ID!, $parent: SourceObjectRefInput, $kinds: [SourceObjectKind!], $pageSize: Int, $pageOffset: Int) { PlatformSourceObjects(projectId: $projectId, sourceId: $sourceId, parent: $parent, kinds: $kinds, pageSize: $pageSize, pageOffset: $pageOffset) { Ref { Kind Locator Path } Kind Name Path HasChildren Actions Metadata { Key Value } } }"


def platform_source_objects_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query PlatformSourceObjects."""
    return Request("PlatformSourceObjects", PLATFORMSOURCEOBJECTS_DOCUMENT, variables)


def platform_source_objects_parse(data: dict[str, Any]) -> Any:
    """Extract the PlatformSourceObjects payload from a GraphQL data object."""
    return data.get("PlatformSourceObjects")

PLATFORMSOURCECOLUMNS_DOCUMENT = "query PlatformSourceColumns($projectId: ID!, $sourceId: ID!, $ref: SourceObjectRefInput!) { PlatformSourceColumns(projectId: $projectId, sourceId: $sourceId, ref: $ref) { Type Name MetadataFidelity IsPrimary IsForeignKey ReferencedTable ReferencedColumn Length Precision Scale } }"


def platform_source_columns_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query PlatformSourceColumns."""
    return Request("PlatformSourceColumns", PLATFORMSOURCECOLUMNS_DOCUMENT, variables)


def platform_source_columns_parse(data: dict[str, Any]) -> Any:
    """Extract the PlatformSourceColumns payload from a GraphQL data object."""
    return data.get("PlatformSourceColumns")

MYORGANIZATIONS_DOCUMENT = "query MyOrganizations { MyOrganizations { id name slug createdAt } }"


def my_organizations_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query MyOrganizations."""
    return Request("MyOrganizations", MYORGANIZATIONS_DOCUMENT, variables)


def my_organizations_parse(data: dict[str, Any]) -> Any:
    """Extract the MyOrganizations payload from a GraphQL data object."""
    return data.get("MyOrganizations")

PROJECTS_DOCUMENT = "query Projects($orgId: ID!) { Projects(orgId: $orgId) { id orgId name slug description createdAt } }"


def projects_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query Projects."""
    return Request("Projects", PROJECTS_DOCUMENT, variables)


def projects_parse(data: dict[str, Any]) -> Any:
    """Extract the Projects payload from a GraphQL data object."""
    return data.get("Projects")

MYWORKSPACE_DOCUMENT = "query MyWorkspace { MyWorkspace { orgId projectId } }"


def my_workspace_request(variables: dict[str, Any]) -> Request:
    """Build the wire request for Query MyWorkspace."""
    return Request("MyWorkspace", MYWORKSPACE_DOCUMENT, variables)


def my_workspace_parse(data: dict[str, Any]) -> Any:
    """Extract the MyWorkspace payload from a GraphQL data object."""
    return data.get("MyWorkspace")
