# GENERATED by sdk/tools/generate-core.mjs — DO NOT EDIT (manifest 4b84678f5fe7)

from __future__ import annotations

from typing import Any, Optional, TypedDict

#: GraphQL type AtomicWhereCondition.
AtomicWhereCondition = TypedDict(
    "AtomicWhereCondition",
    {
        "ColumnType": str,
        "Key": str,
        "Operator": str,
        "Value": str,
    },
    total=False,
)

#: GraphQL type Column.
Column = TypedDict(
    "Column",
    {
        "Type": str,
        "Name": str,
        "MetadataFidelity": str,
        "IsPrimary": bool,
        "IsForeignKey": bool,
        "ReferencedTable": Optional[str],
        "ReferencedColumn": Optional[str],
        "Length": Optional[int],
        "Precision": Optional[int],
        "Scale": Optional[int],
    },
    total=False,
)

#: GraphQL type ColumnDef.
ColumnDef = TypedDict(
    "ColumnDef",
    {
        "name": str,
        "type": str,
        "isNullable": bool,
        "isPrimary": bool,
    },
    total=False,
)

#: GraphQL type Dataset.
Dataset = TypedDict(
    "Dataset",
    {
        "id": str,
        "projectId": str,
        "sourceId": str,
        "name": str,
        "description": str,
        "schema": list["ColumnDef"],
        "schemaMode": str,
        "ownerId": str,
        "rowCount": int,
        "sizeBytes": int,
        "createdAt": str,
        "updatedAt": str,
    },
    total=False,
)

#: GraphQL type DatasetQueryResult.
DatasetQueryResult = TypedDict(
    "DatasetQueryResult",
    {
        "columns": list[str],
        "rows": list[list[str]],
        "total": int,
    },
    total=False,
)

#: GraphQL type OntologyAddRowsResult.
OntologyAddRowsResult = TypedDict(
    "OntologyAddRowsResult",
    {
        "inserted": int,
        "ids": list[str],
    },
    total=False,
)

#: GraphQL type OntologyAggregateMetricInput.
OntologyAggregateMetricInput = TypedDict(
    "OntologyAggregateMetricInput",
    {
        "field": Optional[str],
        "op": str,
        "as": Optional[str],
    },
    total=False,
)

#: GraphQL type OntologyCreateRowInput.
OntologyCreateRowInput = TypedDict(
    "OntologyCreateRowInput",
    {
        "values": list["RecordInput"],
    },
    total=False,
)

OntologyDataType = str  # enum: String | Integer | Long | Double | Float | Boolean | Date | Timestamp | Array | Struct | UUID

#: GraphQL type OntologyDescribeInput.
OntologyDescribeInput = TypedDict(
    "OntologyDescribeInput",
    {
        "entities": list[str],
        "includeInferred": bool,
    },
    total=False,
)

#: GraphQL type OntologyDescription.
OntologyDescription = TypedDict(
    "OntologyDescription",
    {
        "text": str,
        "entities": list["OntologyDescriptionEntity"],
        "relationships": list["OntologyDescriptionRelationship"],
    },
    total=False,
)

#: GraphQL type OntologyDescriptionEntity.
OntologyDescriptionEntity = TypedDict(
    "OntologyDescriptionEntity",
    {
        "name": str,
        "displayName": str,
        "description": str,
        "primaryKey": str,
        "fields": list["OntologyDescriptionField"],
    },
    total=False,
)

#: GraphQL type OntologyDescriptionField.
OntologyDescriptionField = TypedDict(
    "OntologyDescriptionField",
    {
        "name": str,
        "displayName": str,
        "description": str,
        "type": str,
        "required": bool,
        "searchable": bool,
        "sortable": bool,
    },
    total=False,
)

#: GraphQL type OntologyDescriptionRelationship.
OntologyDescriptionRelationship = TypedDict(
    "OntologyDescriptionRelationship",
    {
        "name": str,
        "source": str,
        "sourceField": str,
        "target": str,
        "targetField": str,
        "cardinality": str,
        "kind": str,
    },
    total=False,
)

#: GraphQL type OntologyFastLookup.
OntologyFastLookup = TypedDict(
    "OntologyFastLookup",
    {
        "id": str,
        "entityId": str,
        "displayName": str,
        "fields": list[str],
        "status": str,
        "reason": str,
        "createdAt": str,
        "updatedAt": str,
    },
    total=False,
)

#: GraphQL type OntologyLink.
OntologyLink = TypedDict(
    "OntologyLink",
    {
        "id": str,
        "apiName": str,
        "targetOntologyApiName": str,
        "cardinality": str,
        "foreignKeyProperty": str,
        "targetForeignKeyProperty": str,
        "joinTable": str,
        "sourceColumnInJoinTable": str,
        "targetColumnInJoinTable": str,
        "displayName": str,
        "pluralDisplayName": str,
        "reverseDisplayName": str,
    },
    total=False,
)

OntologyLinkCardinality = str  # enum: ONE_TO_ONE | ONE_TO_MANY | MANY_TO_ONE | MANY_TO_MANY

#: GraphQL type OntologyObjectType.
OntologyObjectType = TypedDict(
    "OntologyObjectType",
    {
        "id": str,
        "projectId": str,
        "apiName": str,
        "displayName": str,
        "pluralDisplayName": str,
        "description": str,
        "primaryKey": str,
        "sourceId": Optional[str],
        "tableName": str,
        "schemaName": str,
        "storageMode": str,
        "provisioningStatus": str,
        "embeddingEnabled": bool,
        "embeddingProperties": list[str],
        "status": str,
        "icon": str,
        "color": str,
        "createdAt": str,
        "updatedAt": str,
        "properties": list["OntologyProperty"],
        "links": list["OntologyLink"],
    },
    total=False,
)

#: GraphQL type OntologyProperty.
OntologyProperty = TypedDict(
    "OntologyProperty",
    {
        "id": str,
        "apiName": str,
        "displayName": str,
        "description": str,
        "columnName": str,
        "dataType": str,
        "arrayElementType": str,
        "isRequired": bool,
        "visibility": str,
        "isSearchable": bool,
        "isSortable": bool,
        "isEditOnly": bool,
        "sortOrder": int,
    },
    total=False,
)

OntologyProvisioningStatus = str  # enum: provisioning | ready | failed

#: GraphQL type OntologyQueryInput.
OntologyQueryInput = TypedDict(
    "OntologyQueryInput",
    {
        "entity": str,
        "whereJson": Optional[str],
        "search": Optional[str],
        "searchFields": Optional[list[str]],
        "joins": Optional[list["OntologyQueryJoinInput"]],
        "groupBy": Optional[list[str]],
        "metrics": Optional[list["OntologyQueryMetricInput"]],
        "sort": Optional[list["OntologyQuerySortInput"]],
        "pageSize": Optional[int],
        "offset": Optional[int],
        "scanLimit": Optional[int],
    },
    total=False,
)

#: GraphQL type OntologyQueryJoinInput.
OntologyQueryJoinInput = TypedDict(
    "OntologyQueryJoinInput",
    {
        "entity": str,
        "leftField": str,
        "rightField": str,
        "as": Optional[str],
        "kind": Optional[str],
    },
    total=False,
)

#: GraphQL type OntologyQueryMetricInput.
OntologyQueryMetricInput = TypedDict(
    "OntologyQueryMetricInput",
    {
        "op": str,
        "field": Optional[str],
        "as": Optional[str],
    },
    total=False,
)

#: GraphQL type OntologyQuerySortInput.
OntologyQuerySortInput = TypedDict(
    "OntologyQuerySortInput",
    {
        "field": str,
        "desc": Optional[bool],
    },
    total=False,
)

#: GraphQL type OntologySimilarInput.
OntologySimilarInput = TypedDict(
    "OntologySimilarInput",
    {
        "entityId": str,
        "rowId": str,
        "topK": int,
        "properties": Optional[list[str]],
        "where": Optional["WhereCondition"],
    },
    total=False,
)

#: GraphQL type OntologySimilarityResult.
OntologySimilarityResult = TypedDict(
    "OntologySimilarityResult",
    {
        "rows": list["OntologySimilarityRow"],
    },
    total=False,
)

#: GraphQL type OntologySimilarityRow.
OntologySimilarityRow = TypedDict(
    "OntologySimilarityRow",
    {
        "score": float,
        "values": list["OntologySimilarityValue"],
    },
    total=False,
)

#: GraphQL type OntologySimilarityValue.
OntologySimilarityValue = TypedDict(
    "OntologySimilarityValue",
    {
        "key": str,
        "value": str,
    },
    total=False,
)

#: GraphQL type OntologyStatsResult.
OntologyStatsResult = TypedDict(
    "OntologyStatsResult",
    {
        "property": str,
        "min": Optional[str],
        "max": Optional[str],
        "total": int,
        "nonNull": int,
    },
    total=False,
)

OntologyStatus = str  # enum: active | experimental | deprecated

OntologyStorageMode = str  # enum: operational | analytical

OntologyVisibility = str  # enum: prominent | normal | hidden

#: GraphQL type OperationWhereCondition.
OperationWhereCondition = TypedDict(
    "OperationWhereCondition",
    {
        "Children": list["WhereCondition"],
    },
    total=False,
)

#: GraphQL type Organization.
Organization = TypedDict(
    "Organization",
    {
        "id": str,
        "name": str,
        "slug": str,
        "createdAt": str,
    },
    total=False,
)

#: GraphQL type PlatformSource.
PlatformSource = TypedDict(
    "PlatformSource",
    {
        "id": str,
        "projectId": str,
        "name": str,
        "databaseType": str,
        "createdBy": str,
        "createdAt": str,
        "ingestionStatus": str,
        "lastEventAt": Optional[str],
        "ingestionError": str,
        "eventsReceived": str,
    },
    total=False,
)

#: GraphQL type Project.
Project = TypedDict(
    "Project",
    {
        "id": str,
        "orgId": str,
        "name": str,
        "slug": str,
        "description": str,
        "createdAt": str,
    },
    total=False,
)

#: GraphQL type QueryDatasetInput.
QueryDatasetInput = TypedDict(
    "QueryDatasetInput",
    {
        "projectId": str,
        "datasetId": str,
        "pageSize": int,
        "pageOffset": int,
    },
    total=False,
)

#: GraphQL type Record.
Record = TypedDict(
    "Record",
    {
        "Key": str,
        "Value": str,
    },
    total=False,
)

#: GraphQL type RecordInput.
RecordInput = TypedDict(
    "RecordInput",
    {
        "Key": str,
        "Value": str,
        "Extra": Optional[list["RecordInput"]],
    },
    total=False,
)

#: GraphQL type RowsResult.
RowsResult = TypedDict(
    "RowsResult",
    {
        "Columns": list["Column"],
        "Rows": list[list[str]],
        "DisableUpdate": bool,
        "TotalCount": int,
    },
    total=False,
)

#: GraphQL type SortCondition.
SortCondition = TypedDict(
    "SortCondition",
    {
        "Column": str,
        "Direction": str,
    },
    total=False,
)

SortDirection = str  # enum: ASC | DESC

SourceAction = str  # enum: Browse | Inspect | ViewRows | ViewContent | ViewDefinition | CreateChild | Delete | InsertData | UpdateData | DeleteData | ImportData | GenerateMockData | Execute | ViewGraph

SourceMetadataFidelity = str  # enum: Exact | Driver | Sampled | Inferred | Synthetic | Unsupported | Unknown

#: GraphQL type SourceObject.
SourceObject = TypedDict(
    "SourceObject",
    {
        "Ref": "SourceObjectRef",
        "Kind": str,
        "Name": str,
        "Path": list[str],
        "HasChildren": bool,
        "Actions": list[str],
        "Metadata": list["Record"],
    },
    total=False,
)

SourceObjectKind = str  # enum: Database | Schema | Table | View | Collection | Index | Key | Item | Function | Procedure | Trigger | Sequence

#: GraphQL type SourceObjectRef.
SourceObjectRef = TypedDict(
    "SourceObjectRef",
    {
        "Kind": str,
        "Locator": str,
        "Path": list[str],
    },
    total=False,
)

#: GraphQL type SourceObjectRefInput.
SourceObjectRefInput = TypedDict(
    "SourceObjectRefInput",
    {
        "Kind": str,
        "Locator": Optional[str],
        "Path": list[str],
    },
    total=False,
)

#: GraphQL type StatusResponse.
StatusResponse = TypedDict(
    "StatusResponse",
    {
        "Status": bool,
    },
    total=False,
)

#: GraphQL type WhereCondition.
WhereCondition = TypedDict(
    "WhereCondition",
    {
        "Type": str,
        "Atomic": Optional["AtomicWhereCondition"],
        "And": Optional["OperationWhereCondition"],
        "Or": Optional["OperationWhereCondition"],
    },
    total=False,
)

WhereConditionType = str  # enum: Atomic | And | Or

#: GraphQL type Workspace.
Workspace = TypedDict(
    "Workspace",
    {
        "orgId": Optional[str],
        "projectId": Optional[str],
    },
    total=False,
)

