// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/clidey/whodb/core/baml_client/types"
)

func GenerateChatTitle(ctx context.Context, user_query string, opts ...CallOptionFunc) (string, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"user_query": user_query},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "GenerateChatTitle", encoded, callOpts.onTick)
		if err != nil {
			return "", err
		}

		if result.Error != nil {
			return "", result.Error
		}

		casted := (result.Data).(string)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateChatTitle", encoded, callOpts.onTick)
		if err != nil {
			return "", err
		}

		for result := range channel {
			if result.Error != nil {
				return "", result.Error
			}

			if result.HasData {
				return result.Data.(string), nil
			}
		}

		return "", fmt.Errorf("No data returned from stream")
	}
}

func GenerateSQLQuery(ctx context.Context, context types.DatabaseContext, user_query string, opts ...CallOptionFunc) ([]types.ChatResponse, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"context": context, "user_query": user_query},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "GenerateSQLQuery", encoded, callOpts.onTick)
		if err != nil {
			return nil, err
		}

		if result.Error != nil {
			return nil, result.Error
		}

		casted := (result.Data).([]types.ChatResponse)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateSQLQuery", encoded, callOpts.onTick)
		if err != nil {
			return nil, err
		}

		for result := range channel {
			if result.Error != nil {
				return nil, result.Error
			}

			if result.HasData {
				return result.Data.([]types.ChatResponse), nil
			}
		}

		return nil, fmt.Errorf("No data returned from stream")
	}
}
