// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/clidey/whodb/core/baml_client/stream_types"
	"github.com/clidey/whodb/core/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.AgentAction":            reflect.TypeOf(types.AgentAction{}),
	"STREAM_TYPES.AgentAction":     reflect.TypeOf(stream_types.AgentAction{}),
	"TYPES.ChatResponse":           reflect.TypeOf(types.ChatResponse{}),
	"STREAM_TYPES.ChatResponse":    reflect.TypeOf(stream_types.ChatResponse{}),
	"TYPES.DatabaseContext":        reflect.TypeOf(types.DatabaseContext{}),
	"STREAM_TYPES.DatabaseContext": reflect.TypeOf(stream_types.DatabaseContext{}),

	"TYPES.AgentActionType": reflect.TypeOf(types.AgentActionType("")),
	"TYPES.ChatMessageType": reflect.TypeOf(types.ChatMessageType("")),
	"TYPES.OperationType":   reflect.TypeOf(types.OperationType("")),
}
