// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/clidey/whodb/core/baml_client/stream_types"
	"github.com/clidey/whodb/core/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.ChatResponse":           reflect.TypeFor[types.ChatResponse](),
	"STREAM_TYPES.ChatResponse":    reflect.TypeFor[stream_types.ChatResponse](),
	"TYPES.DatabaseContext":        reflect.TypeFor[types.DatabaseContext](),
	"STREAM_TYPES.DatabaseContext": reflect.TypeFor[stream_types.DatabaseContext](),

	"TYPES.ChatMessageType": reflect.TypeFor[types.ChatMessageType](),
	"TYPES.OperationType":   reflect.TypeFor[types.OperationType](),
}
