import { describe, expect, it } from 'vitest'

import {
  buildImportTableFileInput,
  buildImportSqlInput,
  buildTableFileOptions,
  getTableFileFormat,
  hasSqlScriptSource,
  isAcceptedSqlFile,
  isAcceptedTableFile,
} from '@/components/database/import/sql-import-utils'
import { ImportFileFormat, ImportMode } from '@graphql'

describe('SQL import source utilities', () => {
  it('accepts only .sql file names', () => {
    expect(isAcceptedSqlFile(new File(['SELECT 1;'], 'seed.sql'))).toBe(true)
    expect(isAcceptedSqlFile(new File(['SELECT 1;'], 'seed.SQL'))).toBe(true)
    expect(isAcceptedSqlFile(new File(['id,name'], 'seed.csv'))).toBe(false)
  })

  it('builds file upload input without adding script text', () => {
    const file = new File(['SELECT 1;'], 'seed.sql')

    expect(buildImportSqlInput({ kind: 'file', file, filename: file.name, preview: 'SELECT 1;' })).toEqual({
      File: file,
      Filename: 'seed.sql',
    })
  })

  it('builds script input after converting to editable text', () => {
    expect(buildImportSqlInput({ kind: 'text', script: 'SELECT 1;' })).toEqual({
      Script: 'SELECT 1;',
    })
  })

  it('treats blank sources as not executable', () => {
    expect(hasSqlScriptSource(null)).toBe(false)
    expect(hasSqlScriptSource({ kind: 'file', file: new File([''], 'empty.sql'), filename: 'empty.sql', preview: ' ' })).toBe(false)
    expect(hasSqlScriptSource({ kind: 'text', script: ' ' })).toBe(false)
    expect(hasSqlScriptSource({ kind: 'text', script: 'SELECT 1;' })).toBe(true)
  })

  it('detects supported table file formats', () => {
    expect(getTableFileFormat('users.csv')).toBe(ImportFileFormat.Csv)
    expect(getTableFileFormat('users.XLS')).toBe(ImportFileFormat.Excel)
    expect(getTableFileFormat('users.xlsx')).toBe(ImportFileFormat.Excel)
    expect(getTableFileFormat('users.json')).toBeNull()
    expect(isAcceptedTableFile(new File(['id,name'], 'users.csv'))).toBe(true)
    expect(isAcceptedTableFile(new File(['{}'], 'users.json'))).toBe(false)
  })

  it('builds table file options from file format controls', () => {
    const csv = {
      kind: 'tableFile' as const,
      file: new File(['id,name'], 'users.csv'),
      filename: 'users.csv',
      format: ImportFileFormat.Csv,
    }
    const excel = {
      kind: 'tableFile' as const,
      file: new File([''], 'users.xlsx'),
      filename: 'users.xlsx',
      format: ImportFileFormat.Excel,
    }

    expect(buildTableFileOptions(csv, ';', 'Sheet2')).toEqual({
      Format: ImportFileFormat.Csv,
      Delimiter: ';',
    })
    expect(buildTableFileOptions(excel, ';', ' Sheet2 ')).toEqual({
      Format: ImportFileFormat.Excel,
      Sheet: 'Sheet2',
    })
  })

  it('builds existing-table import input with mapping and import mode', () => {
    const file = new File(['id,name\n1,Ada'], 'users.csv')
    const source = {
      kind: 'tableFile' as const,
      file,
      filename: file.name,
      format: ImportFileFormat.Csv,
    }

    expect(buildImportTableFileInput({
      source,
      schema: 'public',
      storageUnit: 'users',
      mode: ImportMode.Append,
      delimiter: ',',
      sheet: '',
      allowAutoGenerated: false,
      mapping: [
        { SourceColumn: 'id', TargetColumn: 'id', Skip: false },
        { SourceColumn: 'name', TargetColumn: 'name', Skip: false },
      ],
    })).toEqual({
      Schema: 'public',
      StorageUnit: 'users',
      Mode: ImportMode.Append,
      Options: {
        Format: ImportFileFormat.Csv,
        Delimiter: ',',
      },
      File: file,
      Mapping: [
        { SourceColumn: 'id', TargetColumn: 'id', Skip: false },
        { SourceColumn: 'name', TargetColumn: 'name', Skip: false },
      ],
      AllowAutoGenerated: false,
    })
  })
})
