/*
 * Copyright 2026 Clidey, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package importer exposes the shared data-import pipeline used by GraphQL and
// the CLI.
package importer

import (
	"bytes"
	"encoding/csv"
	"errors"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/clidey/whodb/core/src/engine"
	"github.com/clidey/whodb/core/src/plugins"
	"github.com/xuri/excelize/v2"
)

const (
	defaultMaxRows   = 100000
	defaultBatchSize = 1000
	// DefaultPreviewLimit is the default number of rows returned for file previews.
	DefaultPreviewLimit = 25
	// MaxFileSizeBytes is the maximum supported size for table import files.
	MaxFileSizeBytes = int64(50 * 1024 * 1024)

	importValidationGeneric               = "import.validation.generic"
	importValidationFileTooLarge          = "import.validation.file_too_large"
	importValidationInvalidOptions        = "import.validation.invalid_options"
	importValidationUnsupportedFormat     = "import.validation.unsupported_format"
	importValidationAmbiguousDelimiter    = "import.validation.ambiguous_delimiter"
	importValidationInvalidDelimiter      = "import.validation.invalid_delimiter"
	importValidationParseFailed           = "import.validation.parse_failed"
	importValidationNoColumns             = "import.validation.no_columns"
	importValidationRowTooManyColumns     = "import.validation.row_too_many_columns"
	importValidationRowLimitExceeded      = "import.validation.row_limit_exceeded"
	importValidationDuplicateHeader       = "import.validation.duplicate_header"
	importValidationEmptyHeader           = "import.validation.empty_header"
	importValidationColumnCountMismatch   = "import.validation.column_count_mismatch"
	importValidationColumnCountInsertable = "import.validation.column_count_insertable"
	importValidationUnknownColumn         = "import.validation.column_unknown"
	importValidationGeneratedColumn       = "import.validation.column_generated"
	importValidationAutoGeneratedColumn   = "import.validation.column_auto_generated"
	importValidationMappingInvalid        = "import.validation.mapping_invalid"
	importValidationAutoGeneratedToggle   = "import.validation.auto_generated_requires_toggle"

	importErrorNoRows             = "import.error.no_rows"
	importErrorTableColumns       = "import.error.table_columns"
	importErrorImportFailed       = "import.error.import_failed"
	importErrorClearFailed        = "import.error.clear_failed"
	importErrorInsertFailed       = "import.error.insert_failed"
	importErrorUpsertNoPK         = "import.error.upsert_no_pk"
	importErrorUpsertNotSupported = "import.error.upsert_not_supported"
)

// FileFormat identifies the supported structured file formats for table import.
type FileFormat string

const (
	// FileFormatCSV represents a delimited text file.
	FileFormatCSV FileFormat = "CSV"
	// FileFormatExcel represents an Excel workbook.
	FileFormatExcel FileFormat = "EXCEL"
)

// IsValid reports whether the file format is supported.
func (f FileFormat) IsValid() bool {
	switch f {
	case FileFormatCSV, FileFormatExcel:
		return true
	default:
		return false
	}
}

// Mode controls how imported rows should be applied to the target storage unit.
type Mode string

const (
	// ModeAppend inserts rows and skips duplicates when the database supports it.
	ModeAppend Mode = "APPEND"
	// ModeOverwrite clears existing rows before importing.
	ModeOverwrite Mode = "OVERWRITE"
	// ModeUpsert inserts new rows and updates existing rows by primary key.
	ModeUpsert Mode = "UPSERT"
)

// IsValid reports whether the import mode is supported.
func (m Mode) IsValid() bool {
	switch m {
	case ModeAppend, ModeOverwrite, ModeUpsert:
		return true
	default:
		return false
	}
}

// FileOptions configures how an input file should be parsed.
type FileOptions struct {
	Format    FileFormat
	Delimiter *string
	Sheet     *string
	HasHeader bool
}

// ParsedFile contains the normalized contents of an imported file.
type ParsedFile struct {
	Columns   []string
	Rows      [][]string
	Truncated bool
	Sheet     string
}

// ColumnMapping maps a source column from the input file to a target column in
// the destination storage unit.
type ColumnMapping struct {
	SourceColumn string
	TargetColumn *string
	Skip         bool
}

// ResolvedMapping stores the validated destination metadata for a source
// column mapping.
type ResolvedMapping struct {
	SourceIndex int
	TargetName  string
	TargetType  string
	IsNullable  bool
}

// ExecuteRequest describes a parsed import ready to be applied to a database.
type ExecuteRequest struct {
	Schema             string
	StorageUnit        string
	Mode               Mode
	Parsed             *ParsedFile
	Mapping            []ColumnMapping
	AllowAutoGenerated bool
	BatchSize          int
	TargetColumns      []engine.Column
}

// ExecuteResult summarizes a completed table import.
type ExecuteResult struct {
	RowsImported int
}

type importError struct {
	key   string
	cause error
}

func (err *importError) Error() string {
	return err.key
}

func (err *importError) Unwrap() error {
	return err.cause
}

func newImportError(key string, cause error) error {
	return &importError{key: key, cause: cause}
}

func isImportKey(value string) bool {
	return strings.HasPrefix(value, "import.validation.") || strings.HasPrefix(value, "import.error.")
}

// ErrorKeyFromError extracts an import localization key from an importer error.
func ErrorKeyFromError(err error) string {
	if err == nil {
		return ""
	}

	if typedErr, ok := errors.AsType[*importError](err); ok {
		return typedErr.key
	}

	if isImportKey(err.Error()) {
		return err.Error()
	}

	return ""
}

// FormatFromPath infers the file format from the file extension.
func FormatFromPath(path string) FileFormat {
	switch strings.ToLower(filepath.Ext(path)) {
	case ".xlsx", ".xls":
		return FileFormatExcel
	default:
		return FileFormatCSV
	}
}

// ReadFile reads a local import file with a size cap.
func ReadFile(path string, maxBytes int64) ([]byte, error) {
	if maxBytes <= 0 {
		maxBytes = MaxFileSizeBytes
	}

	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	info, err := file.Stat()
	if err == nil && info.Size() > maxBytes {
		return nil, newImportError(importValidationFileTooLarge, nil)
	}

	limited := io.LimitReader(file, maxBytes+1)
	data, err := io.ReadAll(limited)
	if err != nil {
		return nil, err
	}
	if int64(len(data)) > maxBytes {
		return nil, newImportError(importValidationFileTooLarge, nil)
	}

	return data, nil
}

// DetectCSVDelimiter detects a CSV delimiter from a sample of input data.
func DetectCSVDelimiter(data []byte) (string, error) {
	candidates := []rune{',', '\t', ';', '|'}
	valid := make([]string, 0, len(candidates))

	for _, candidate := range candidates {
		reader := csv.NewReader(bytes.NewReader(data))
		reader.Comma = candidate
		reader.FieldsPerRecord = -1

		records := 0
		expectedFields := -1
		consistent := true
		for records < 5 {
			row, err := reader.Read()
			if errors.Is(err, io.EOF) {
				break
			}
			if err != nil {
				consistent = false
				break
			}

			if len(row) == 0 || (len(row) == 1 && row[0] == "") {
				continue
			}

			fieldCount := len(row)
			if expectedFields == -1 {
				expectedFields = fieldCount
			} else if expectedFields != fieldCount {
				consistent = false
				break
			}
			records++
		}

		if !consistent || records == 0 || expectedFields <= 1 {
			continue
		}

		valid = append(valid, string(candidate))
	}

	if len(valid) == 0 {
		return ",", nil
	}
	if len(valid) > 1 {
		return "", newImportError(importValidationAmbiguousDelimiter, nil)
	}

	return valid[0], nil
}

// ParseFile parses a structured import file into normalized columns and rows.
func ParseFile(data []byte, options *FileOptions, maxRows int, enforceRowCap bool) (*ParsedFile, error) {
	if options == nil || !options.Format.IsValid() {
		return nil, newImportError(importValidationInvalidOptions, nil)
	}

	switch options.Format {
	case FileFormatCSV:
		return parseCSV(data, options, maxRows, enforceRowCap)
	case FileFormatExcel:
		return parseExcel(data, options, maxRows, enforceRowCap)
	default:
		return nil, newImportError(importValidationUnsupportedFormat, nil)
	}
}

// BuildDefaultMappings creates a default mapping plan from parsed source
// columns to target database columns.
func BuildDefaultMappings(
	sourceColumns []string,
	targetColumns []engine.Column,
	useHeaderMapping bool,
	allowAutoGenerated bool,
) ([]ColumnMapping, []string, error) {
	if len(sourceColumns) == 0 {
		return nil, nil, newImportError(importValidationNoColumns, nil)
	}

	if useHeaderMapping {
		targetByName := make(map[string]engine.Column, len(targetColumns))
		for _, column := range targetColumns {
			targetByName[column.Name] = column
		}

		mappings := make([]ColumnMapping, 0, len(sourceColumns))
		autoGeneratedColumns := make([]string, 0)
		for _, source := range sourceColumns {
			column, ok := targetByName[source]
			if !ok {
				return nil, nil, newImportError(importValidationUnknownColumn, nil)
			}
			if column.IsComputed {
				return nil, nil, newImportError(importValidationGeneratedColumn, nil)
			}
			if column.IsAutoIncrement {
				autoGeneratedColumns = append(autoGeneratedColumns, column.Name)
			}

			targetCopy := column.Name
			mappings = append(mappings, ColumnMapping{
				SourceColumn: source,
				TargetColumn: &targetCopy,
			})
		}

		if !allowAutoGenerated && len(autoGeneratedColumns) > 0 {
			return mappings, autoGeneratedColumns, newImportError(importValidationAutoGeneratedToggle, nil)
		}

		if _, err := ResolveMappings(sourceColumns, mappings, targetColumns, allowAutoGenerated); err != nil {
			return nil, autoGeneratedColumns, err
		}

		return mappings, autoGeneratedColumns, nil
	}

	insertable := make([]engine.Column, 0, len(targetColumns))
	autoGeneratedColumns := make([]string, 0)
	for _, column := range targetColumns {
		if column.IsComputed {
			continue
		}
		if column.IsAutoIncrement {
			autoGeneratedColumns = append(autoGeneratedColumns, column.Name)
			continue
		}
		insertable = append(insertable, column)
	}

	if len(sourceColumns) != len(insertable) {
		if len(autoGeneratedColumns) > 0 {
			sort.Strings(autoGeneratedColumns)
			return nil, autoGeneratedColumns, newImportError(importValidationColumnCountInsertable, nil)
		}

		return nil, nil, newImportError(importValidationColumnCountMismatch, nil)
	}

	mappings := make([]ColumnMapping, 0, len(sourceColumns))
	for idx, source := range sourceColumns {
		targetCopy := insertable[idx].Name
		mappings = append(mappings, ColumnMapping{
			SourceColumn: source,
			TargetColumn: &targetCopy,
		})
	}

	if _, err := ResolveMappings(sourceColumns, mappings, targetColumns, false); err != nil {
		return nil, nil, err
	}

	return mappings, nil, nil
}

// ResolveMappings validates an explicit mapping plan against the target table
// columns and returns the normalized metadata needed for insertion.
func ResolveMappings(
	sourceColumns []string,
	mappings []ColumnMapping,
	targetColumns []engine.Column,
	allowAutoGenerated bool,
) ([]ResolvedMapping, error) {
	if len(mappings) == 0 || len(mappings) != len(sourceColumns) {
		return nil, newImportError(importValidationMappingInvalid, nil)
	}

	sourceIndex := make(map[string]int, len(sourceColumns))
	for idx, column := range sourceColumns {
		if _, exists := sourceIndex[column]; exists {
			return nil, newImportError(importValidationMappingInvalid, nil)
		}
		sourceIndex[column] = idx
	}

	targetByName := make(map[string]engine.Column, len(targetColumns))
	for _, column := range targetColumns {
		targetByName[column.Name] = column
	}

	seenSources := make(map[string]struct{}, len(sourceColumns))
	seenTargets := make(map[string]struct{}, len(sourceColumns))
	resolved := make([]ResolvedMapping, 0, len(sourceColumns))
	mappedCount := 0

	for _, mapping := range mappings {
		if _, exists := sourceIndex[mapping.SourceColumn]; !exists {
			return nil, newImportError(importValidationMappingInvalid, nil)
		}
		if _, exists := seenSources[mapping.SourceColumn]; exists {
			return nil, newImportError(importValidationMappingInvalid, nil)
		}
		seenSources[mapping.SourceColumn] = struct{}{}

		targetName := ""
		if mapping.TargetColumn != nil {
			targetName = *mapping.TargetColumn
		}

		if mapping.Skip || targetName == "" {
			return nil, newImportError(importValidationMappingInvalid, nil)
		}
		if _, exists := seenTargets[targetName]; exists {
			return nil, newImportError(importValidationMappingInvalid, nil)
		}
		seenTargets[targetName] = struct{}{}

		column, exists := targetByName[targetName]
		if !exists {
			return nil, newImportError(importValidationUnknownColumn, nil)
		}
		if column.IsComputed {
			return nil, newImportError(importValidationGeneratedColumn, nil)
		}
		if column.IsAutoIncrement && !allowAutoGenerated {
			return nil, newImportError(importValidationAutoGeneratedColumn, nil)
		}

		resolved = append(resolved, ResolvedMapping{
			SourceIndex: sourceIndex[mapping.SourceColumn],
			TargetName:  targetName,
			TargetType:  column.Type,
			IsNullable:  column.IsNullable,
		})
		mappedCount++
	}

	if len(seenSources) != len(sourceColumns) || mappedCount == 0 {
		return nil, newImportError(importValidationMappingInvalid, nil)
	}

	return resolved, nil
}

// Execute applies a parsed import file to the target storage unit using the
// configured import mode and mappings.
func Execute(plugin engine.PluginFunctions, config *engine.PluginConfig, request *ExecuteRequest) (*ExecuteResult, error) {
	if request == nil || request.Parsed == nil {
		return nil, newImportError(importValidationInvalidOptions, nil)
	}
	if request.Mode == "" {
		request.Mode = ModeAppend
	}
	if !request.Mode.IsValid() {
		return nil, newImportError(importValidationInvalidOptions, nil)
	}
	if len(request.Parsed.Rows) == 0 {
		return nil, newImportError(importErrorNoRows, nil)
	}

	columns := request.TargetColumns
	if len(columns) == 0 {
		var err error
		columns, err = plugin.GetColumnsForTable(config, request.Schema, request.StorageUnit)
		if err != nil {
			return nil, newImportError(importErrorTableColumns, err)
		}
	}

	mappings, err := ResolveMappings(request.Parsed.Columns, request.Mapping, columns, request.AllowAutoGenerated)
	if err != nil {
		return nil, err
	}

	batchSize := request.BatchSize
	if batchSize <= 0 {
		batchSize = defaultBatchSize
	}

	err = plugin.WithTransaction(config, func(tx any) error {
		cloned := *config
		if tx != nil {
			cloned.Transaction = tx
		}
		txConfig := &cloned

		if request.Mode == ModeOverwrite {
			graph, err := plugin.GetGraph(txConfig, request.Schema)
			if err != nil {
				return newImportError(importErrorClearFailed, err)
			}
			if err := plugins.ClearTableWithDependencies(plugin, txConfig, request.Schema, request.StorageUnit, graph); err != nil {
				return newImportError(importErrorClearFailed, err)
			}
		}

		if request.Mode == ModeAppend || request.Mode == ModeUpsert {
			var primaryKeys []string
			for _, column := range columns {
				if column.IsPrimary {
					primaryKeys = append(primaryKeys, column.Name)
				}
			}

			if request.Mode == ModeUpsert {
				if len(primaryKeys) == 0 {
					return newImportError(importErrorUpsertNoPK, nil)
				}
				txConfig.UpsertPKColumns = primaryKeys
			} else if len(primaryKeys) > 0 {
				txConfig.SkipConflictPKColumns = primaryKeys
			}
		}

		for start := 0; start < len(request.Parsed.Rows); start += batchSize {
			end := min(start+batchSize, len(request.Parsed.Rows))

			batch := request.Parsed.Rows[start:end]
			records := make([][]engine.Record, 0, len(batch))
			for _, row := range batch {
				recordRow := make([]engine.Record, 0, len(mappings))
				for _, mapping := range mappings {
					value := ""
					if mapping.SourceIndex < len(row) {
						value = row[mapping.SourceIndex]
					}

					extra := map[string]string{
						"Type": mapping.TargetType,
					}
					if mapping.IsNullable {
						extra["IsNullable"] = "true"
					}

					recordRow = append(recordRow, engine.Record{
						Key:   mapping.TargetName,
						Value: value,
						Extra: extra,
					})
				}
				records = append(records, recordRow)
			}

			status, err := plugin.BulkAddRows(txConfig, request.Schema, request.StorageUnit, records)
			if err != nil {
				key := ErrorKeyFromError(err)
				if key == "" {
					return newImportError(importErrorInsertFailed, err)
				}
				return newImportError(key, err)
			}
			if !status {
				return newImportError(importErrorInsertFailed, nil)
			}
		}

		return nil
	})
	if err != nil {
		if key := ErrorKeyFromError(err); key != "" {
			return nil, err
		}
		return nil, newImportError(importErrorImportFailed, err)
	}

	return &ExecuteResult{RowsImported: len(request.Parsed.Rows)}, nil
}

func parseCSV(data []byte, options *FileOptions, maxRows int, enforceRowCap bool) (*ParsedFile, error) {
	delimiter := ""
	if options.Delimiter != nil {
		delimiter = *options.Delimiter
	}
	if delimiter == "" {
		detected, err := DetectCSVDelimiter(data)
		if err != nil {
			return nil, err
		}
		delimiter = detected
	}
	if err := validateDelimiter(delimiter); err != nil {
		return nil, newImportError(importValidationInvalidDelimiter, err)
	}

	reader := csv.NewReader(bytes.NewReader(data))
	reader.Comma = rune(delimiter[0])
	reader.FieldsPerRecord = -1

	result := &ParsedFile{}
	firstRow := true

	for {
		row, err := reader.Read()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return nil, newImportError(importValidationParseFailed, err)
		}

		if firstRow {
			firstRow = false
			if options.HasHeader {
				if err := validateHeaderColumns(row); err != nil {
					return nil, err
				}
				result.Columns = row
				continue
			}

			if len(row) == 0 {
				return nil, newImportError(importValidationNoColumns, nil)
			}
			result.Columns = generatedColumns(len(row))
			normalized, err := normalizeRow(row, len(result.Columns))
			if err != nil {
				return nil, err
			}
			result.Rows = append(result.Rows, normalized)
			if exceededRowLimit(result.Rows, enforceRowCap) {
				return nil, newImportError(importValidationRowLimitExceeded, nil)
			}
			if maxRows > 0 && len(result.Rows) >= maxRows {
				result.Truncated = true
				break
			}
			continue
		}

		normalized, err := normalizeRow(row, len(result.Columns))
		if err != nil {
			return nil, err
		}

		result.Rows = append(result.Rows, normalized)
		if exceededRowLimit(result.Rows, enforceRowCap) {
			return nil, newImportError(importValidationRowLimitExceeded, nil)
		}
		if maxRows > 0 && len(result.Rows) >= maxRows {
			result.Truncated = true
			break
		}
	}

	if len(result.Columns) == 0 {
		return nil, newImportError(importValidationNoColumns, nil)
	}

	return result, nil
}

func parseExcel(data []byte, options *FileOptions, maxRows int, enforceRowCap bool) (*ParsedFile, error) {
	file, err := excelize.OpenReader(bytes.NewReader(data), excelize.Options{
		UnzipSizeLimit:    MaxFileSizeBytes,
		UnzipXMLSizeLimit: MaxFileSizeBytes,
	})
	if err != nil {
		return nil, newImportError(importValidationParseFailed, err)
	}
	defer file.Close()

	sheetName := ""
	if options.Sheet != nil {
		sheetName = *options.Sheet
	}
	if sheetName == "" {
		sheets := file.GetSheetList()
		if len(sheets) == 0 {
			return nil, newImportError(importValidationNoColumns, nil)
		}
		sheetName = sheets[0]
	}

	rows, err := file.Rows(sheetName)
	if err != nil {
		return nil, newImportError(importValidationParseFailed, err)
	}
	defer rows.Close()

	result := &ParsedFile{Sheet: sheetName}
	firstRow := true

	for rows.Next() {
		row, err := rows.Columns()
		if err != nil {
			return nil, newImportError(importValidationParseFailed, err)
		}

		if firstRow {
			firstRow = false
			if options.HasHeader {
				if err := validateHeaderColumns(row); err != nil {
					return nil, err
				}
				result.Columns = row
				continue
			}

			if len(row) == 0 {
				return nil, newImportError(importValidationNoColumns, nil)
			}
			result.Columns = generatedColumns(len(row))
			normalized, err := normalizeRow(row, len(result.Columns))
			if err != nil {
				return nil, err
			}
			result.Rows = append(result.Rows, normalized)
			if exceededRowLimit(result.Rows, enforceRowCap) {
				return nil, newImportError(importValidationRowLimitExceeded, nil)
			}
			if maxRows > 0 && len(result.Rows) >= maxRows {
				result.Truncated = true
				break
			}
			continue
		}

		normalized, err := normalizeRow(row, len(result.Columns))
		if err != nil {
			return nil, err
		}

		result.Rows = append(result.Rows, normalized)
		if exceededRowLimit(result.Rows, enforceRowCap) {
			return nil, newImportError(importValidationRowLimitExceeded, nil)
		}
		if maxRows > 0 && len(result.Rows) >= maxRows {
			result.Truncated = true
			break
		}
	}

	if len(result.Columns) == 0 {
		return nil, newImportError(importValidationNoColumns, nil)
	}

	return result, nil
}

func normalizeRow(row []string, columnCount int) ([]string, error) {
	if len(row) > columnCount {
		return nil, newImportError(importValidationRowTooManyColumns, nil)
	}
	if len(row) == columnCount {
		return row, nil
	}

	normalized := make([]string, columnCount)
	copy(normalized, row)
	for idx := len(row); idx < columnCount; idx++ {
		normalized[idx] = ""
	}
	return normalized, nil
}

func validateHeaderColumns(columns []string) error {
	seen := make(map[string]struct{}, len(columns))
	for _, column := range columns {
		if column == "" {
			return newImportError(importValidationEmptyHeader, nil)
		}
		if _, exists := seen[column]; exists {
			return newImportError(importValidationDuplicateHeader, nil)
		}
		seen[column] = struct{}{}
	}
	return nil
}

func generatedColumns(columnCount int) []string {
	columns := make([]string, columnCount)
	for idx := range columns {
		columns[idx] = "col" + strconv.Itoa(idx+1)
	}
	return columns
}

func exceededRowLimit(rows [][]string, enforceRowCap bool) bool {
	if enforceRowCap && len(rows) > defaultMaxRows {
		return true
	}
	return false
}

func validateDelimiter(delimiter string) error {
	if len(delimiter) != 1 {
		return errors.New("delimiter must be a single character")
	}

	switch delimiter[0] {
	case '=', '+', '-', '@', '\r', '\n', '\'', '"':
		return errors.New("invalid delimiter")
	default:
		return nil
	}
}
