package importer

import (
	"reflect"
	"testing"

	"github.com/clidey/whodb/core/internal/testutil"
	"github.com/clidey/whodb/core/src/engine"
)

func TestParseFileWithoutHeader(t *testing.T) {
	parsed, err := ParseFile([]byte("1,alice\n2,bob\n"), &FileOptions{
		Format:    FileFormatCSV,
		HasHeader: false,
	}, 0, false)
	if err != nil {
		t.Fatalf("ParseFile returned error: %v", err)
	}

	if !reflect.DeepEqual(parsed.Columns, []string{"col1", "col2"}) {
		t.Fatalf("unexpected columns: %#v", parsed.Columns)
	}
	if len(parsed.Rows) != 2 {
		t.Fatalf("expected 2 rows, got %d", len(parsed.Rows))
	}
	if parsed.Rows[0][0] != "1" || parsed.Rows[0][1] != "alice" {
		t.Fatalf("unexpected first row: %#v", parsed.Rows[0])
	}
}

func TestBuildDefaultMappingsRequiresAutoGeneratedToggle(t *testing.T) {
	targetColumns := []engine.Column{
		{Name: "id", Type: "INTEGER", IsAutoIncrement: true},
		{Name: "name", Type: "TEXT"},
	}

	mappings, autoGeneratedColumns, err := BuildDefaultMappings(
		[]string{"id", "name"},
		targetColumns,
		true,
		false,
	)
	if key := ErrorKeyFromError(err); key != "import.validation.auto_generated_requires_toggle" {
		t.Fatalf("expected auto-generated toggle error, got %v", err)
	}
	if len(mappings) != 2 {
		t.Fatalf("expected 2 mappings, got %d", len(mappings))
	}
	if !reflect.DeepEqual(autoGeneratedColumns, []string{"id"}) {
		t.Fatalf("unexpected auto-generated columns: %#v", autoGeneratedColumns)
	}
}

func TestExecuteAppendSetsSkipConflictPrimaryKeys(t *testing.T) {
	mock := testutil.NewPluginMock(engine.DatabaseType("Test"))
	mock.WithTransactionFunc = func(config *engine.PluginConfig, operation func(tx any) error) error {
		return operation(nil)
	}
	mock.BulkAddRowsFunc = func(config *engine.PluginConfig, _, _ string, rows [][]engine.Record) (bool, error) {
		if !reflect.DeepEqual(config.SkipConflictPKColumns, []string{"id"}) {
			t.Fatalf("expected append mode PK columns, got %#v", config.SkipConflictPKColumns)
		}
		if len(config.UpsertPKColumns) != 0 {
			t.Fatalf("did not expect upsert PK columns, got %#v", config.UpsertPKColumns)
		}
		if rows[0][1].Extra["Type"] != "TEXT" {
			t.Fatalf("expected type metadata to be preserved, got %#v", rows[0][1].Extra)
		}
		return true, nil
	}

	result, err := Execute(mock, engine.NewPluginConfig(&engine.Credentials{Type: "Test"}), &ExecuteRequest{
		Schema:      "public",
		StorageUnit: "users",
		Mode:        ModeAppend,
		Parsed: &ParsedFile{
			Columns: []string{"id", "name"},
			Rows:    [][]string{{"1", "alice"}, {"2", "bob"}},
		},
		Mapping: []ColumnMapping{
			{SourceColumn: "id", TargetColumn: new("id")},
			{SourceColumn: "name", TargetColumn: new("name")},
		},
		TargetColumns: []engine.Column{
			{Name: "id", Type: "INTEGER", IsPrimary: true},
			{Name: "name", Type: "TEXT", IsNullable: true},
		},
	})
	if err != nil {
		t.Fatalf("Execute returned error: %v", err)
	}
	if result.RowsImported != 2 {
		t.Fatalf("expected 2 imported rows, got %d", result.RowsImported)
	}
}

func TestExecuteOverwriteClearsTargetTable(t *testing.T) {
	mock := testutil.NewPluginMock(engine.DatabaseType("Test"))
	cleared := false
	mock.WithTransactionFunc = func(config *engine.PluginConfig, operation func(tx any) error) error {
		return operation(nil)
	}
	mock.GetGraphFunc = func(*engine.PluginConfig, string) ([]engine.GraphUnit, error) {
		return []engine.GraphUnit{}, nil
	}
	mock.ClearTableDataFunc = func(*engine.PluginConfig, string, string) (bool, error) {
		cleared = true
		return true, nil
	}
	mock.BulkAddRowsFunc = func(_ *engine.PluginConfig, _, _ string, _ [][]engine.Record) (bool, error) {
		return true, nil
	}

	_, err := Execute(mock, engine.NewPluginConfig(&engine.Credentials{Type: "Test"}), &ExecuteRequest{
		Schema:      "public",
		StorageUnit: "users",
		Mode:        ModeOverwrite,
		Parsed: &ParsedFile{
			Columns: []string{"name"},
			Rows:    [][]string{{"alice"}},
		},
		Mapping: []ColumnMapping{
			{SourceColumn: "name", TargetColumn: new("name")},
		},
		TargetColumns: []engine.Column{
			{Name: "name", Type: "TEXT"},
		},
	})
	if err != nil {
		t.Fatalf("Execute returned error: %v", err)
	}
	if !cleared {
		t.Fatal("expected overwrite mode to clear existing rows")
	}
}

func TestExecuteUpsertRequiresPrimaryKey(t *testing.T) {
	mock := testutil.NewPluginMock(engine.DatabaseType("Test"))
	mock.WithTransactionFunc = func(config *engine.PluginConfig, operation func(tx any) error) error {
		return operation(nil)
	}

	_, err := Execute(mock, engine.NewPluginConfig(&engine.Credentials{Type: "Test"}), &ExecuteRequest{
		Schema:      "public",
		StorageUnit: "users",
		Mode:        ModeUpsert,
		Parsed: &ParsedFile{
			Columns: []string{"name"},
			Rows:    [][]string{{"alice"}},
		},
		Mapping: []ColumnMapping{
			{SourceColumn: "name", TargetColumn: new("name")},
		},
		TargetColumns: []engine.Column{
			{Name: "name", Type: "TEXT"},
		},
	})
	if key := ErrorKeyFromError(err); key != "import.error.upsert_no_pk" {
		t.Fatalf("expected upsert_no_pk error, got %v", err)
	}
}

//go:fix inline
func stringPtr(value string) *string {
	return new(value)
}
