# GENERATED by `whodb sdk generate` — DO NOT EDIT.
# Typed client for your WhoDB project's ontology, layered over the whodb SDK.
# Regenerate after ontology changes: whodb sdk generate --language python
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from whodb import WhoDB

#: SHA-256 of the ontology model this client was generated from.
ONTOLOGY_HASH = "9624e601205889ab0364197e9723b73f4115a63b5ef4bf389cb09a5fd2a7438a"


@dataclass
class Order:
    """Order"""
    order_id: str
    total: float


class OrderHandle:
    """Typed handle for the order entity."""

    def __init__(self, handle):
        self._handle = handle

    def get(self, pk):
        """Fetch one Order by primary key (order_id)."""
        return self._handle.get(pk)

    def list(self, **kwargs):
        """List Order records."""
        return self._handle.list(**kwargs)

    def query(self, **kwargs):
        """Flexible query (search, joins, grouping)."""
        return self._handle.query(**kwargs)

    def create(self, values):
        """Insert one record."""
        return self._handle.create(values)

    def create_many(self, rows, idempotency_key=None):
        """Insert many records with optional idempotency key."""
        return self._handle.create_many(rows, idempotency_key=idempotency_key)

    def update(self, pk, values):
        """Update one record by primary key."""
        return self._handle.update(pk, values)

    def delete(self, pk):
        """Delete one record by primary key."""
        return self._handle.delete(pk)

    @property
    def dynamic(self):
        """The underlying dynamic handle, for operations not typed here."""
        return self._handle


@dataclass
class User:
    """A registered user."""
    active: bool
    age: Optional[int] = None
    email: str
    id: str
    joined_at: Optional[datetime] = None


class UserHandle:
    """Typed handle for the user entity."""

    def __init__(self, handle):
        self._handle = handle

    def get(self, pk):
        """Fetch one User by primary key (id)."""
        return self._handle.get(pk)

    def list(self, **kwargs):
        """List User records."""
        return self._handle.list(**kwargs)

    def query(self, **kwargs):
        """Flexible query (search, joins, grouping)."""
        return self._handle.query(**kwargs)

    def create(self, values):
        """Insert one record."""
        return self._handle.create(values)

    def create_many(self, rows, idempotency_key=None):
        """Insert many records with optional idempotency key."""
        return self._handle.create_many(rows, idempotency_key=idempotency_key)

    def update(self, pk, values):
        """Update one record by primary key."""
        return self._handle.update(pk, values)

    def delete(self, pk):
        """Delete one record by primary key."""
        return self._handle.delete(pk)

    def orders(self, pk, **kwargs):
        """Follow the orders link to order records (ONE_TO_MANY)."""
        return self._handle.follow_link(pk, "orders", **kwargs)

    @property
    def dynamic(self):
        """The underlying dynamic handle, for operations not typed here."""
        return self._handle


class TypedOntology:
    """Typed ontology root for this project."""

    def __init__(self, client: WhoDB):
        self.Order = OrderHandle(client.ontology("order"))
        self.User = UserHandle(client.ontology("user"))


class TypedClient:
    """Typed WhoDB client for this project."""

    def __init__(self, **config: Any):
        self.client = WhoDB(**config)
        self.ontology = TypedOntology(self.client)


def create_client(**config: Any) -> TypedClient:
    """Create a typed client for this project's ontology."""
    return TypedClient(**config)
