// GENERATED by `whodb sdk generate` — DO NOT EDIT.
// Typed client for your WhoDB project's ontology, layered over @clidey/whodb-sdk.
// Regenerate after ontology changes: whodb sdk generate --language ts
/* eslint-disable */
import { WhoDB, OntologyHandle, ListCall, type WhoDBConfig } from '@clidey/whodb-sdk';

/** SHA-256 of the ontology model this client was generated from. */
export const ONTOLOGY_HASH = '9624e601205889ab0364197e9723b73f4115a63b5ef4bf389cb09a5fd2a7438a';

/** Order */
export interface Order {
  order_id: string;
  total: number;
}

/** Typed handle for the order entity. */
export class OrderHandle {
  private readonly handle: OntologyHandle;

  constructor(handle: OntologyHandle) {
    this.handle = handle;
  }
  /** Fetches one Order by primary key (order_id). */
  async get(pk: string | number): Promise<Order | null> {
    return (await this.handle.get(pk)) as Order | null;
  }

  /** Lists Order records; supports `.pages()` iteration. */
  list(options: Parameters<OntologyHandle['list']>[0] = {}): ListCall {
    return this.handle.list(options);
  }

  /** Flexible query (search, joins, grouping). */
  async query(options: Parameters<OntologyHandle['query']>[0]): Promise<Order[]> {
    return (await this.handle.query(options)) as unknown as Order[];
  }

  /** Inserts one record. */
  async create(values: Partial<Order>): Promise<void> {
    return this.handle.create(values as Record<string, unknown>);
  }

  /** Inserts many records with optional idempotency key. */
  async createMany(rows: Array<Partial<Order>>, options: { idempotencyKey?: string } = {}) {
    return this.handle.createMany(rows as Array<Record<string, unknown>>, options);
  }

  /** Updates one record by primary key. */
  async update(pk: string | number, values: Partial<Order>): Promise<void> {
    return this.handle.update(pk, values as Record<string, unknown>);
  }

  /** Deletes one record by primary key. */
  async delete(pk: string | number): Promise<void> {
    return this.handle.delete(pk);
  }

  /** The underlying dynamic handle, for operations not typed here. */
  get dynamic(): OntologyHandle {
    return this.handle;
  }
}

/** A registered user. */
export interface User {
  active: boolean;
  age?: number | null;
  email: string;
  id: string;
  joined_at?: Date | null;
}

/** Typed handle for the user entity. */
export class UserHandle {
  private readonly handle: OntologyHandle;

  constructor(handle: OntologyHandle) {
    this.handle = handle;
  }
  /** Fetches one User by primary key (id). */
  async get(pk: string | number): Promise<User | null> {
    return (await this.handle.get(pk)) as User | null;
  }

  /** Lists User records; supports `.pages()` iteration. */
  list(options: Parameters<OntologyHandle['list']>[0] = {}): ListCall {
    return this.handle.list(options);
  }

  /** Flexible query (search, joins, grouping). */
  async query(options: Parameters<OntologyHandle['query']>[0]): Promise<User[]> {
    return (await this.handle.query(options)) as unknown as User[];
  }

  /** Inserts one record. */
  async create(values: Partial<User>): Promise<void> {
    return this.handle.create(values as Record<string, unknown>);
  }

  /** Inserts many records with optional idempotency key. */
  async createMany(rows: Array<Partial<User>>, options: { idempotencyKey?: string } = {}) {
    return this.handle.createMany(rows as Array<Record<string, unknown>>, options);
  }

  /** Updates one record by primary key. */
  async update(pk: string | number, values: Partial<User>): Promise<void> {
    return this.handle.update(pk, values as Record<string, unknown>);
  }

  /** Deletes one record by primary key. */
  async delete(pk: string | number): Promise<void> {
    return this.handle.delete(pk);
  }

  /** Follows the orders link to order records (ONE_TO_MANY). */
  orders(pk: string | number, options: { pageSize?: number } = {}): ListCall {
    return this.handle.followLink(pk, 'orders', options);
  }

  /** The underlying dynamic handle, for operations not typed here. */
  get dynamic(): OntologyHandle {
    return this.handle;
  }
}

/** Typed ontology root for this project. */
export interface TypedOntology {
  Order: OrderHandle;
  User: UserHandle;
}

/** Typed WhoDB client for this project. */
export interface TypedClient {
  /** The underlying dynamic client. */
  client: WhoDB;
  ontology: TypedOntology;
}

/**
 * Creates a typed client. Verifies at first use that the live ontology still
 * matches ONTOLOGY_HASH and warns on drift (regenerate to clear).
 */
export function createClient(config: WhoDBConfig = {}): TypedClient {
  const client = new WhoDB(config);
  return {
    client,
    ontology: {
      Order: new OrderHandle(client.ontology('order')),
      User: new UserHandle(client.ontology('user')),
    },
  };
}
