/*
 * Copyright 2026 Clidey, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package graph

const (
	maxImportRows          = 100000
	maxImportFileSizeBytes = int64(50 * 1024 * 1024)
	importPreviewRowLimit  = 25
	importBatchSize        = 1000

	importValidationGeneric               = "import.validation.generic"
	importValidationMissingFile           = "import.validation.missing_file"
	importValidationFileTooLarge          = "import.validation.file_too_large"
	importValidationInvalidOptions        = "import.validation.invalid_options"
	importValidationAmbiguousDelimiter    = "import.validation.ambiguous_delimiter"
	importValidationInvalidDelimiter      = "import.validation.invalid_delimiter"
	importValidationRowTooManyColumns     = "import.validation.row_too_many_columns"
	importValidationDuplicateHeader       = "import.validation.duplicate_header"
	importValidationEmptyHeader           = "import.validation.empty_header"
	importValidationColumnCountMismatch   = "import.validation.column_count_mismatch"
	importValidationColumnCountInsertable = "import.validation.column_count_insertable"
	importValidationUnknownColumn         = "import.validation.column_unknown"
	importValidationGeneratedColumn       = "import.validation.column_generated"
	importValidationAutoGeneratedColumn   = "import.validation.column_auto_generated"
	importValidationAutoGeneratedToggle   = "import.validation.auto_generated_requires_toggle"

	// SQL import error keys
	importErrorSQLSourceBoth                = "import.error.sql_source_both"
	importErrorSQLSourceMissing             = "import.error.sql_source_missing"
	importErrorSQLTooLarge                  = "import.error.sql_too_large"
	importErrorSQLFailed                    = "import.error.sql_failed"
	importErrorSQLFileFailed                = "import.error.sql_file_failed"
	importErrorSQLMultiStatementUnsupported = "import.error.sql_multi_statement_unsupported"
	importErrorImportFailed                 = "import.error.import_failed"
)
