/*
 * Copyright 2026 Clidey, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package graph

import (
	"fmt"
	"strings"

	"github.com/clidey/whodb/core/graph/model"
	"github.com/clidey/whodb/core/src/engine"
	"github.com/clidey/whodb/core/src/log"
	"github.com/clidey/whodb/core/src/plugins"
)

func importMappingPreviewItems(mappings []*model.ImportColumnMapping) []*model.ImportColumnMappingPreview {
	previewItems := make([]*model.ImportColumnMappingPreview, 0, len(mappings))
	for _, mapping := range mappings {
		if mapping == nil || mapping.TargetColumn == nil {
			continue
		}
		previewItems = append(previewItems, &model.ImportColumnMappingPreview{
			SourceColumn: mapping.SourceColumn,
			TargetColumn: *mapping.TargetColumn,
		})
	}
	return previewItems
}

func importExistingTableFile(plugin *engine.Plugin, config *engine.PluginConfig, parsed *importParseResult, target *model.ImportExistingTableInput) (*model.ImportResult, error) {
	columns, err := plugin.GetColumnsForTable(config, target.Schema, target.StorageUnit)
	if err != nil {
		return importResult(false, importErrorTableColumns), nil
	}
	if err := plugin.MarkGeneratedColumns(config, target.Schema, target.StorageUnit, columns); err != nil {
		log.WithError(err).Warn("Failed to mark generated columns for import")
	}

	allowAutoGenerated := false
	if target.AllowAutoGenerated != nil {
		allowAutoGenerated = *target.AllowAutoGenerated
	}

	mappings, err := resolveImportMappings(parsed.columns, target.Mapping, columns, allowAutoGenerated)
	if err != nil {
		return importResult(false, validationKeyFromError(err)), nil
	}

	err = plugin.WithTransaction(config, func(tx any) error {
		cloned := *config
		if tx != nil {
			cloned.Transaction = tx
		}
		txConfig := &cloned

		if target.Mode == model.ImportModeOverwrite {
			graph, err := plugin.GetGraph(txConfig, target.Schema)
			if err != nil {
				return fmt.Errorf(importErrorClearFailed+": %w", err)
			}
			if err := plugins.ClearTableWithDependencies(plugin, txConfig, target.Schema, target.StorageUnit, graph); err != nil {
				return fmt.Errorf(importErrorClearFailed+": %w", err)
			}
		}

		if target.Mode == model.ImportModeAppend || target.Mode == model.ImportModeUpsert {
			var pkCols []string
			for _, col := range columns {
				if col.IsPrimary {
					pkCols = append(pkCols, col.Name)
				}
			}
			if target.Mode == model.ImportModeUpsert {
				if len(pkCols) == 0 {
					return fmt.Errorf(importErrorUpsertNoPK)
				}
				txConfig.UpsertPKColumns = pkCols
			} else if len(pkCols) > 0 {
				txConfig.SkipConflictPKColumns = pkCols
			}
		}

		return importRowsInBatches(plugin, txConfig, target.Schema, target.StorageUnit, parsed.rows, mappings)
	})
	if err != nil {
		errMsg := err.Error()
		if errMsg == importErrorUpsertNoPK || errMsg == importErrorUpsertNotSupported {
			return importResult(false, errMsg), nil
		}
		log.WithError(err).Error("Import failed")
		return importResultWithMessage(false, importErrorImportFailed, err.Error()), nil
	}

	return importResult(true, ""), nil
}

func importNewTableFile(plugin *engine.Plugin, config *engine.PluginConfig, parsed *importParseResult, target *model.ImportNewTableInput) (*model.ImportResult, error) {
	tableName := strings.TrimSpace(target.TableName)
	if tableName == "" {
		return importResult(false, importValidationTableNameEmpty), nil
	}

	exists, err := plugin.StorageUnitExists(config, target.Schema, tableName)
	if err != nil {
		return importResultWithMessage(false, importErrorImportFailed, err.Error()), nil
	}
	if exists {
		return importResult(false, importValidationTableExists), nil
	}

	resolvedColumns, fields, err := resolveNewTableImportColumns(parsed.columns, target.Columns, plugin.GetDatabaseMetadata())
	if err != nil {
		return importResult(false, validationKeyFromError(err)), nil
	}

	tableCreated := false
	err = plugin.WithTransaction(config, func(tx any) error {
		cloned := *config
		if tx != nil {
			cloned.Transaction = tx
		}
		txConfig := &cloned

		status, err := plugin.AddStorageUnitWithOptions(txConfig, target.Schema, tableName, fields, engine.CreateStorageUnitOptions{
			PrimaryKeysUseSourceValues: true,
		})
		if err != nil {
			return err
		}
		if !status {
			return fmt.Errorf(importErrorImportFailed)
		}
		tableCreated = true

		return importNewTableRowsInBatches(plugin, txConfig, target.Schema, tableName, parsed.rows, resolvedColumns)
	})
	if err != nil {
		if tableCreated {
			if _, dropErr := plugin.DropStorageUnit(config, target.Schema, tableName); dropErr != nil {
				return importResultWithMessage(false, importErrorImportFailed, fmt.Sprintf("%s; cleanup failed: %s", err.Error(), dropErr.Error())), nil
			}
		}
		log.WithError(err).Error("New table import failed")
		return importResultWithMessage(false, importErrorImportFailed, err.Error()), nil
	}

	return importResult(true, ""), nil
}

func importRowsInBatches(plugin *engine.Plugin, config *engine.PluginConfig, schema string, storageUnit string, rows [][]string, mappings []importMapping) error {
	for start := 0; start < len(rows); start += importBatchSize {
		end := start + importBatchSize
		if end > len(rows) {
			end = len(rows)
		}

		batch := rows[start:end]
		records := make([][]engine.Record, 0, len(batch))
		for _, row := range batch {
			recordRow := make([]engine.Record, 0, len(mappings))
			for _, mapping := range mappings {
				value := ""
				if mapping.sourceIndex < len(row) {
					value = row[mapping.sourceIndex]
				}

				extra := map[string]string{
					"Type": mapping.targetType,
				}
				if mapping.isNullable {
					extra["IsNullable"] = "true"
				}

				recordRow = append(recordRow, engine.Record{
					Key:   mapping.targetName,
					Value: value,
					Extra: extra,
				})
			}
			records = append(records, recordRow)
		}

		status, err := plugin.BulkAddRows(config, schema, storageUnit, records)
		if err != nil {
			return err
		}
		if !status {
			return fmt.Errorf(importErrorInsertFailed)
		}
	}

	return nil
}

func importNewTableRowsInBatches(plugin *engine.Plugin, config *engine.PluginConfig, schema string, storageUnit string, rows [][]string, columns []importNewTableColumn) error {
	mappings := make([]importMapping, 0, len(columns))
	for _, column := range columns {
		if column.skip {
			continue
		}
		mappings = append(mappings, importMapping{
			sourceIndex: column.sourceIndex,
			targetName:  column.targetName,
			targetType:  column.targetType,
			isNullable:  column.isNullable,
		})
	}
	return importRowsInBatches(plugin, config, schema, storageUnit, rows, mappings)
}
