/*
 * Copyright 2026 Clidey, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package graph

import (
	"errors"
	"io"
	"sort"
	"strings"

	"github.com/99designs/gqlgen/graphql"

	"github.com/clidey/whodb/core/graph/model"
	"github.com/clidey/whodb/core/src/importer"
	"github.com/clidey/whodb/core/src/source"
)

type importParseResult struct {
	columns   []string
	rows      [][]string
	truncated bool
	sheet     string
}

type importMapping struct {
	sourceIndex int
	targetName  string
	targetType  string
	isNullable  bool
}

func newImportValidationError(key string) error {
	return errors.New(key)
}

func isImportValidationKey(value string) bool {
	return strings.HasPrefix(value, "import.validation.")
}

func validationKeyFromError(err error) string {
	if err == nil {
		return ""
	}

	key := importer.ErrorKeyFromError(err)
	if isImportValidationKey(key) {
		return key
	}
	if isImportValidationKey(err.Error()) {
		return err.Error()
	}

	return importValidationGeneric
}

func readUploadBytes(upload graphql.Upload, maxBytes int64) ([]byte, error) {
	if upload.File == nil {
		return nil, newImportValidationError(importValidationMissingFile)
	}

	if closer, ok := upload.File.(io.Closer); ok {
		defer func() { _ = closer.Close() }()
	}

	if upload.Size > maxBytes {
		return nil, newImportValidationError(importValidationFileTooLarge)
	}

	limited := io.LimitReader(upload.File, maxBytes+1)
	data, err := io.ReadAll(limited)
	if err != nil {
		return nil, err
	}
	if int64(len(data)) > maxBytes {
		return nil, newImportValidationError(importValidationFileTooLarge)
	}

	return data, nil
}

func parseImportFile(data []byte, options *model.ImportFileOptions, maxRows int, enforceRowCap bool) (*importParseResult, error) {
	fileOptions, err := importerFileOptions(options)
	if err != nil {
		return nil, err
	}

	parsed, err := importer.ParseFile(data, fileOptions, maxRows, enforceRowCap)
	if err != nil {
		return nil, err
	}

	return &importParseResult{
		columns:   parsed.Columns,
		rows:      parsed.Rows,
		truncated: parsed.Truncated,
		sheet:     parsed.Sheet,
	}, nil
}

func detectCSVDelimiter(data []byte) (string, error) {
	return importer.DetectCSVDelimiter(data)
}

func resolveImportMappings(
	sourceColumns []string,
	mappings []*model.ImportColumnMapping,
	targetColumns []source.Column,
	allowAutoGenerated bool,
) ([]importMapping, error) {
	resolved, err := importer.ResolveMappings(
		sourceColumns,
		importerColumnMappings(mappings),
		targetColumns,
		allowAutoGenerated,
	)
	if err != nil {
		return nil, err
	}

	result := make([]importMapping, 0, len(resolved))
	for _, mapping := range resolved {
		result = append(result, importMapping{
			sourceIndex: mapping.SourceIndex,
			targetName:  mapping.TargetName,
			targetType:  mapping.TargetType,
			isNullable:  mapping.IsNullable,
		})
	}

	return result, nil
}

func buildImportMappingInputs(
	sourceColumns []string,
	targetColumns []source.Column,
	useHeaderMapping bool,
	allowAutoGenerated bool,
) ([]*model.ImportColumnMapping, []string, error) {
	mappings, autoGeneratedColumns, err := importer.BuildDefaultMappings(
		sourceColumns,
		targetColumns,
		useHeaderMapping,
		allowAutoGenerated,
	)
	if len(autoGeneratedColumns) > 0 {
		sort.Strings(autoGeneratedColumns)
	}
	return graphColumnMappings(mappings), autoGeneratedColumns, err
}

func importResult(success bool, detail string) *model.ImportResult {
	result := &model.ImportResult{Status: success}
	if detail != "" {
		result.Detail = &detail
	}
	return result
}

func importerFileOptions(options *model.ImportFileOptions) (*importer.FileOptions, error) {
	if options == nil {
		return nil, newImportValidationError(importValidationInvalidOptions)
	}

	return &importer.FileOptions{
		Format:    importer.FileFormat(options.Format),
		Delimiter: options.Delimiter,
		Sheet:     options.Sheet,
		HasHeader: true,
	}, nil
}

func importerColumnMappings(mappings []*model.ImportColumnMapping) []importer.ColumnMapping {
	result := make([]importer.ColumnMapping, 0, len(mappings))
	for _, mapping := range mappings {
		if mapping == nil {
			result = append(result, importer.ColumnMapping{})
			continue
		}

		result = append(result, importer.ColumnMapping{
			SourceColumn: mapping.SourceColumn,
			TargetColumn: mapping.TargetColumn,
			Skip:         mapping.Skip,
		})
	}

	return result
}

func graphColumnMappings(mappings []importer.ColumnMapping) []*model.ImportColumnMapping {
	result := make([]*model.ImportColumnMapping, 0, len(mappings))
	for _, mapping := range mappings {
		targetColumn := mapping.TargetColumn
		result = append(result, &model.ImportColumnMapping{
			SourceColumn: mapping.SourceColumn,
			TargetColumn: targetColumn,
			Skip:         mapping.Skip,
		})
	}
	return result
}
