/*
 * Copyright 2026 Clidey, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package graph

import (
	"context"
	"errors"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/clidey/whodb/core/graph/model"
	"github.com/clidey/whodb/core/src"
	"github.com/clidey/whodb/core/src/engine"
	"github.com/clidey/whodb/core/src/mockdata"
	"github.com/clidey/whodb/core/src/log"
	"github.com/clidey/whodb/core/src/plugins"
)

// ImportSQL is the resolver for the ImportSQL field.
func (r *mutationResolver) ImportSQL(ctx context.Context, input model.ImportSQLInput) (*model.ImportResult, error) {
	plugin, config := GetPluginForContext(ctx)

	script := ""
	if input.Script != nil {
		script = *input.Script
	}
	hasScript := script != ""
	hasFile := input.File != nil

	if hasScript && hasFile {
		return importResult(false, importErrorSQLSourceBoth), nil
	}
	if !hasScript && !hasFile {
		return importResult(false, importErrorSQLSourceMissing), nil
	}

	if hasFile {
		data, err := readUploadBytes(*input.File, maxImportFileSizeBytes)
		if err != nil {
			return importResult(false, importErrorSQLFileFailed), nil
		}
		script = string(data)
	}

	if int64(len([]byte(script))) > maxImportFileSizeBytes {
		return importResult(false, importErrorSQLTooLarge), nil
	}

	config.MultiStatement = true
	_, err := plugin.RawExecute(config, script)
	if err != nil {
		if errors.Is(err, engine.ErrMultiStatementUnsupported) {
			return importResult(false, importErrorSQLMultiStatementUnsupported), nil
		}
		log.WithError(err).Error("SQL import failed")
		return importResult(false, importErrorSQLFailed), nil
	}

	return importResult(true, ""), nil
}

// ImportPreview is the resolver for the ImportPreview field.
func (r *mutationResolver) ImportPreview(ctx context.Context, file graphql.Upload, options model.ImportFileOptions, schema *string, storageUnit *string, useHeaderMapping *bool) (*model.ImportPreview, error) {
	data, err := readUploadBytes(file, maxImportFileSizeBytes)
	if err != nil {
		return nil, err
	}

	result, err := parseImportFile(data, &options, importPreviewRowLimit, false)
	if err != nil {
		return nil, err
	}

	preview := &model.ImportPreview{
		Sheet:                      &result.sheet,
		Columns:                    result.columns,
		Rows:                       result.rows,
		Truncated:                  result.truncated,
		RequiresAllowAutoGenerated: false,
		AutoGeneratedColumns:       []string{},
	}

	if schema == nil || storageUnit == nil || useHeaderMapping == nil {
		return preview, nil
	}

	plugin, config := GetPluginForContext(ctx)
	columns, err := plugin.GetColumnsForTable(config, *schema, *storageUnit)
	if err != nil {
		return nil, err
	}
	if err := plugin.MarkGeneratedColumns(config, *schema, *storageUnit, columns); err != nil {
		log.WithError(err).Warn("Failed to mark generated columns for import preview")
	}

	allowAutoGenerated := *useHeaderMapping
	mappings, autoGeneratedColumns, err := buildImportMappingInputs(
		preview.Columns,
		columns,
		*useHeaderMapping,
		allowAutoGenerated,
	)
	if err != nil {
		key := validationKeyFromError(err)
		if key != "" {
			preview.ValidationError = &key
		}
		if len(autoGeneratedColumns) > 0 {
			preview.RequiresAllowAutoGenerated = true
			preview.AutoGeneratedColumns = autoGeneratedColumns
			if len(mappings) > 0 {
				preview.Mapping = make([]*model.ImportColumnMappingPreview, 0, len(mappings))
				for _, mapping := range mappings {
					if mapping == nil || mapping.TargetColumn == nil {
						continue
					}
					preview.Mapping = append(preview.Mapping, &model.ImportColumnMappingPreview{
						SourceColumn: mapping.SourceColumn,
						TargetColumn: *mapping.TargetColumn,
					})
				}
			}
		}
		return preview, nil
	}

	if len(autoGeneratedColumns) > 0 {
		preview.RequiresAllowAutoGenerated = true
		preview.AutoGeneratedColumns = autoGeneratedColumns
	}

	if len(mappings) > 0 {
		preview.Mapping = make([]*model.ImportColumnMappingPreview, 0, len(mappings))
		for _, mapping := range mappings {
			if mapping == nil || mapping.TargetColumn == nil {
				continue
			}
			preview.Mapping = append(preview.Mapping, &model.ImportColumnMappingPreview{
				SourceColumn: mapping.SourceColumn,
				TargetColumn: *mapping.TargetColumn,
			})
		}
	}

	return preview, nil
}

// ImportTableFile is the resolver for the ImportTableFile field.
func (r *mutationResolver) ImportTableFile(ctx context.Context, input model.ImportFileInput) (*model.ImportResult, error) {
	plugin, config := GetPluginForContext(ctx)

	data, err := readUploadBytes(input.File, maxImportFileSizeBytes)
	if err != nil {
		return importResult(false, validationKeyFromError(err)), nil
	}

	if input.Options == nil {
		return importResult(false, importValidationInvalidOptions), nil
	}

	parsed, err := parseImportFile(data, input.Options, maxImportRows, true)
	if err != nil {
		return importResult(false, validationKeyFromError(err)), nil
	}

	if len(parsed.rows) == 0 {
		return importResult(false, importErrorNoRows), nil
	}

	columns, err := plugin.GetColumnsForTable(config, input.Schema, input.StorageUnit)
	if err != nil {
		return importResult(false, importErrorTableColumns), nil
	}
	if err := plugin.MarkGeneratedColumns(config, input.Schema, input.StorageUnit, columns); err != nil {
		log.WithError(err).Warn("Failed to mark generated columns for import")
	}

	allowAutoGenerated := false
	if input.AllowAutoGenerated != nil {
		allowAutoGenerated = *input.AllowAutoGenerated
	}

	mappings, err := resolveImportMappings(parsed.columns, input.Mapping, columns, allowAutoGenerated)
	if err != nil {
		return importResult(false, validationKeyFromError(err)), nil
	}

	err = plugin.WithTransaction(config, func(tx any) error {
		cloned := *config
		if tx != nil {
			cloned.Transaction = tx
		}
		txConfig := &cloned

		if input.Mode == model.ImportModeOverwrite {
			graph, err := plugin.GetGraph(txConfig, input.Schema)
			if err != nil {
				return fmt.Errorf(importErrorClearFailed+": %w", err)
			}
			if err := plugins.ClearTableWithDependencies(plugin, txConfig, input.Schema, input.StorageUnit, graph); err != nil {
				return fmt.Errorf(importErrorClearFailed+": %w", err)
			}
		}

		if input.Mode == model.ImportModeAppend || input.Mode == model.ImportModeUpsert {
			var pkCols []string
			for _, col := range columns {
				if col.IsPrimary {
					pkCols = append(pkCols, col.Name)
				}
			}
			if input.Mode == model.ImportModeUpsert {
				if len(pkCols) == 0 {
					return fmt.Errorf(importErrorUpsertNoPK)
				}
				txConfig.UpsertPKColumns = pkCols
			} else if len(pkCols) > 0 {
				txConfig.SkipConflictPKColumns = pkCols
			}
		}

		for start := 0; start < len(parsed.rows); start += importBatchSize {
			end := start + importBatchSize
			if end > len(parsed.rows) {
				end = len(parsed.rows)
			}

			batch := parsed.rows[start:end]
			records := make([][]engine.Record, 0, len(batch))
			for _, row := range batch {
				recordRow := make([]engine.Record, 0, len(mappings))
				for _, mapping := range mappings {
					value := ""
					if mapping.sourceIndex < len(row) {
						value = row[mapping.sourceIndex]
					}

					extra := map[string]string{
						"Type": mapping.targetType,
					}
					if mapping.isNullable {
						extra["IsNullable"] = "true"
					}

					recordRow = append(recordRow, engine.Record{
						Key:   mapping.targetName,
						Value: value,
						Extra: extra,
					})
				}
				records = append(records, recordRow)
			}

			status, err := plugin.BulkAddRows(txConfig, input.Schema, input.StorageUnit, records)
			if err != nil {
				return err
			}
			if !status {
				return fmt.Errorf(importErrorInsertFailed)
			}
		}

		return nil
	})
	if err != nil {
		// Surface specific upsert errors with their own localization keys
		errMsg := err.Error()
		if errMsg == importErrorUpsertNoPK || errMsg == importErrorUpsertNotSupported {
			return importResult(false, errMsg), nil
		}
		log.WithError(err).Error("Import failed")
		return importResult(false, importErrorImportFailed), nil
	}

	return importResult(true, ""), nil
}

// GenerateMockData is the resolver for the GenerateMockData field.
func (r *mutationResolver) GenerateMockData(ctx context.Context, input model.MockDataGenerationInput) (*model.MockDataGenerationStatus, error) {
	log.WithField("schema", input.Schema).WithField("table", input.StorageUnit).WithField("rowCount", input.RowCount).WithField("overwrite", input.OverwriteExisting).Info("Starting mock data generation")

	maxRowLimit := mockdata.GetMockDataGenerationMaxRowCount()
	if input.RowCount > maxRowLimit {
		log.WithField("requested", input.RowCount).WithField("max", maxRowLimit).Error("Row count exceeds maximum limit")
		return nil, fmt.Errorf("row count exceeds maximum limit of %d", maxRowLimit)
	}

	if !mockdata.IsMockDataGenerationAllowed(input.StorageUnit) {
		log.WithField("table", input.StorageUnit).Error("Mock data generation not allowed for table")
		return nil, errors.New("mock data generation is not allowed for this table")
	}

	plugin, config := GetPluginForContext(ctx)

	fkRatio := 0
	if input.FkDensityRatio != nil {
		fkRatio = *input.FkDensityRatio
	}
	generator := src.NewMockDataGenerator(fkRatio)
	result, err := generator.Generate(plugin, config, input.Schema, input.StorageUnit, input.RowCount, input.OverwriteExisting)
	if err != nil {
		log.WithError(err).Error("Mock data generation failed")
		return nil, fmt.Errorf("mock data generation failed: %w", err)
	}

	var details []*model.MockDataTableDetail
	if len(result.Details) > 0 {
		details = make([]*model.MockDataTableDetail, len(result.Details))
		for i, d := range result.Details {
			details[i] = &model.MockDataTableDetail{
				Table:            d.Table,
				RowsGenerated:    d.RowsGenerated,
				UsedExistingData: d.UsedExistingData,
			}
		}
	}

	log.WithField("generatedRows", result.TotalGenerated).Info("Mock data generation completed successfully")
	return &model.MockDataGenerationStatus{
		AmountGenerated: result.TotalGenerated,
		Details:         details,
	}, nil
}

// AnalyzeMockDataDependencies analyzes FK dependencies for mock data generation.
func (r *queryResolver) AnalyzeMockDataDependencies(ctx context.Context, schema string, storageUnit string, rowCount int, fkDensityRatio *int) (*model.MockDataDependencyAnalysis, error) {
	maxRowLimit := mockdata.GetMockDataGenerationMaxRowCount()
	if rowCount > maxRowLimit {
		errMsg := fmt.Sprintf("row count exceeds maximum limit of %d", maxRowLimit)
		return &model.MockDataDependencyAnalysis{
			Error: &errMsg,
		}, nil
	}

	if !mockdata.IsMockDataGenerationAllowed(storageUnit) {
		errMsg := "mock data generation is not allowed for this table"
		return &model.MockDataDependencyAnalysis{
			Error: &errMsg,
		}, nil
	}

	plugin, config := GetPluginForContext(ctx)
	if plugin == nil {
		return nil, errors.New("no database connection")
	}

	fkRatio := 0
	if fkDensityRatio != nil {
		fkRatio = *fkDensityRatio
	}
	generator := src.NewMockDataGenerator(fkRatio)
	analysis, err := generator.AnalyzeDependencies(plugin, config, schema, storageUnit, rowCount)
	if err != nil {
		errMsg := err.Error()
		return &model.MockDataDependencyAnalysis{
			Error: &errMsg,
		}, nil
	}

	tables := make([]*model.MockDataTableInfo, 0, len(analysis.Tables))
	for _, t := range analysis.Tables {
		tables = append(tables, &model.MockDataTableInfo{
			Table:            t.Table,
			RowsToGenerate:   t.RowCount,
			IsBlocked:        t.IsBlocked,
			UsesExistingData: t.UsesExistingData,
		})
	}

	var errorPtr *string
	if analysis.Error != "" {
		errorPtr = &analysis.Error
	}

	return &model.MockDataDependencyAnalysis{
		GenerationOrder: analysis.GenerationOrder,
		Tables:          tables,
		TotalRows:       analysis.TotalRows,
		Warnings:        analysis.Warnings,
		Error:           errorPtr,
	}, nil
}
