package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/clidey/whodb/core/graph/model"
	"github.com/clidey/whodb/core/src"
	"github.com/clidey/whodb/core/src/analytics"
	"github.com/clidey/whodb/core/src/audit"
	"github.com/clidey/whodb/core/src/auth"
	"github.com/clidey/whodb/core/src/common"
	"github.com/clidey/whodb/core/src/engine"
	"github.com/clidey/whodb/core/src/env"
	"github.com/clidey/whodb/core/src/envconfig"
	"github.com/clidey/whodb/core/src/llm"
	"github.com/clidey/whodb/core/src/log"
	"github.com/clidey/whodb/core/src/mockdata"
	"github.com/clidey/whodb/core/src/settings"
	"github.com/clidey/whodb/core/src/source"
	"github.com/clidey/whodb/core/src/sourcecatalog"
	"github.com/clidey/whodb/core/src/version"
)

// LoginSource is the resolver for the LoginSource field.
func (r *mutationResolver) LoginSource(ctx context.Context, credentials model.SourceLoginInput) (*model.StatusResponse, error) {
	creds := sourceCredentialsFromInput(credentials)
	if current := auth.GetSourceCredentials(ctx); current != nil && current.SourceType == creds.SourceType {
		creds.Values = mergeCurrentSourceValues(current, creds.Values)
	}
	return performSourceLogin(ctx, creds, "")
}

// LoginWithSourceProfile is the resolver for the LoginWithSourceProfile field.
func (r *mutationResolver) LoginWithSourceProfile(ctx context.Context, profile model.SourceProfileLoginInput) (*model.StatusResponse, error) {
	sourceProfile, credentials, ok := src.FindSourceProfile(profile.ID)
	if !ok {
		return nil, errors.New("login profile does not exist or is not authorized")
	}

	values, err := auth.MergeSourceProfileValues(credentials.SourceType, credentials.Values, recordInputsToMap(profile.Values))
	if err != nil {
		return nil, err
	}
	credentials.Values = values
	return performSourceLogin(ctx, credentials, sourceProfile.Source)
}

// Logout is the resolver for the Logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*model.StatusResponse, error) {
	start := time.Now()
	creds := auth.GetSourceCredentials(ctx)
	identity := strings.TrimSpace(analytics.MetadataFromContext(ctx).DistinctID)
	hasIdentity := identity != "" && identity != "disabled"
	hasProfile := false
	sourceType := ""
	var profileID *string
	if creds != nil {
		hasProfile = creds.ID != nil && strings.TrimSpace(*creds.ID) != ""
		sourceType = creds.SourceType
		profileID = creds.ID
	}

	if hasIdentity {
		analytics.CaptureWithDistinctID(ctx, identity, "logout.attempt", map[string]any{
			"database_type":      sourceType,
			"profile_id_present": hasProfile,
		})
	}

	resp, err := auth.Logout(ctx)
	if err != nil {
		if hasIdentity {
			analytics.CaptureError(ctx, "logout.execute", err, map[string]any{
				"database_type":      sourceType,
				"profile_id_present": hasProfile,
			})
		}
		if creds != nil {
			audit.RecordWithContext(ctx, audit.AuditEvent{
				Timestamp: start,
				Action:    "logout.source",
				Outcome:   audit.OutcomeFailure,
				Severity:  audit.SeverityWarn,
				Resource:  audit.SourceResource(sourceType, profileID),
				Details: map[string]any{
					"source_type":        sourceType,
					"profile_id_present": hasProfile,
					"error":              err.Error(),
				},
				Duration: time.Since(start),
			})
		}
		return nil, err
	}

	if hasIdentity {
		analytics.CaptureWithDistinctID(ctx, identity, "logout.success", map[string]any{
			"database_type":      sourceType,
			"profile_id_present": hasProfile,
		})
	}

	if creds != nil {
		audit.RecordWithContext(ctx, audit.AuditEvent{
			Timestamp: start,
			Action:    "logout.source",
			Outcome:   audit.OutcomeSuccess,
			Severity:  audit.SeverityInfo,
			Resource:  audit.SourceResource(sourceType, profileID),
			Details: map[string]any{
				"source_type":        sourceType,
				"profile_id_present": hasProfile,
			},
			Duration: time.Since(start),
		})
	}

	return resp, nil
}

// ExportSourceConnection is the resolver for the ExportSourceConnection field.
func (r *mutationResolver) ExportSourceConnection(ctx context.Context, id string, includeSecrets bool) ([]*model.Record, error) {
	return exportSourceConnection(ctx, id, includeSecrets)
}

// TestSourceConnection is the resolver for the TestSourceConnection field.
func (r *mutationResolver) TestSourceConnection(ctx context.Context, credentials model.SourceLoginInput) (*model.StatusResponse, error) {
	return testSourceConnection(ctx, sourceCredentialsFromInput(credentials))
}

// UpdateSettings is the resolver for the UpdateSettings field.
func (r *mutationResolver) UpdateSettings(ctx context.Context, newSettings model.SettingsConfigInput) (*model.StatusResponse, error) {
	start := time.Now()
	before := settings.Get()
	var fields []settings.ISettingsField
	changedFields := make([]string, 0, 1)
	details := map[string]any{}

	if newSettings.MetricsEnabled != nil {
		metricsEnabled := common.StrPtrToBool(newSettings.MetricsEnabled)
		fields = append(fields, settings.MetricsEnabledField(metricsEnabled))
		changedFields = append(changedFields, "metrics_enabled")
		details["metrics_enabled_before"] = before.MetricsEnabled
		details["metrics_enabled_after"] = metricsEnabled

		analytics.TrackMutation(ctx, "UpdateSettings.metrics", map[string]any{
			"metrics_enabled": metricsEnabled,
		})
	}

	updated := settings.UpdateSettings(fields...)
	if len(changedFields) > 0 {
		details["changed_fields"] = changedFields
		details["updated"] = updated
		audit.RecordWithContext(ctx, audit.AuditEvent{
			Timestamp: start,
			Action:    "settings.update",
			Outcome:   audit.OutcomeSuccess,
			Severity:  audit.SeverityInfo,
			Resource: audit.Resource{
				ID:   "global-settings",
				Type: "settings_config",
				Name: "settings",
			},
			Details:  details,
			Duration: time.Since(start),
		})
	}
	return &model.StatusResponse{
		Status: updated,
	}, nil
}

// CreateSourceObject is the resolver for the CreateSourceObject field.
func (r *mutationResolver) CreateSourceObject(ctx context.Context, parent *model.SourceObjectRefInput, name string, fields []*model.RecordInput) (*model.StatusResponse, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}
	resolvedParent := sourceRefFromInput(parent)
	if err := source.ValidateCreateChildSupported(spec, resolvedParent); err != nil {
		return nil, err
	}
	manager, ok := source.AsObjectManager(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source object creation is not supported")
	}

	status, err := manager.CreateObject(ctx, resolvedParent, name, recordInputsToSourceRecords(fields))
	if err != nil {
		return nil, err
	}

	return &model.StatusResponse{Status: status}, nil
}

// CreateSourceObjectFromDefinition is the resolver for the CreateSourceObjectFromDefinition field.
func (r *mutationResolver) CreateSourceObjectFromDefinition(ctx context.Context, parent *model.SourceObjectRefInput, definition model.SourceObjectDefinitionInput) (*model.StatusResponse, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}
	resolvedParent := sourceRefFromInput(parent)
	if err := source.ValidateCreateChildSupported(spec, resolvedParent); err != nil {
		return nil, err
	}
	manager, ok := source.AsObjectManager(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source object creation is not supported")
	}

	objectDefinition := sourceObjectDefinitionInputToSource(definition)
	status, err := manager.CreateObject(ctx, resolvedParent, objectDefinition.Name, source.ObjectDefinitionToRecords(objectDefinition))
	if err != nil {
		return nil, err
	}

	return &model.StatusResponse{Status: status}, nil
}

// UpdateSourceObject is the resolver for the UpdateSourceObject field.
func (r *mutationResolver) UpdateSourceObject(ctx context.Context, ref model.SourceObjectRefInput, values []*model.RecordInput, updatedColumns []string) (*model.StatusResponse, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}
	resolvedRef := sourceRefFromInput(&ref)
	if err := validateSourceObjectAction(spec, resolvedRef, source.ActionUpdateData); err != nil {
		return nil, err
	}
	manager, ok := source.AsObjectManager(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source object updates are not supported")
	}

	status, err := manager.UpdateObject(ctx, *resolvedRef, recordInputsToMap(values), updatedColumns)
	if err != nil {
		return nil, err
	}

	return &model.StatusResponse{Status: status}, nil
}

// AddSourceRow is the resolver for the AddSourceRow field.
func (r *mutationResolver) AddSourceRow(ctx context.Context, ref model.SourceObjectRefInput, values []*model.RecordInput) (*model.StatusResponse, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}
	resolvedRef := sourceRefFromInput(&ref)
	if err := validateSourceObjectAction(spec, resolvedRef, source.ActionInsertData); err != nil {
		return nil, err
	}
	manager, ok := source.AsObjectManager(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source row inserts are not supported")
	}

	status, err := manager.AddRow(ctx, *resolvedRef, recordInputsToSourceRecords(values))
	if err != nil {
		return nil, err
	}

	return &model.StatusResponse{Status: status}, nil
}

// DeleteSourceRow is the resolver for the DeleteSourceRow field.
func (r *mutationResolver) DeleteSourceRow(ctx context.Context, ref model.SourceObjectRefInput, values []*model.RecordInput) (*model.StatusResponse, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}
	resolvedRef := sourceRefFromInput(&ref)
	if err := validateSourceObjectAction(spec, resolvedRef, source.ActionDeleteData); err != nil {
		return nil, err
	}
	manager, ok := source.AsObjectManager(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source row deletes are not supported")
	}

	status, err := manager.DeleteRow(ctx, *resolvedRef, recordInputsToMap(values))
	if err != nil {
		return nil, err
	}

	return &model.StatusResponse{Status: status}, nil
}

// GenerateMockData is the resolver for the GenerateMockData field.
func (r *mutationResolver) GenerateMockData(ctx context.Context, input model.MockDataGenerationInput) (*model.MockDataGenerationStatus, error) {
	return generateMockDataForRef(ctx, input)
}

// ImportSQL is the resolver for the ImportSQL field.
func (r *mutationResolver) ImportSQL(ctx context.Context, input model.ImportSQLInput) (*model.ImportResult, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}

	script := ""
	if input.Script != nil {
		script = *input.Script
	}
	hasScript := script != ""
	hasFile := input.File != nil

	if hasScript && hasFile {
		return importResult(false, importErrorSQLSourceBoth), nil
	}
	if !hasScript && !hasFile {
		return importResult(false, importErrorSQLSourceMissing), nil
	}
	if err := source.ValidateScriptExecutionSupported(spec); err != nil {
		return nil, err
	}
	runner, ok := source.AsScriptRunner(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source scripts are not supported")
	}

	if hasFile {
		data, err := readUploadBytes(*input.File, maxImportFileSizeBytes)
		if err != nil {
			return importResult(false, importErrorSQLFileFailed), nil //nolint:nilerr
		}
		script = string(data)
	}

	if int64(len([]byte(script))) > maxImportFileSizeBytes {
		return importResult(false, importErrorSQLTooLarge), nil
	}

	_, err = runner.RunScript(ctx, script, spec.Traits.Query.SupportsMultiStatement)
	if err != nil {
		if errors.Is(err, engine.ErrMultiStatementUnsupported) {
			return importResult(false, importErrorSQLMultiStatementUnsupported), nil
		}
		log.WithError(err).Error("SQL import failed")
		return importResult(false, importErrorSQLFailed), nil
	}

	return importResult(true, ""), nil
}

// ImportPreview is the resolver for the ImportPreview field.
func (r *mutationResolver) ImportPreview(ctx context.Context, file graphql.Upload, options model.ImportFileOptions, ref *model.SourceObjectRefInput, useHeaderMapping *bool) (*model.ImportPreview, error) {
	return importPreviewForRef(ctx, file, options, ref, useHeaderMapping)
}

// ImportSourceObjectFile is the resolver for the ImportSourceObjectFile field.
func (r *mutationResolver) ImportSourceObjectFile(ctx context.Context, input model.ImportFileInput) (*model.ImportResult, error) {
	return importSourceObjectFile(ctx, input)
}

// ExecuteConfirmedSQL is the resolver for the ExecuteConfirmedSQL field.
func (r *mutationResolver) ExecuteConfirmedSQL(ctx context.Context, query string, operationType string) (*model.AIChatMessage, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}
	if err := source.ValidateScriptExecutionSupported(spec); err != nil {
		return nil, err
	}
	runner, ok := source.AsScriptRunner(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source scripts are not supported")
	}

	// Execute the SQL query
	result, execErr := runner.RunScript(ctx, query, false)

	message := &model.AIChatMessage{
		Type:                 operationType,
		Text:                 query,
		RequiresConfirmation: false,
	}

	if execErr != nil {
		message.Type = "error"
		message.Text = execErr.Error()
	} else {
		// Convert result
		var columns []*model.Column
		for _, column := range result.Columns {
			columns = append(columns, &model.Column{
				Type: column.Type,
				Name: column.Name,
			})
		}
		message.Result = &model.RowsResult{
			Columns: columns,
			Rows:    result.Rows,
		}
	}

	return message, nil
}

// GenerateChatTitle is the resolver for the GenerateChatTitle field.
func (r *mutationResolver) GenerateChatTitle(ctx context.Context, input model.GenerateChatTitleInput) (*model.GenerateChatTitleResponse, error) {
	return generateChatTitleImpl(ctx, input)
}

// Version is the resolver for the Version field.
func (r *queryResolver) Version(ctx context.Context) (string, error) {
	if env.ApplicationVersion != "" {
		return env.ApplicationVersion, nil
	}
	// Default fallback for development
	return "development", nil
}

// UpdateInfo is the resolver for the UpdateInfo field.
func (r *queryResolver) UpdateInfo(ctx context.Context) (*model.UpdateInfo, error) {
	currentVersion := env.ApplicationVersion
	if currentVersion == "" {
		currentVersion = "development"
	}

	disabled := env.GetDisableUpdateCheck() || os.Getenv("SNAP") != ""

	info := version.CheckForUpdate(currentVersion, disabled)
	return &model.UpdateInfo{
		CurrentVersion:  info.CurrentVersion,
		LatestVersion:   info.LatestVersion,
		UpdateAvailable: info.UpdateAvailable,
		ReleaseURL:      info.ReleaseURL,
	}, nil
}

// Health is the resolver for the Health field.
func (r *queryResolver) Health(ctx context.Context) (*model.HealthStatus, error) {
	status := &model.HealthStatus{
		Server:   "healthy",
		Database: "unavailable",
	}

	// Check if user is authenticated and has credentials
	credentials := auth.GetSourceCredentials(ctx)
	if credentials != nil && credentials.SourceType != "" {
		spec, session, err := getSourceSessionForContext(ctx)
		if err == nil {
			availability, ok := source.AsAvailabilityChecker(sourceAuditScopeFromContext(ctx, spec), session)
			if ok {
				healthCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
				defer cancel()

				result := make(chan string, 1)

				go func() {
					defer func() {
						if r := recover(); r != nil {
							log.Errorf("Panic during health check for source: %v", r)
							result <- "error"
						}
					}()

					if availability.IsAvailable(healthCtx) {
						result <- "healthy"
					} else {
						result <- "error"
					}
				}()

				select {
				case status.Database = <-result:
				case <-healthCtx.Done():
					status.Database = "error"
				}
			}
		}
	}

	return status, nil
}

// SourceProfiles is the resolver for the SourceProfiles field.
func (r *queryResolver) SourceProfiles(ctx context.Context) ([]*model.SourceProfile, error) {
	return sourceProfilesToModel(src.GetSourceProfiles()), nil
}

// SourceTypes is the resolver for the SourceTypes field.
func (r *queryResolver) SourceTypes(ctx context.Context) ([]*model.SourceType, error) {
	specs := sourcecatalog.All()
	types := make([]*model.SourceType, 0, len(specs))
	for i := range specs {
		types = append(types, sourceTypeToModel(specs[i]))
	}
	return types, nil
}

// SourceFieldOptions is the resolver for the SourceFieldOptions field.
func (r *queryResolver) SourceFieldOptions(ctx context.Context, sourceType string, fieldKey string, values []*model.RecordInput) ([]string, error) {
	spec, ok := sourcecatalog.Find(sourceType)
	if !ok {
		return nil, fmt.Errorf("unsupported source type: %s", sourceType)
	}

	credentials := &source.Credentials{
		SourceType: sourceType,
		Values:     recordInputsToMap(values),
	}
	if current := auth.GetSourceCredentials(ctx); current != nil && current.SourceType == sourceType {
		credentials.Values = mergeCurrentSourceValues(current, credentials.Values)
	}

	session, err := source.Open(ctx, spec, credentials)
	if err != nil {
		return nil, err
	}

	reader, ok := source.AsConnectionFieldOptionsReader(source.AuditScopeFromCredentials(spec, credentials), session)
	if !ok {
		return []string{}, nil
	}

	return reader.ConnectionFieldOptions(ctx, fieldKey, credentials.Values)
}

// SourceSession is the resolver for the SourceSession field.
func (r *queryResolver) SourceSession(ctx context.Context) (*model.SourceSession, error) {
	credentials := auth.GetSourceCredentials(ctx)
	if credentials == nil {
		return nil, nil
	}

	database := ""
	for key, value := range credentials.Values {
		if strings.EqualFold(key, "database") {
			database = value
			break
		}
	}

	return &model.SourceSession{
		ID:         credentials.ID,
		SourceType: credentials.SourceType,
		Database:   database,
	}, nil
}

// SourceSessionMetadata is the resolver for the SourceSessionMetadata field.
func (r *queryResolver) SourceSessionMetadata(ctx context.Context) (*model.SourceSessionMetadata, error) {
	_, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}

	metadata, err := session.Metadata(ctx)
	if err != nil {
		return nil, err
	}
	return sourceSessionMetadataToModel(metadata), nil
}

// SourceObjectCreationMetadata is the resolver for the SourceObjectCreationMetadata field.
func (r *queryResolver) SourceObjectCreationMetadata(ctx context.Context, parent *model.SourceObjectRefInput) (*model.ObjectCreationMetadata, error) {
	spec, _, err := getSourceSpecForContext(ctx)
	if err != nil {
		return nil, err
	}
	metadata, ok := sourcecatalog.ResolveObjectCreationMetadata(spec.ID, spec.Connector)
	if !ok {
		return sourceObjectCreationMetadataToModel(source.ObjectCreationMetadata{
			Supported:       false,
			ObjectKind:      spec.Contract.DefaultObjectKind,
			RequiresColumns: false,
		}), nil
	}
	return sourceObjectCreationMetadataToModel(metadata), nil
}

// SourceObjects is the resolver for the SourceObjects field.
func (r *queryResolver) SourceObjects(ctx context.Context, parent *model.SourceObjectRefInput, kinds []model.SourceObjectKind) ([]*model.SourceObject, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}
	resolvedParent := sourceRefFromInput(parent)
	if err := source.ValidateBrowseSupported(spec, resolvedParent); err != nil {
		return nil, err
	}

	browser, ok := source.AsSourceBrowser(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source browsing is not supported")
	}

	kindFilter := make([]source.ObjectKind, 0, len(kinds))
	for _, kind := range kinds {
		kindFilter = append(kindFilter, source.ObjectKind(kind))
	}

	objects, err := browser.ListObjects(ctx, resolvedParent, kindFilter)
	if err != nil {
		return nil, err
	}
	return sourceObjectModels(spec, objects), nil
}

// SourceObject is the resolver for the SourceObject field.
func (r *queryResolver) SourceObject(ctx context.Context, ref model.SourceObjectRefInput) (*model.SourceObject, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}
	resolvedRef := sourceRefFromInput(&ref)
	if err := validateSourceObjectAction(spec, resolvedRef, source.ActionInspect); err != nil {
		return nil, err
	}

	browser, ok := source.AsSourceBrowser(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source browsing is not supported")
	}

	object, err := browser.GetObject(ctx, *resolvedRef)
	if err != nil {
		return nil, err
	}
	return sourceObjectToModel(*object), nil
}

// SourceRows is the resolver for the SourceRows field.
func (r *queryResolver) SourceRows(ctx context.Context, ref model.SourceObjectRefInput, where *model.WhereCondition, sort []*model.SortCondition, pageSize int, pageOffset int) (*model.RowsResult, error) {
	if pageSize <= 0 {
		return nil, errors.New("pageSize must be greater than 0")
	}
	if pageSize > env.MaxPageSize {
		return nil, fmt.Errorf("pageSize must not exceed %d", env.MaxPageSize)
	}
	if pageOffset < 0 {
		return nil, errors.New("pageOffset must not be negative")
	}

	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}
	resolvedRef := sourceRefFromInput(&ref)
	if err := validateSourceObjectAction(spec, resolvedRef, source.ActionViewRows); err != nil {
		return nil, err
	}

	reader, ok := source.AsTabularReader(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source rows are not supported")
	}

	rowsResult, err := reader.ReadRows(ctx, *resolvedRef, queryWhereConditionFromModel(where), querySortConditionsFromModel(sort), pageSize, pageOffset)
	if err != nil {
		return nil, err
	}

	columns, err := reader.Columns(ctx, *resolvedRef)
	if err != nil {
		log.WithError(err).Warn("Failed to load source columns for row metadata")
		return rowsResultToModel(rowsResult), nil
	}

	return mergeRowsColumns(rowsResult, columns), nil
}

// SourceContent is the resolver for the SourceContent field.
func (r *queryResolver) SourceContent(ctx context.Context, ref model.SourceObjectRefInput) (*model.SourceContent, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}
	resolvedRef := sourceRefFromInput(&ref)
	if err := validateSourceObjectAction(spec, resolvedRef, source.ActionViewContent); err != nil {
		return nil, err
	}

	reader, ok := source.AsContentReader(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source content is not supported")
	}

	content, err := reader.ReadContent(ctx, *resolvedRef)
	if err != nil {
		return nil, err
	}
	return sourceContentToModel(content), nil
}

// SourceColumns is the resolver for the SourceColumns field.
func (r *queryResolver) SourceColumns(ctx context.Context, ref model.SourceObjectRefInput) ([]*model.Column, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}
	resolvedRef := sourceRefFromInput(&ref)
	if err := validateSourceObjectAction(spec, resolvedRef, source.ActionInspect); err != nil {
		return nil, err
	}

	reader, ok := source.AsTabularReader(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source columns are not supported")
	}

	columns, err := reader.Columns(ctx, *resolvedRef)
	if err != nil {
		return nil, err
	}
	return MapColumnsToModel(columns), nil
}

// SourceColumnsBatch is the resolver for the SourceColumnsBatch field.
func (r *queryResolver) SourceColumnsBatch(ctx context.Context, refs []*model.SourceObjectRefInput) ([]*model.SourceObjectColumns, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}

	reader, ok := source.AsTabularReader(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source columns are not supported")
	}

	sourceRefs := make([]source.ObjectRef, 0, len(refs))
	for _, ref := range refs {
		if ref == nil {
			continue
		}
		resolvedRef := sourceRefFromInput(ref)
		if err := validateSourceObjectAction(spec, resolvedRef, source.ActionInspect); err != nil {
			return nil, err
		}
		sourceRefs = append(sourceRefs, *resolvedRef)
	}

	results, err := reader.ColumnsBatch(ctx, sourceRefs)
	if err != nil {
		return nil, err
	}
	return sourceObjectColumnsToModel(results), nil
}

// SourceFieldConstraints is the resolver for the SourceFieldConstraints field.
func (r *queryResolver) SourceFieldConstraints(ctx context.Context, ref model.SourceObjectRefInput) ([]*model.SourceFieldConstraints, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}
	resolvedRef := sourceRefFromInput(&ref)
	if err := validateSourceObjectAction(spec, resolvedRef, source.ActionInspect); err != nil {
		return nil, err
	}

	reader, ok := source.AsFieldConstraintReader(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source field constraints are not supported")
	}

	constraints, err := reader.FieldConstraints(ctx, *resolvedRef)
	if err != nil {
		return nil, err
	}
	return MapFieldConstraintsToModel(constraints), nil
}

// RunSourceQuery is the resolver for the RunSourceQuery field.
func (r *queryResolver) RunSourceQuery(ctx context.Context, query string) (*model.RowsResult, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}
	if err := source.ValidateSurfaceSupported(spec, source.SurfaceQuery); err != nil {
		return nil, err
	}
	if err := source.ValidateRootActionSupported(spec, source.ActionExecute); err != nil {
		return nil, err
	}

	runner, ok := source.AsQueryRunner(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source queries are not supported")
	}

	rowsResult, err := runner.RunQuery(ctx, query)
	if err != nil {
		return nil, err
	}
	return rowsResultToModel(rowsResult), nil
}

// SourceGraph is the resolver for the SourceGraph field.
func (r *queryResolver) SourceGraph(ctx context.Context, ref *model.SourceObjectRefInput) ([]*model.GraphUnit, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		return nil, err
	}
	resolvedRef := sourceRefFromInput(ref)
	if err := source.ValidateGraphSupported(spec, resolvedRef); err != nil {
		return nil, err
	}

	reader, ok := source.AsGraphReader(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, errors.New("source graph is not supported")
	}

	graphUnits, err := reader.ReadGraph(ctx, resolvedRef)
	if err != nil {
		return nil, err
	}
	return graphUnitsToModel(graphUnits, resolvedRef, spec.Contract.DefaultObjectKind), nil
}

// AIProviders is the resolver for the AIProviders field.
func (r *queryResolver) AIProviders(ctx context.Context) ([]*model.AIProvider, error) {
	chatProviders := envconfig.GetConfiguredChatProviders()
	aiProviders := make([]*model.AIProvider, 0, len(chatProviders))
	for _, provider := range chatProviders {
		ap := &model.AIProvider{
			Type:                 provider.Type,
			Name:                 provider.Name,
			ProviderID:           provider.ProviderId,
			IsEnvironmentDefined: true,
			IsGeneric:            provider.IsGeneric,
		}
		if provider.Icon != "" {
			ap.Icon = new(provider.Icon)
		}
		aiProviders = append(aiProviders, ap)
	}
	return aiProviders, nil
}

// AIModel is the resolver for the AIModel field.
func (r *queryResolver) AIModel(ctx context.Context, providerID *string, modelType string, token *string) ([]string, error) {
	provider := ""
	if providerID != nil {
		provider = *providerID
	}
	requestToken := ""
	if token != nil {
		requestToken = *token
	}
	models, err := llm.ListSupportedModels(llm.ModelLookupOptions{
		ProviderID:          provider,
		ModelType:           modelType,
		Token:               requestToken,
		ConfiguredProviders: envconfig.GetConfiguredChatProviders(),
		AllowTokenFallback:  true,
	})
	if err != nil {
		log.WithFields(log.Fields{
			"operation":   "GetSupportedModels",
			"model_type":  modelType,
			"provider_id": providerID,
			"error":       err.Error(),
		}).Error("AI operation failed")
		return nil, err
	}
	return models, nil
}

// SettingsConfig is the resolver for the SettingsConfig field.
func (r *queryResolver) SettingsConfig(ctx context.Context) (*model.SettingsConfig, error) {
	currentSettings := settings.Get()
	return &model.SettingsConfig{
		MetricsEnabled:        &currentSettings.MetricsEnabled,
		DisableCredentialForm: env.DisableCredentialForm,
		EnableNewUI:           env.IsNewUIEnabled,
		MaxPageSize:           env.MaxPageSize,
	}, nil
}

// MockDataMaxRowCount is the resolver for the MockDataMaxRowCount field.
func (r *queryResolver) MockDataMaxRowCount(ctx context.Context) (int, error) {
	return mockdata.GetMockDataGenerationMaxRowCount(), nil
}

// AnalyzeMockDataDependencies analyzes FK dependencies for mock data generation.
func (r *queryResolver) AnalyzeMockDataDependencies(ctx context.Context, ref model.SourceObjectRefInput, rowCount int, fkDensityRatio *int) (*model.MockDataDependencyAnalysis, error) {
	return analyzeMockDataDependenciesForRef(ctx, ref, rowCount, fkDensityRatio)
}

// SSLStatus is the resolver for the SSLStatus field.
func (r *queryResolver) SSLStatus(ctx context.Context) (*model.SSLStatus, error) {
	spec, session, err := getSourceSessionForContext(ctx)
	if err != nil {
		log.Debug("[SSL] SSLStatus resolver: no plugin context")
		return nil, nil //nolint:nilerr
	}
	reader, ok := source.AsSecurityReader(sourceAuditScopeFromContext(ctx, spec), session)
	if !ok {
		return nil, nil
	}

	log.Debugf("[SSL] SSLStatus resolver: querying SSL status for %s", spec.ID)
	status, err := reader.SSLStatus(ctx)
	if err != nil {
		log.Warnf("[SSL] SSLStatus resolver: error getting SSL status: %v", err)
		return nil, err
	}

	// Return nil if SSL status is not applicable (e.g., SQLite)
	if status == nil {
		log.Debugf("[SSL] SSLStatus resolver: SSL not applicable for %s", spec.ID)
		return nil, nil
	}

	log.Debugf("[SSL] SSLStatus resolver: %s connection SSL enabled=%t, mode=%s",
		spec.ID, status.IsEnabled, status.Mode)

	return &model.SSLStatus{
		IsEnabled: status.IsEnabled,
		Mode:      status.Mode,
	}, nil
}

// SourceQuerySuggestions is the resolver for the SourceQuerySuggestions field.
func (r *queryResolver) SourceQuerySuggestions(ctx context.Context, ref *model.SourceObjectRefInput) ([]*model.SourceQuerySuggestion, error) {
	return sourceQuerySuggestionsForRef(ctx, ref)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
