/*
 * Copyright 2025 Clidey, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package database

import (
	"context"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	coreimporter "github.com/clidey/whodb/core/src/importer"
	"github.com/clidey/whodb/core/src/source"
)

// ImportOptions configures how data is imported.
type ImportOptions struct {
	HasHeader          bool
	Delimiter          rune
	CreateTable        bool
	BatchSize          int
	Mode               coreimporter.Mode
	Sheet              string
	UseHeaderMapping   *bool
	AllowAutoGenerated bool
}

// ImportResult reports the outcome of an import operation.
type ImportResult struct {
	RowsImported int
	TableCreated bool
}

var importErrorMessages = map[string]string{
	"import.validation.generic":                        "import validation failed",
	"import.validation.file_too_large":                 "file exceeds the maximum size",
	"import.validation.invalid_options":                "invalid import options",
	"import.validation.unsupported_format":             "unsupported import format",
	"import.validation.ambiguous_delimiter":            "CSV delimiter could not be detected",
	"import.validation.invalid_delimiter":              "CSV delimiter is invalid",
	"import.validation.parse_failed":                   "file could not be read",
	"import.validation.no_columns":                     "no columns detected in the file",
	"import.validation.row_too_many_columns":           "a row has more columns than expected",
	"import.validation.row_limit_exceeded":             "row count exceeds the maximum allowed",
	"import.validation.duplicate_header":               "file header contains duplicate column names",
	"import.validation.empty_header":                   "file header contains an empty column name",
	"import.validation.column_count_mismatch":          "column count does not match the target table",
	"import.validation.column_count_insertable":        "column count does not match insertable target columns",
	"import.validation.column_unknown":                 "file columns do not match the target table",
	"import.validation.column_generated":               "the import targets a generated column",
	"import.validation.column_auto_generated":          "the import targets an auto-generated column",
	"import.validation.mapping_invalid":                "column mapping is invalid",
	"import.validation.auto_generated_requires_toggle": "auto-generated columns were detected; enable auto-generated imports to continue",
	"import.error.no_rows":                             "no rows found to import",
	"import.error.table_columns":                       "failed to read target table columns",
	"import.error.import_failed":                       "import failed",
	"import.error.clear_failed":                        "failed to clear existing data before import",
	"import.error.insert_failed":                       "failed to insert imported rows",
	"import.error.upsert_no_pk":                        "upsert mode requires a primary key on the target table",
	"import.error.upsert_not_supported":                "this database does not support upsert imports",
}

// ReadCSV reads a CSV file and returns headers and rows.
// If hasHeader is true, the first row is used as column names.
func ReadCSV(filePath string, delimiter rune, hasHeader bool) ([]string, [][]string, error) {
	return ReadFileForImport(filePath, ImportOptions{
		HasHeader: hasHeader,
		Delimiter: delimiter,
	})
}

// ReadExcel reads the first sheet of an Excel file and returns headers and rows.
func ReadExcel(filePath string, hasHeader bool) ([]string, [][]string, error) {
	return ReadFileForImport(filePath, ImportOptions{
		HasHeader: hasHeader,
	})
}

// DetectDelimiter guesses the CSV delimiter by examining the first few lines.
func DetectDelimiter(filePath string) rune {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return ','
	}

	delimiter, err := coreimporter.DetectCSVDelimiter(data)
	if err != nil || len(delimiter) != 1 {
		return ','
	}

	return rune(delimiter[0])
}

// DetectFormat returns "csv" or "excel" based on file extension.
func DetectFormat(filePath string) string {
	if coreimporter.FormatFromPath(filePath) == coreimporter.FileFormatExcel {
		return "excel"
	}
	return "csv"
}

// InferColumnTypes examines sample data rows and returns SQL type names.
func InferColumnTypes(headers []string, rows [][]string) []string {
	types := make([]string, len(headers))
	for idx := range types {
		types[idx] = inferColumnType(idx, rows)
	}
	return types
}

func inferColumnType(colIdx int, rows [][]string) string {
	hasInt, hasFloat, hasBool := true, true, true
	nonEmpty := 0

	limit := len(rows)
	if limit > 100 {
		limit = 100
	}

	for _, row := range rows[:limit] {
		if colIdx >= len(row) || row[colIdx] == "" {
			continue
		}

		val := strings.TrimSpace(row[colIdx])
		nonEmpty++

		if _, err := strconv.ParseInt(val, 10, 64); err != nil {
			hasInt = false
		}
		if _, err := strconv.ParseFloat(val, 64); err != nil {
			hasFloat = false
		}

		lower := strings.ToLower(val)
		if lower != "true" && lower != "false" && lower != "0" && lower != "1" {
			hasBool = false
		}
	}

	if nonEmpty == 0 {
		return "TEXT"
	}
	if hasBool {
		return "BOOLEAN"
	}
	if hasInt {
		return "INTEGER"
	}
	if hasFloat {
		return "REAL"
	}

	return "TEXT"
}

// ImportData imports parsed rows into the database using the manager's current connection.
func (m *Manager) ImportData(schema, tableName string, headers []string, rows [][]string, opts ImportOptions) (*ImportResult, error) {
	start := time.Now()
	defer func() {
		m.logOperation(fmt.Sprintf("ImportData(%s, %d rows)", tableName, len(rows)), start, len(rows), nil)
	}()

	if m.currentConnection == nil {
		return nil, fmt.Errorf("not connected to any database")
	}
	if m.config.GetReadOnly() {
		return nil, ErrReadOnly
	}

	spec, session, err := m.currentSourceSession(context.Background())
	if err != nil {
		return nil, err
	}

	manager, ok := session.(source.ObjectManager)
	if !ok {
		return nil, fmt.Errorf("object management is not supported for %s", spec.Label)
	}

	result := &ImportResult{}

	if opts.CreateTable {
		types := InferColumnTypes(headers, rows)
		fields := make([]source.Record, len(headers))
		for idx, header := range headers {
			fields[idx] = source.Record{
				Key:   header,
				Value: types[idx],
			}
		}

		parentRef, err := m.storageUnitParentRef(spec, schema)
		if err != nil {
			return nil, err
		}

		created, err := manager.CreateObject(context.Background(), parentRef, tableName, fields)
		if err != nil {
			return nil, fmt.Errorf("create table: %w", err)
		}
		result.TableCreated = created
	}

	targetColumns, err := m.GetColumns(schema, tableName)
	if err != nil {
		return nil, humanizeImportError(fmt.Errorf("%s", "import.error.table_columns"))
	}

	mappings, _, err := coreimporter.BuildDefaultMappings(
		headers,
		targetColumns,
		opts.useHeaderMapping(),
		opts.AllowAutoGenerated,
	)
	if err != nil {
		return nil, humanizeImportError(err)
	}

	importer, ok := session.(source.DataImporter)
	if !ok {
		return nil, fmt.Errorf("importing data is not supported for %s", spec.Label)
	}

	ref, err := m.storageUnitRef(spec, schema, tableName)
	if err != nil {
		return nil, err
	}

	importResult, err := importer.ImportData(context.Background(), ref, source.ImportRequest{
		Mode:               source.ImportMode(opts.modeOrDefault()),
		Parsed:             source.ParsedImportFile{Columns: headers, Rows: rows},
		Mapping:            sourceImportMappings(mappings),
		AllowAutoGenerated: opts.AllowAutoGenerated,
		BatchSize:          opts.batchSizeOrDefault(),
	})
	if err != nil {
		return nil, humanizeImportError(err)
	}

	if importResult != nil {
		result.RowsImported = importResult.RowsImported
	}
	m.cache.Clear()

	return result, nil
}

// ReadFileForImport reads a CSV or Excel file and returns headers and rows.
func ReadFileForImport(filePath string, opts ImportOptions) ([]string, [][]string, error) {
	parsed, err := parseImportFile(filePath, opts, 0, true)
	if err != nil {
		return nil, nil, humanizeImportError(err)
	}

	return parsed.Columns, parsed.Rows, nil
}

// PreviewImport reads a file and returns the first N rows for preview.
func PreviewImport(filePath string, opts ImportOptions, maxRows int) ([]string, [][]string, error) {
	parsed, err := parseImportFile(filePath, opts, maxRows, false)
	if err != nil {
		return nil, nil, humanizeImportError(err)
	}

	return parsed.Columns, parsed.Rows, nil
}

func parseImportFile(filePath string, opts ImportOptions, maxRows int, enforceRowCap bool) (*coreimporter.ParsedFile, error) {
	data, err := coreimporter.ReadFile(filePath, coreimporter.MaxFileSizeBytes)
	if err != nil {
		return nil, err
	}

	return coreimporter.ParseFile(
		data,
		opts.fileOptions(filePath),
		maxRows,
		enforceRowCap,
	)
}

func (opts ImportOptions) fileOptions(filePath string) *coreimporter.FileOptions {
	var delimiter *string
	if opts.Delimiter != 0 {
		value := string(opts.Delimiter)
		delimiter = new(value)
	}

	var sheet *string
	if opts.Sheet != "" {
		value := opts.Sheet
		sheet = new(value)
	}

	return &coreimporter.FileOptions{
		Format:    coreimporter.FormatFromPath(filePath),
		Delimiter: delimiter,
		Sheet:     sheet,
		HasHeader: opts.HasHeader,
	}
}

func (opts ImportOptions) useHeaderMapping() bool {
	if opts.UseHeaderMapping != nil {
		return *opts.UseHeaderMapping
	}
	return opts.HasHeader
}

func (opts ImportOptions) modeOrDefault() coreimporter.Mode {
	if opts.Mode == "" {
		return coreimporter.ModeAppend
	}
	return opts.Mode
}

func (opts ImportOptions) batchSizeOrDefault() int {
	if opts.BatchSize <= 0 {
		return 500
	}
	return opts.BatchSize
}

func sourceImportMappings(mappings []coreimporter.ColumnMapping) []source.ImportColumnMapping {
	converted := make([]source.ImportColumnMapping, 0, len(mappings))
	for _, mapping := range mappings {
		converted = append(converted, source.ImportColumnMapping{
			SourceColumn: mapping.SourceColumn,
			TargetColumn: mapping.TargetColumn,
			Skip:         mapping.Skip,
		})
	}
	return converted
}

func humanizeImportError(err error) error {
	key := coreimporter.ErrorKeyFromError(err)
	if key == "" {
		return err
	}

	message, ok := importErrorMessages[key]
	if !ok {
		message = importErrorMessages["import.validation.generic"]
	}

	return fmt.Errorf("%s", message)
}
